### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#100]
#17 基本文法のNumberについて

[Number](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number)は使うところが限られているけど、
JavaScriptが浮動小数点数を使うという説明をしようと思ったら結構使う値が定義されている。
なので、 `0.1 + 0.2 === 0.3 ; // => false` を説明するという流れでNumberの話をしてみるとかは面白いのかも。
- [You-Dont-Know-JS/ch2.md at master · getify/You-Dont-Know-JS](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20&%20grammar/ch2.md)

もう一つは Math の方は数学的な計算に便利なものが色々あるよぐらいの話で終わると思う。

この辺を頑張ってるライブラリとしてはmath.jsとか。
- [math.js | an extensive math library for JavaScript and Node.js](http://mathjs.org/)

**Comment by azu** [comment]
イマイチ JavaScriptでBigNumberとか精度が必要な計算をする定番の方法を知らない。
何が定番何だろ?

**Comment by laco0416** [comment]
そういう分野でJS書いてる人に聞いてみようと思います

**Comment by azu** [comment]
http://floating-point-gui.de/ 浮動小数点数ガイド

**Comment by azu** [comment]
[the new code – Math Constants in JavaScript](http://thenewcode.com/1117/Math-Constants-in-JavaScript "the new code – Math Constants in JavaScript") Math.*

**Comment by azu** [comment]
なぜNaNはNumberか
[Why "typeof NaN === 'number'" : javascript](https://www.reddit.com/r/javascript/comments/4xzaus/why_typeof_nan_number/ "Why &#34;typeof NaN === &#39;number&#39;&#34; : javascript")

**Comment by azu** [comment]
- [Bartek Szopka: Everything you never wanted to know about JavaScript numbers -- JSConf EU 2013 - YouTube](https://www.youtube.com/watch?v=MqHDDtVYJRI)
- [Everything you never wanted to know about JavaScript numbers // Speaker Deck](https://speakerdeck.com/bartoszopka/everything-you-never-wanted-to-know-about-javascript-numbers)

Numberについて面白い話 0.1 + 0.2 とかもでてきてる

**Comment by azu** [comment]
```js
Object.getOwnPropertyNames(Number).filter(p => typeof Number[p] === "function" && Number[p] !== window[p]).forEach((t) => console.log(t))
 // [ "isFinite", "isInteger", "isNaN", "isSafeInteger" ]
```

parse系はグローバルと同じ

**Comment by yumetodo** [comment]
そういえば

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">parseInt完全に理解した <a href="https://t.co/JbgpZ1jQud">pic.twitter.com/JbgpZ1jQud</a></p>&mdash; 🐬ハイクォリティ・ツイート⚓️9/4←🎂 (@mzyy94) <a href="https://twitter.com/mzyy94/status/770435537312161792">2016年8月30日</a></blockquote>

```js
parseInt(0.000001); // => 0
parseInt(0.0000001); // => 1
(0.000001).toString(); // => "0.000001"
(0.0000001).toString(); // => "1e-7"
parseInt((0.000001).toString()); // => 0
parseInt((0.0000001).toString()); // => 1
```

なんて話もあったな・・・

**Comment by azu** [comment]
parseIntの引数にはstringを指定するという話なので、
numberを指定した時点で大体おかしいという話ですね。 #129 
後は、intなので浮動小数点数であるeが理解できないのはおかしくないかなという感じです。
(まあレガシーな機能なので、後方互換性も壊せないし、何でもは無理な感じですね。Data.parseなどもそうですが、パース系は大体例外的な挙動が多い印象)

**Comment by azu** [comment]
浮動小数点数同士の比較ってどうやるのが一般的なんだろなー。

- [scijs/almost-equal: Test if two floats are nearly equal](https://github.com/scijs/almost-equal)
- [miguelmota/epsilon-equal: Compares two numbers taking the standard epsilon value for double precision into consideration.](https://github.com/miguelmota/epsilon-equal)
- [The Floating-Point Guide - Error Propagation](http://floating-point-gui.de/errors/propagation/ "The Floating-Point Guide - Error Propagation")

**Comment by mzyy94** [comment]
横から失礼します。

`parseInt`の第一引数はECMAScript仕様にはMUST BEとは書かれておらず、むしろ文字列型でないオブジェクトが渡された場合に`ToString`を挟んで適切に処理を行うよう記載があります。
http://www.ecma-international.org/ecma-262/6.0/#sec-parseint-string-radix
ですので、stringであることが必須ということはなく、*大体おかしい*と一蹴りできる話でもないかと思います。
確かに暗黙の型変換は学習の上では障壁になるため、ここでは`parseInt`の第一引数にstringを渡すことを示しておくのが良いという意見には賛同できます。

横から失礼しました。

**Comment by mzyy94** [comment]
再度横から失礼します。

浮動小数点同士の比較においては、ECMAScript標準で浮動小数点の扱いが規定されている範囲外において、
次のような**ブラウザの実装依存**による挙動の差異があることを熟知し、検証を重ねたうえで内容を検討なささるとよろしいかと思います。

> これがわかったんだからゆるして！ https://pbs.twimg.com/media/CrGWvUfUAAA4jVa.jpg
> 
> — :dolphin:ハイクォリティ・ツイート:anchor:9/4←:birthday: (@mzyy94) 2016年8月30日

https://twitter.com/mzyy94/status/770562753358467072

横から失礼しました。

**Comment by azu** [comment]
> stringであることが必須ということはなく、大体おかしいと一蹴りできる話でもないかと思います。

#129 にも書いていますが、JavaScriptは歴史的に型エラーに対してかなり緩やかな方針になってます。
仕様的にはそうですが、現実的にnumberを渡す使い方はしてはいけないものだと思います。
`isNaN`も明らかにおかしなことになっていて、仕様的には暗黙的な型変換が行われます。
(しかし、これは`Number.isNaN`で修正されています。ですが、Annex Bとかではないのは、歴史的に仕様がおかしかっただけで、独自拡張でできたものではないからだと思います)

**Comment by azu** [comment]
[the new code – Web Developer Reading List: Maths in JavaScript](http://thenewcode.com/1131/Web-Developer-Reading-List-Maths-in-JavaScript "the new code – Web Developer Reading List: Maths in JavaScript") 
Mathの解説記事シリーズ

**Comment by yumetodo** [comment]
あ・・・ツイートを引用したらメンション飛んでしまっていました、すみません。

>確かに暗黙の型変換は学習の上では障壁になるため、ここではparseIntの第一引数にstringを渡すことを示しておくのが良いという意見には賛同できます。

そうですね。

**Comment by azu** [comment]
[JavaScriptでの小数点の計算の誤差について - Qiita](http://qiita.com/k_moto/items/0b576a3351b77fb0aa98 "JavaScriptでの小数点の計算の誤差について - Qiita")

`Number.EPSILON` を使った方法は載ってなかった

- [Number.EPSILON - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON "Number.EPSILON - JavaScript | MDN")

**Comment by azu** [comment]
はじめてのJavaScriptだと http://mathjs.org/ が紹介されてた
![mu pdf viewer 2017-03-12 14-23-44](https://cloud.githubusercontent.com/assets/19714/23829219/85255ac2-072f-11e7-8688-a335532d95bf.png)

**Comment by azu** [comment]
フォーマット系だと http://numeraljs.com/

![mu pdf viewer 2017-03-12 14-26-32](https://cloud.githubusercontent.com/assets/19714/23829227/ee53f0d0-072f-11e7-9983-e6ef5fdfa9d9.png)

この辺はi18nAPIとかformat.jsでもいい気がする

**Comment by lacolaco** [comment]
```
Mathの章はDateの章ぐらい?

Math.random, max, min とか

どのメソッドを触れる
Dateはユースケースベースで触れるメソッドを決めている
```

https://github.com/asciidwango/js-primer/issues/299#issuecomment-332799358

**Comment by lacolaco** [comment]
spread operatorとmin maxの例とか。

**Comment by azu** [comment]
3ステップで学ぶJavaScript入門だと
Math.random を使ったおみくじを例にMath紹介してた

**Comment by azu** [comment]
微妙に増えてたので📝。
- [tabatkins/js-seeded-random: Proposal for an options argument to be added to JS's Math.random() function, and some options to start it with.](https://github.com/tabatkins/js-seeded-random "tabatkins/js-seeded-random: Proposal for an options argument to be added to JS&#39;s Math.random() function, and some options to start it with.")
- [mathiasbynens/proposal-number-fromstring: {BigInt,Number}.fromString(string, radix)](https://github.com/mathiasbynens/proposal-number-fromstring "mathiasbynens/proposal-number-fromstring: {BigInt,Number}.fromString(string, radix)")

**Comment by azu** [comment]
これ閉じてよかった
