### ISSUE TITLE
`isEmptyString`（空文字かどうかを判定する関数）の実装をシンプルに

### ISSUE THREAD

**Issue by yassh** [asciidwango/js-primer#1004]
## 該当ページ

https://jsprimer.net/basic/implicit-coercion/#judge-empty-string

## リクエスト/提案内容

```js
// 空文字かどうかを判定
function isEmptyString(str) {
    // String型でlengthが0の値の場合はtrueを返す
    return typeof str === "string" && str.length === 0;
}
```

こうなっていますが、

```js
// 空文字かどうかを判定
function isEmptyString(str) {
    return str === "";
}
```

これでは駄目でしょうか？

## 期待する結果

`isEmptyString`の実装がシンプルになる。

**Comment by azu** [comment]
別解としてはありだと思います

> この場合、空文字とは「String型で文字長が0の値」であると定義すること

ただ文中でこう定義してるので、そのままコードに落とした感じではありますね。

**Comment by azu** [comment]
https://deploy-preview-1005--js-primer.netlify.com/basic/implicit-coercion/#judge-empty-string
#1005 で例として加えてみましたが、どうでしょうか?
冗長に感じる場合もありそうなので少し迷っています。

**Comment by yumetodo** [comment]
> 空文字とは「String型で文字長が0の値」であると定義すること

これがまさに`""`なのであって、だからこれと厳密一致比較すればいいよね、というふうに持っていくほうが素直なのではと思います。`typeof str === "string" && str.length === 0;`って冗長にすぎるような。

**Comment by yassh** [comment]
そもそも、

> この場合、空文字とは「String型で文字長が0の値」であると定義すること

この定義が冗長に感じますね。「空文字とは`""`である」という定義でよい気がします。

それと、「空文字」ではなく「空文字列」が正しい表現だと思います。

**Comment by azu** [comment]
`""`を空文字というのはなんか説明として微妙な気がしています。
`''`や``` `` ```も空文字列で、それはあくまで空文字列を表現するリテラル表現だと思うので、空文字列ですというにはなんか違う気がしています。

**Comment by yumetodo** [comment]
> それと、「空文字」ではなく「空文字列」が正しい表現だと思います。

それはそう

> 空文字列とは""である

これは @azu 氏と同様違和感があります。

**Comment by azu** [comment]
特にフィードバックがないので閉じます。
必要に応じてRe-Openしてください

**Comment by yumetodo** [comment]
あれっ、見落としてました。

自分の意図としては、空文字列とは「String型で文字長が0の値」であると定義することはいいのですが、例の方は単に厳密一致比較するほうだけでいいのではないかという話を上の方でしていたと思います。
