### ISSUE TITLE
文章に句点（。）が抜けている箇所があります。

### ISSUE THREAD

**Issue by ymashimo0720** [asciidwango/js-primer#1023]
## 該当ページ

https://jsprimer.net/basic/read-eval-print/

## 説明

REPLはあくまで開発者向けの機能です ウェブサイトでは...（誤）
↓
REPLはあくまで開発者向けの機能です。ウェブサイトでは…（正）

**Comment by azu** [comment]
@kahei 。が抜けていたみたいです。

**Comment by kahei** [comment]
おお、なんと！　どうもありがとうございます。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/1069 で修正されました
