### ISSUE TITLE
「別々の name と NAME という名前の変数として認識されます。」をコードで検証する方法を教えてください。

### ISSUE THREAD

**Issue by mendelssohnbach** [asciidwango/js-primer#1025]
## 大文字と小文字を区別する

-[大文字と小文字を区別する](https://jsprimer.net/basic/introduction/#case-sensitive)

## 質問内容

> 別々の name と NAME という名前の変数として認識されます。

上記の説明を JavaScript コードを書いて検証するにはどうすればよいでしょうか？

```javascript
// falseが返されることを期待したが...
console.log(name === NAME);  // true
```

お時間のある時にでも、ご教示いただければ幸いです。

**Comment by yumetodo** [comment]
```js
// `name`という名前の変数を宣言
const name = "hello world";
// `NAME`という名前の変数を宣言
const NAME = "arikitari na world";
console.log(name === NAME);  // -> false
```

**Comment by azu** [comment]
@yumetodo さんが書いてる通りですね、

`===` は変数が参照してる**値**を比較する演算子なので、
`name`と`NAME`という変数に同じ文字列を定義すると、`name === NAME`は`true`担ってしまいますね。

```js
console.log(name === NAME); // true
```

なので、それぞれ変数に別の値を入れれば、変数が区別されてることがわかると思います。
https://github.com/asciidwango/js-primer/issues/1025#issuecomment-574080237 はそういう例ですね。

もっと単純に[Console API](https://jsprimer.net/basic/read-eval-print/#console-api)を使ってそれぞれの変数をコンソールに出力してみれば、それぞれの変数が別々の値を参照してる(つまり別々の変数名として存在している)ことがわかりますね。

```js
// `name`という名前の変数を宣言
const name = "a";
const NAME = "B";
// nameとNAMEがそれぞれ異なる値を参照してる
console.log(name);/ /  => "a"
console.log(NAME);  // => "B"
```

**Comment by mendelssohnbach** [comment]
yumetodo様 azu様 ありがとうございます。

厳密比較演算子 `===` で値を評価できるというのは理解しています。

```javascript
const name = "a";
const NAME = "a";
```

`const` で宣言した変数が違うものだというのも、見ればわかります。

これらが簡単にわかるので、変数が違うことをコードで検証することもできると考えました。

イメージとしては次のようなコードで検証できるのではないかと...

```javascript
'use strict';

const name = 'azu';
const NAME = 'suguru';

console.log(identifer[0].name === identifer[1].name);
```

**Comment by azu** [comment]
変数のリファレンスを取って比較したいという感じですかね?
JavaScriptは参照の値渡しなので、ポインタみたいなものがなくて表現しにくいのですね。
`const`で宣言した変数名の一覧をruntimeで取得する方法はないかもしれないです(`var`はちょっと違うのでできなくはないですが)

オブジェクトなら、プロパティ名(実際は変数と同じ)が異なるものとして設定されてることを、オブジェクトのプロパティ名を列挙する[Object.getOwnPropertyNames()](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames)を使うと分かりやすいかもですね。

```js
const object = {
  name: "a",
  NAME: "A"
};
// `obejct`が持つプロパティ名を列挙する
console.log(Object.getOwnPropertyNames(object));// ["a", "A"]

**Comment by mendelssohnbach** [comment]
azu様
回答ありがとうございます。

ぱっと見に簡単そうなことでも、難しいことがあるのですね。

`Object.getOwnPropertyNames()`　を読んでおきます。
