### ISSUE TITLE
Firefoxのスクショを更新する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1028]
イラストを差し替えるのと同じタイミングで、Firefoxのスクリーンショットを更新し直す

**Comment by azu** [comment]
1024 x 640で撮影する。

**Comment by azu** [comment]
エラーが赤が

**Comment by lacolaco** [comment]
@azu DevToolsの幅ってapplescriptから操作できたかどうかわかります？

**Comment by azu** [comment]
高さ? 
どっちにしてもマウス操作になる感じがする。
または `about:config` あたりに値が入ってそうな気はするので、これを起動時に無理やり書き換えるとかになるのかな
