### ISSUE TITLE
質問:テンプレートリテラルの模範的な使い方

### ISSUE THREAD

**Issue by mendelssohnbach** [asciidwango/js-primer#1035]
## 該当ページ
[テンプレートリテラル ](https://jsprimer.net/basic/data-type/#template-literal)

## 質問内容
テンプレートリテラルの模範的な使い方について教えてください。

単一行かつプレースホルダーを用いない文字列を  ` （バッククォート）で囲むことは推奨されませんか？

多くのサンプルでは `${}` のように文字列とともにプレースホルダーが用いられています。
しかし、単純な文字列をバッククォートで囲んでも例外などは発生しません。
単純な文字列をバッククォートで囲むことは慎むべきでしょうか？

```javascript
const greet = `hello world` ;
```
変数などに渡す文字列リテラルをバッククォートで囲むのは気持ち悪い。

```javascript
console.log(`hello world`);
```
`console.log()` に単純な文字列をバッククォートで囲って記述するのは楽ができる印象を持っている。

「恥ずかしくないコードを書く」との観点で、
テンプレートリテラルの模範的な使い方を教えてください。

**Comment by yumetodo** [comment]
ESLintで言うところの

```json
"quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": false }],
```

ないし

```json
"quotes": ["error", "double", { "avoidEscape": true, "allowTemplateLiterals": false }],
```

に従っておけばいいとは思いますがどうでしょう。

ref:
- https://eslint.org/docs/rules/quotes
- https://github.com/standard/eslint-config-standard/blob/eb187deec36e72bfea4034db1a81b0d7414f814a/eslintrc.json#L179

**Comment by mendelssohnbach** [comment]
回答ありがとうございます。

ESLint。名前しか聞いたことがない初心者ですが、
教示いただいたドキュメントを読んでおきます。
