### ISSUE TITLE
GitBookでの複数行に渡る文字列リテラルの表示の問題

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#105]
https://github.com/asciidwango/js-primer/blob/dec06b5ee1b68c1da81d5b11e6616a27d2b43802/source/basic/data-type/README.md
https://asciidwango.github.io/js-primer/basic/data-type/

sourceでは

    ```js
    "複数行の
    文字列を
    入れたい"; // Syntax Error
    ```

のように書かれており、GFMでは

```js
"複数行の
文字列を
入れたい"; // Syntax Error
```

のように表示できるが、GitBookでは

![default](https://cloud.githubusercontent.com/assets/10869046/17161850/c4525af8-53eb-11e6-9d95-55837aa862f5.png)

のように一行になってしまう。

これは問題ではないか

**Comment by azu** [comment]
@yumetodo ありがとうございます。
https://github.com/KazuhiroKuwabara/gitbook-plugin-japanese-support が原因だったようです。
修正致しました。
