### ISSUE TITLE
for...of文とstringの説明におけるcombining charactersの扱い

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#106]
https://github.com/asciidwango/js-primer/blob/71a13f3a087e418444d5872497c9af393c12a079/source/basic/loop/README.md
https://asciidwango.github.io/js-primer/basic/loop/

Unicodeには`combining characters`があるわけですが、これの扱いについて規格でなにか言及があったりするのでしょうか？

``` js
var s = "\u30db\u309a";

console.log(s); // => ポ
console.log(s.length); // => 2

for(var c of s) {
    console.log(c);
} // =>
//ホ
//゚
```

手元のFirefox47.0.1 Windows10では考慮されなかったので。

> JavaScriptではStringオブジェクトもiterableです。サロゲートペアも考慮し、文字列を1文字ずつ列挙することができます。

とありますが、これだと`combining characters`も考慮されるように読めてしまうので、`combining characters`の話を追記するか、サロゲートペアの話を除去するかが必要ではないかと思います。

cf.)
- http://tama-san.com/combining_character_sequence/
- #68

**Comment by azu** [comment]
📝 [字符串的扩展 - ECMAScript 6入门](http://es6.ruanyifeng.com/#docs/string "字符串的扩展 - ECMAScript 6入门")

**Comment by yumetodo** [comment]
Normalizeすればええやん、というノリのリンク先ですが、ところがどっこい

```js
var s = "\u0030\u20E3".normalize('NFC');

console.log(s); // => 0⃣
console.log(s.length); // => 2

for(var c of s) {
    console.log(c);
}// =>
//0
//⃣
``` 

こんな例も。Unicodeの絵文字はやはり闇だ。

**Comment by azu** [comment]
現在の記述は間違っているので、該当部分は削除しました。
ご報告ありがとうございます。

https://github.com/asciidwango/js-primer/commit/23f4ba8b676f8caa48f486b49435b5a71503ec87

後でまた書き直したい部分なので、Issueはとりあえずそのまま残しておきます。

**Comment by azu** [comment]
#643 #672 あたらいで大きく書き換わったので一度閉じます。
