### ISSUE TITLE
書籍用レイアウト/著者校正用PDF

### ISSUE THREAD

**Issue by kahei** [asciidwango/js-primer#1070]
まだ第1部の途中ですが、ラフレイアウトをしたtexファイルとPDFをpublish1ブランチにあげました。まだいろいろレイアウトにも問題が残っていますが、気がついた点があればお知らせください。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/publish1/TeX/main.pdf

**Comment by azu** [comment]
### HTML-likeコメント

`<!--` が `<!-` になってしまっている。

![3BDE692E-E3C2-4BC7-A93A-3B4268B94842](https://user-images.githubusercontent.com/19714/73943089-7e56d100-4933-11ea-9459-6e5f5f9547d2.png)

### セクション名

右上のセクション名まで ES2015の上付きが作ると少し見た目のバランスが悪いかなと思いました。

![C10DDAB0-2BB3-4167-8BAA-6A8041C31BA4](https://user-images.githubusercontent.com/19714/73943206-b5c57d80-4933-11ea-8f81-fe6f43abe0d6.png)

![8E918433-C689-4274-8738-1898BA2EB15A](https://user-images.githubusercontent.com/19714/73945808-3c7c5980-4938-11ea-8034-5522d6c1c95a.png)

ES2015がついてるところとそうでないところがあるみたいな気がする。


### nullのコラム

はみ出てる
`// undefined という名前の変数をエラーなく定義できる` のコメントは上に移動して大丈夫です。
![2C450D90-F2C9-477D-BEB5-4BBD66072070](https://user-images.githubusercontent.com/19714/73943752-a8f55980-4934-11ea-85ab-9dd9fc471742.png)

### 右シフト
単純にコードのコメントの書き方がよくない感じがします。
![91EA5AAF-25A0-4E22-BD97-117DE23E4116](https://user-images.githubusercontent.com/19714/73944136-67b17980-4935-11ea-8b48-264021238d89.png)

みたいに説明としてコメントを書くように書き換えちゃった方が見やすくなるかな。
```
console.log((-9) >>> 2); // => 1073741821
// 0b11111111111111111111111111110111 >>> 2 すると
// 0b00111111111111111111111111111101 となる
```

###　コードコメントのバッククオート

コード中のコメントでバッククートをコードを意味する記号として使ってるけど、
Markdownのコンテキストがない人がみたら ` にもなにか意味があるようにみえちゃうかもしれない。

単純に取り除くか、最初に説明いれたほうがいいのかな?
![67960D30-7068-4192-911E-9EA1A6539C3A](https://user-images.githubusercontent.com/19714/73944441-ee665680-4935-11ea-955f-528b6fea0cdb.png)


### コードの %

コード中の `%` のフォントが妙に縦に細い感じがしますが、こんなものですかね?

![3233FBD4-7395-48EB-9714-E70388643A91](https://user-images.githubusercontent.com/19714/73944574-2cfc1100-4936-11ea-8c8e-8c1edfff26a4.png)


### エスケープシーケンス

https://jsprimer.net/basic/string/#escape-sequence
`console.log("¯\_(ツ)_/¯"); ` がなんか変な描画になってますね。
![7A9D49B0-303F-49F7-ABDD-7420732B7022](https://user-images.githubusercontent.com/19714/73944844-99771000-4936-11ea-978b-090da874d0c5.png)

### 絵文字

絵文字って普通に出るんですね?
これモノクロになると思うのですが、モノクロで区別つくかな?
![778926B5-A35C-4612-BFFA-566838D4FBFA](https://user-images.githubusercontent.com/19714/73945045-02f71e80-4937-11ea-8f1d-5a84a4ed8d24.png)

### 1 ES2015 の 仕 様 編 集 者 で あ る...

https://jsprimer.net/basic/function-this/ の一番最後がおかしくなってる。
制御文字が混ざっておかしくなってる? 

![FCBF9FE8-9C5F-44F3-99FC-37AC2951C271](https://user-images.githubusercontent.com/19714/73945439-9fb9bc00-4937-11ea-8c53-56e42aecffd3.png)


#### SyntaxError

なんかここだけ文字幅が伸びている感じがする?

![79328A99-BDC0-4415-AF41-598D56F0A45E](https://user-images.githubusercontent.com/19714/73945606-e90a0b80-4937-11ea-8a61-d4f352997a7b.png)

### スクショ

文字サイズ感的に小さいので、もう少し拡大してとる方がいいかも
![CC702FEF-A7F6-4439-B8E6-11AC99B89C89](https://user-images.githubusercontent.com/19714/73945664-0048f900-4938-11ea-9f96-519a09d9032b.png)

**Comment by azu** [comment]
@kahei おおざっぱに一通り見てみました。

**Comment by kahei** [comment]
@azu どうもありがとうございます。それぞれ修正など入れますね。

**Comment by lacolaco** [comment]
目次
![image](https://user-images.githubusercontent.com/1529180/74079593-e238e100-4a7c-11ea-8ee6-0c6f3a62786a.png)
ESがイタリックになっている

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/74079685-3c867180-4a7e-11ea-8c3e-24e5f8c8378c.png)
これはまだラフだからですよね

**Comment by azu** [comment]
`{% if .. %} `のGitBookマクロ そういえば
https://github.com/asciidwango/js-primer/blob/master/tools/strip-markdown-extension.js では対応してなかったのか。

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/74080006-7194c300-4a82-11ea-9f05-58df46bfeb40.png)
このサイズではコンソールが出ていることはわかりにくそう

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/74080101-a81f0d80-4a83-11ea-923c-b74af35a5c82.png)
リンクが壊れてる

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/74080322-33010780-4a86-11ea-9965-48c478d5ad00.png)
これは普通に原稿のtypoかな？

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/74080341-6e033b00-4a86-11ea-9276-d05a841cf85a.png)
「知らない」がよさそう

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/74080429-68f2bb80-4a87-11ea-8ad4-d86dbe2dce3d.png)
幅溢れ

**Comment by lacolaco** [comment]
ざっくりひと通り見ました。幅溢れはこれからだと思うのでコメント控えます

**Comment by azu** [comment]
```diff
- `class`構文ではプロトタイプオブジェクトと参照する仕組みによって継承が行われています。
+ `class`構文ではプロトタイプオブジェクトを参照する仕組みによって継承が行われています。
```
https://github.com/asciidwango/js-primer/pull/1072

@kahei このtypoの修正 `publish1` ブランチのTexの方にどういう感じで取り込みます?

- PRをマージ -> @azu が `publish1` にもコミットする
- PRをマージ -> Texにも反映が必要ラベルをPull Requestに付けて管理する(`Need Update Tex`?とかのラベル管理) -> @kahei が `publish1` に反映する

どっちがいいですかね?

**Comment by kahei** [comment]
azuさんにもpublish1にコミットしてもらったほうがいいと思うので、よろしくお願いいたします。

**Comment by azu** [comment]
反映しました https://github.com/asciidwango/js-primer/commit/f7d600ba2db601906330b89309892d64d4d328e0

**Comment by kahei** [comment]
どうもありがとうございます！

**Comment by azu** [comment]
![D7C332E6-C929-4131-A2DE-484E9527CC1B](https://user-images.githubusercontent.com/19714/77129976-611c3300-6a99-11ea-9005-37232c528e42.png)
ES2015ラベルがまだ目次に残ってますね

**Comment by azu** [comment]
![8AAB2D6C-C609-42C0-8E99-3B1CCB2E3A4F](https://user-images.githubusercontent.com/19714/77131054-975bb180-6a9d-11ea-9318-c14eb995839b.png)

[詳細] の部分になにか記号が混じってる感じがします

**Comment by azu** [comment]
![FD6E5162-6997-4B62-82A2-748BAA219B38](https://user-images.githubusercontent.com/19714/77131393-d9392780-6a9e-11ea-8b92-c68c3142204e.png)

シングルクオートのとなりにスペースがあるように見えるけど、これはフォントの問題?

**Comment by azu** [comment]
![5ED3C477-AF86-4E5B-8896-268E79DF5849](https://user-images.githubusercontent.com/19714/77240914-f00e8400-6c2e-11ea-8a53-a007963f00fd.png)

const で定義したオブジェクトは変更可能のコラム 変なタイミングで割り込んでしまってるので調整が必要かもしれません。

**Comment by azu** [comment]
![52146D43-2DEC-4081-A5E9-253145ABB8A7](https://user-images.githubusercontent.com/19714/77240938-627f6400-6c2f-11ea-8e69-e2f9efdf948e.png)

オブジェクトのプロパティ名は文字列化される　も同様

**Comment by azu** [comment]
![9CB9A2C0-9202-4093-B53E-7F931C2C4D5B](https://user-images.githubusercontent.com/19714/77241005-1ed92a00-6c30-11ea-89e4-075bdce1ecdb.png)

プロトタイプオブジェクトの図 もへんな位置に割り込んでしまってるので、要調整な気がする。
(このイメージは概念的な図なのでGCと同じぐらいでそこまで必須という感じではなく、補助的な図のイメージ)

**Comment by azu** [comment]
![A52EBDFC-28B3-4BD8-B742-AE22CC6D9347](https://user-images.githubusercontent.com/19714/77243877-653f8080-6c52-11ea-9850-2dbb136e2c29.png)
`ReferenceError: x is not defined`
xの前になんか空間があるのはなんでだろ? justifyみたいなものがかかってるのかな

**Comment by azu** [comment]
![12CAF2F6-30A6-41C6-BF4C-BDB32E24374F](https://user-images.githubusercontent.com/19714/77431772-85bd3580-6e20-11ea-9c10-f5618c20f6ce.png)

Todoのtable中の文字がjustifyされてる感じがする

**Comment by azu** [comment]
03-17版を一通り読んで、レイアウト周りできになったところはこのissueに書きました。
https://github.com/asciidwango/js-primer/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+PR+Welcome%22
文章的なところはissueを作ったのでべっと対応していきます

**Comment by azu** [comment]
* [LaTeX Workshop - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop)
* [Visual Studio Code/LaTeX - TeX Wiki](https://texwiki.texjp.org/?Visual%20Studio%20Code%2FLaTeX)

で一応TeXのプレビューがVSCodeでできた。
![image](https://user-images.githubusercontent.com/19714/77822971-dee7da80-713a-11ea-9eae-fc00702b373f.png)

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/78420884-4bf4f600-768e-11ea-9617-aac3218ba0fe.png)

ホッケが化けて出ている

**Comment by kahei** [comment]
@azu 私の環境（macOS）では、ホッケの文字がきちんと表示されます。azuさんの環境を教えていただけますか？

**Comment by kahei** [comment]
@azu フォントを埋め込んだ暫定PDF（main2.pdf）を作ってアップしてみました。こちらで再度確認してみてください。ホッケの文字が見えると思います。

**Comment by azu** [comment]
あー、こっちの環境依存でしたか。
化けてたのはpdf.jsの古いバージョン([自作のビューア](https://github.com/azu/mu-pdf-viewer))で、最新のpdf.js(Firefoxに搭載されてるもの)なら問題ありませんでした。
main2.pdfでもおかしいのでビューア側が変な感じがします。

<img width="694" alt="image" src="https://user-images.githubusercontent.com/19714/78531637-c3f32580-7820-11ea-9429-9b631e215287.png">

他のビューアなら問題ありませんでした。(なので無視してもよさそう)

**Comment by kahei** [comment]
他のビューアで問題ないということなので、とりあえずこの問題は解決ということで。

**Comment by azu** [comment]
![2F0CD8A4-E7C9-4874-9A23-6ED5A6BC1D72](https://user-images.githubusercontent.com/19714/78641177-c79fae80-78eb-11ea-9976-beeb6930bb3b.png)
次の表で紹介するメソッド\footnote{\url{https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/}}は破壊的なメソッドです。

https://github.com/asciidwango/js-primer/blob/aaa2bab0e269f379b39d40c639f33e3bb338a76d/TeX/chap14.tex#L586

このfootnoteって元からありましたっけ?
Markdown版にはないっぽい。不要そうなので削除してして良さそうな気がします。

**Comment by kahei** [comment]
これ、表内のメソッドがリンクされているURLから作ったfootnoteですね。不要なら削除します。

**Comment by azu** [comment]
あー、なるほど。そのままでも大丈夫です

**Comment by kahei** [comment]
では、このままで。
あと、文章を修正するissueは2つかな？

**Comment by kahei** [comment]
こちらのissueに挙げられているものは修正しました。いったん、pushします。

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/78651168-ec4f5280-78fa-11ea-873e-8bcde6fb284f.png)

絵文字なんとか区別できそうですね

**Comment by kahei** [comment]
たぶん、だいじょうぶだと思います。

**Comment by azu** [comment]
一応、全部読み直して直しました。
#1144 は誤記だったので修正

残ってる
#1134  #1140  #1142 
は間違いではない/問題があるわけではないのでとりあえずはこのままで大丈夫

**Comment by kahei** [comment]
どうもありがとうございます。最終のレイアウト調整に入ります。

**Comment by azu** [comment]
出版したので、これは閉じる
