### ISSUE TITLE
変数名に使える名前のルール ←リンク切れ

### ISSUE THREAD

**Issue by yuuki-kouno** [asciidwango/js-primer#1071]
## 該当ページ

- https://jsprimer.net/basic/function-declaration/ 
ページのURLを入れてください

## 説明

第一部　基本文法　関数と変数　上から20行目？くらい　（「変数名に使える名前のルール」を参照）
というタグがリンク切れです

**Comment by azu** [comment]
ご報告ありがとうございます。修正しました。

**Comment by yuuki-kouno** [comment]
こちらこそとても分かりやすいドキュメントを書いていただいてありがとうございます。
