### ISSUE TITLE
既に使わなくていいイディオム/文法

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#108]
既に使わなくていいイディオム/文法 そういうのをまとめる場所です。
- 「何故使われていたのか」
- 「何故使わなくて良くなったか」

**Comment by laco0416** [comment]
http://qiita.com/cocottejs/items/cb2623316a0c82b603c4

**Comment by azu** [comment]
ショートコーディング向けの書き方は多くの場合使わなくてもいいやり方を使ったりして短く書いてる
http://qiita.com/ichimonji_haji/items/f602f6c437be9e7daa88

**Comment by laco0416** [comment]
即時関数の扱い スコープの話でもあるし、式と文の話でもある

**Comment by azu** [comment]
concat した場合のスコープ壊れについて

- "use strict"
- 先頭に謎の; が置いてある

**Comment by laco0416** [comment]
「何故使われていたのか」と「何故使わなくて良くなったか」が必要

**Comment by azu** [comment]
`__proto__` があるし

**Comment by laco0416** [comment]
ライブラリの中でしか使われないようなものはあえて無理に紹介はしない

**Comment by azu** [comment]
for..in文については既に書いた

**Comment by azu** [comment]
[Make your JavaScript code shine: knockout old ES5 hacks](https://rainsoft.io/make-your-javascript-code-shide-knockout-old-es5-hack/ "Make your JavaScript code shine: knockout old ES5 hacks")
これいい感じにまとまってる

**Comment by azu** [comment]
[Find a Substring in a JavaScript Array | Giga-ahm](http://adam.merrifield.ca/2016/08/08/find-a-substring-in-a-javascript-array/ "Find a Substring in a JavaScript Array | Giga-ahm")
```js
var arr = [ 'foo', 'bar' ];
var str = 'food.land';
var isTrue = !!arr.find( function (elem) {
    return !!~str.indexOf( elem );
});
```

Array#findとか使っても謎のイディオムっぽい

```js
var arr = [ 'foo', 'bar' ];
var str = 'food.land';
var isTrue = arr.some( function (elem) {
    return str.includes(elem);
});
```

やっぱり、今の状況で[暗黙的な型変換](https://github.com/asciidwango/js-primer/issues/53#issuecomment-239388624)を使って何かする必要があるケースは減ったと思う。
代わりに正攻法で同じことが出来るものがあったりする印象

**Comment by azu** [comment]
`isNaN` => `Number.isNaN`
`isFinite` => `Number.isFinite`

Good Parts本みたいに、悪いPartsとしてまとめちゃってもいいかもなー
本文で紹介するほどではないけど、知っていたほうが得みたいな感じのものが多い

**Comment by laco0416** [comment]
ESLintのコラムと良い感じに絡められそうな章

**Comment by azu** [comment]
[Underhanded JavaScript by Xuanyi Chew [Leanpub PDF/iPad/Kindle]](https://leanpub.com/underhandedjavascript "Underhanded JavaScript by Xuanyi Chew [Leanpub PDF/iPad/Kindle]")
JavaScriptのBad Partsについて学ぶ本

**Comment by azu** [comment]
code pointで文字数を数えるのに

```js
function strlen(str) {
  return str.length - (str.match(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g)||[]).length;
}
```

みたいにするパターン。
iterableでやったほうが簡潔 `[...str].length`
combining marksはできないけど

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/326

**Comment by lacolaco** [comment]
Bad Partsに吸収されるのでclose
