### ISSUE TITLE
質問 :「 期待する評価結果」の 2 進数表現について

### ISSUE THREAD

**Issue by lime1024** [asciidwango/js-primer#1084]
## 該当ページ
- [演算子 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/operator/#bit-operator)

## 質問内容
```
console.log(評価したい式); // => 期待する評価結果
```

該当ページのビット論理積やビット論理和等の説明において、「評価したい式」が 2 進数であるときの「期待する評価結果」が実際の実行結果である 10 進数では無く、2 進数であったことに違和感があります。とは言え、2 進数の計算なので 2 進数で表現したほうがわかりやすいことも理解できます。この記載が意図したものなのかが知りたいです。

```
// 自分が想定していたもの
console.log(0b1111 & 0b1001); // => 9

// 実際に記載されている説明
console.log(0b1111 & 0b1001); // => 0b1001
```

**Comment by azu** [comment]
```
0b1111
0b1001
-------
0b1001
```
という感じに見えるように書いたほうが、ビット演算の結果がイメージしやすいと思ったので、意図してですね。

**Comment by lime1024** [comment]
わかりました、意図した結果であれば大丈夫です！ありがとうございます。
