### ISSUE TITLE
core-js

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1089]
core-jsのstatusがあまり良くない状態なので、以下のpolyfillに関する具体的な記述を省くことを検討する。

https://github.com/asciidwango/js-primer/blob/4d6ed86562bce64474e1fb79ee8359fc85d371c3/source/basic/ecmascript/README.md#L187

Refs:

- https://github.com/zloirock/core-js/issues/767
- https://github.com/zloirock/core-js/issues/747#issuecomment-573318269

**Comment by yumetodo** [comment]
2019/11に1年6ヶ月の懲役刑を課され刑務所に収監ということは、2021/5までということだろうか。

**Comment by ssig33** [comment]
https://github.com/zloirock 2020/1/15 に収監されたようですね

**Comment by azu** [comment]
#1126 でいったんこのままでいくことにした。
今週大きな変更があったら2020/04/08までならギリギリ間に合いそうなので、そこで入れることにする。
