### ISSUE TITLE
JSON: プロパティ関数

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1102]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/json/README.md

> 第二引数はreplacer引数とも呼ばれ、変換後のJSONに含まれるプロパティ関数あるいは配列を渡せます。
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/basic/json/README.md#L97 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/basic/json/README.md#L97>

@lacolaco  これちょっと意味がわからなかったけど、

第二引数はreplacer引数とも呼ばれ、 関数あるいは変換後のJSONに含まれるプロパティ名の配列を渡せます。

の間違い?

**Comment by lacolaco** [comment]
なにか間が抜けてますね。書くとしたら

```
JSON.stringifyメソッドにはオプショナルな引数が2つあります。 第二引数はreplacer引数とも呼ばれ、関数あるいは配列を渡せます。 関数を渡した場合は引数にプロパティのキーと値が渡され、その返り値によって文字列に変換される際の挙動をコントロールできます。 次の例は値がnullであるプロパティを除外してJSONに変換するreplacer引数の例です。 replacer引数の関数でundefinedが返されたプロパティは、変換後のJSONに含まれなくなります。
```

で良さそうですね。

**Comment by lacolaco** [comment]
これTeX直接直しに行けばいいんですっけ？

**Comment by azu** [comment]
そうですね。
https://github.com/asciidwango/js-primer/blob/publish1/TeX/chap24.tex#L90
と
Markdownの方

のダブルコミット(Markdownで確認してからTeXにコピペとかかな)

**Comment by kahei** [comment]
TeXの修正、よろしくお願いいたします。

**Comment by lacolaco** [comment]
@kahei TeXの修正マージ済みです！
