### ISSUE TITLE
HTTP通信: HTTPリクエストが作成され

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1105]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/ajaxapp/http/README.md

> fetch`メソッドにURLを与えることで、HTTPリクエストが作成され、サーバーとのHTTP通信を開始します。
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/use-case/ajaxapp/http/README.md#L19 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/use-case/ajaxapp/http/README.md#L19>

HTTPリクエストが作成され ってのが少し気になった。
なにを表してるのかハッキリしない感じ。

**Comment by azu** [comment]
@lacolaco これどうするのがいいかなー
意味は伝わるとでいい案がなければそのままでいい気はするけど

**Comment by lacolaco** [comment]
たしかにちょっと違和感はあるけど良い案思いつかないですね…

**Comment by azu** [comment]
これは一旦このままで。案が思いついたら直す
