### ISSUE TITLE
ユニットテストを記述する: testだとencodingオプションじゃなくなっている

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1107]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/nodecli/refactor-and-unittest/README.md

本文だと

```js
fs.readFile(path, { encoding: "utf-8" })
```

テストだと

```js
fs.readFileSync(path, "utf-8")
```

とencodingの指定方法が急に変わっていた

**Comment by azu** [comment]
そもそもfs.readFileSyncの解説がないからか

**Comment by azu** [comment]
@lacolaco これは `{ encoding: "utf-8" }`に揃える?

**Comment by lacolaco** [comment]
本文側の encoding: utf8に揃えます

**Comment by lacolaco** [comment]
修正done
