### ISSUE TITLE
2020-04-01: MTGアジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1116]
2020-04-01のミーティングアジェンダ置き場

**Comment by azu** [comment]
- [ ] スケジュール
- [ ] ウェブサイトからの導線周り
- [ ] 献本

**Comment by azu** [comment]
残りはこれどうするかかなー commanderだけちょっと悩んでる 5が出たばかりなので。

* [ユニットテストを記述する: mocha 7へアップデート · Issue #1106 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/1106)
* [nodecli: commander@5の変更を確認する · Issue #1111 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/1111)
* [nodecli: marked@0.8へアップデート · Issue #1112 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/1112)

cc @lacolaco

**Comment by lacolaco** [comment]
コードがそのまま動くなら全部最新にあげてしまっていいかなあと思います。

**Comment by azu** [comment]
- [ ] core-jsどうするか #1089

**Comment by azu** [comment]
---

ここから

**Comment by azu** [comment]
core-jsは一旦そのままで。
polyfillとしてゆうめいで使われてる事実は変わらないし、本文で使っているわけでもないため

**Comment by azu** [comment]
ライブラリのアップデートはマージする
