### ISSUE TITLE
オブジェクトリテラルのキーの書き方について

### ISSUE THREAD

**Issue by s-myk** [asciidwango/js-primer#1161]
## 該当ページ

- [ データ型とリテラル > オブジェクトリテラル](https://jsprimer.net/basic/data-type/#object)

## リクエスト/提案内容

上の例では、keyはダブルクォーテーションで囲まれていませんが、
```
const obj = {
    key: "value"
};
```
下の例では、keyはダブルクォーテーションで囲まれています。
```
const obj = {
    "key": "value"
};
```

初学者の混乱に繋がる(誤植に見える)と思いますので、両方ともダブルクォーテーションで囲まれるようにして、その下のドット記法の説明文中で、「キー名のクォーテーションは省略できる("key"もkeyも同じ意味になる)が、数字から始まるキー名の場合はクォーテーションで囲む必要がある」といった説明を行ったほうが分かりやすくなると思います。

## 期待する結果

あくまでも一例ですが、文章だけだと分かりにくいため、以下のような形で説明しておけば、他のコードを読む時の参考になるのではないかと思いました。

---
以下の2つは同じ意味になることをおぼえておいてください。
```
const obj = {
    "key": "value"
};
```
```
const obj = {
    key: "value"
};
```
---
(生まれて初めてのIssueのため、書き方について全く自信がありません。 X-()

**Comment by azu** [comment]
https://jsprimer.net/basic/object/ でその説明をしてるんですよね。
表記ゆれは微妙なので https://jsprimer.net/basic/data-type/#object ではダブルクオートで囲んでおくのが良さそうな気がしますね。

**Comment by s-myk** [comment]
あとで説明が出てくるのであれば、この部分はダブルクオートで囲んでおけば良さそうですね。

それにしても本当に素晴らしい情報源だと思います。
これだけ質の高い情報に無料でアクセスできるなんて幸せです。

今まで、QiitaやN予備校で断片的に得てきた知識が、綺麗に整理されて吸収されていきます。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/1161#issuecomment-625583264 こちらを対応したら改めてCloseしますね。
