### ISSUE TITLE
「除算」に関する説明文中の表現について

### ISSUE THREAD

**Issue by HiroyukiMakita** [asciidwango/js-primer#1165]
## 該当ページ
- [演算子]  https://jsprimer.net/basic/operator/#division-operator

## 質問内容
初心者ながらJavaScriptを学習させていただいております。
詳しく書かれており、とても勉強になります。

該当箇所ですが、
- 除算演算子
2つの数値を除算する演算子
- 剰余演算子
2つの数値のあまりを求める演算子

の2箇所です。
サンプルコードもあり、それぞれ2つの数値を使って、除算したり、あまりを求めたりしていることはよく分かるのですが、「2つの数値を除算」、「2つの数値のあまりを求める」という表現に少し違和感を感じました。

除算という言葉を使う場合、例えば下記のような表現にするとよりわかりやすいのかなと感じました。

- 除算演算子
左オペランドの数値を右オペランドの数値で除算する演算子
- 剰余演算子
左オペランドの数値を右オペランドの数値で除算したあまりを求める演算子

上記の理解で良いか自分としても確認したく、僭越ながらIssueさせていただきます。
よろしくお願いします。

**Comment by azu** [comment]
そうですね。その方が意味が明確な気がします。
MDNはご指摘頂いた形に近い説明になっている感じがしますね。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators

この書籍もそれに合わせたほうがいいですね。(乗算とかとは違ってオペランドの順番に違いがでるのもあるため)

**Comment by HiroyukiMakita** [comment]
ご回答いただきありがとうございます。
確認ができてよかったです。MDNのリンクもありがとうございました

**Comment by azu** [comment]
#1227 で修正されています。
