### ISSUE TITLE
console.log()の記載漏れ(?)について

### ISSUE THREAD

**Issue by s-myk** [asciidwango/js-primer#1166]
## 該当ページ

- クラス > クラスのインスタンスに対してメソッドを定義する  
  [https://jsprimer.net/basic/class/#class-instance-method](https://jsprimer.net/basic/class/#class-instance-method)

## 説明

前後の例文からすると、console.log()が抜けているように思えます。

```diff
 // ベースオブジェクトはundefined
- method(); // => undefined
+ console.log(method()); // => undefined
```

**Comment by azu** [comment]
ありがとうございます。修正しました
