### ISSUE TITLE
input要素の閉じタグについて

### ISSUE THREAD

**Issue by hylian-flute** [asciidwango/js-primer#1167]
## 該当ページ

- [ ] https://jsprimer.net/use-case/todoapp/update-delete/

## 説明

JavaScriptの勉強のために読ませていただきました。
内容ついて一部気になる点がございましたので、issueをさせて頂きたいです。

input要素の閉じタグは禁止されているようです。
> タグの省略 | 開始タグは必須。終了タグを記述してはなりません。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/Input

https://github.com/asciidwango/js-primer/blob/60189fe2654b032da91305d87acfa97d1cd9b24c/source/use-case/todoapp/update-delete/add-checkbox/src/App.js#L21-L23
```diff
-     ? element`<li><input type="checkbox" class="checkbox" checked><s>${item.title}</s></input></li>` 
-     : element`<li><input type="checkbox" class="checkbox">${item.title}</input></li>`; 
+     ? element`<li><input type="checkbox" class="checkbox" checked><s>${item.title}</s></li>` 
+     : element`<li><input type="checkbox" class="checkbox">${item.title}</li>`; 
```

他のページでも同様の問題があるようです。
```console
$ git grep "</input>"
source/use-case/todoapp/final/create-view/src/view/TodoItemView.js:                                </input></li>`
source/use-case/todoapp/final/create-view/src/view/TodoItemView.js:                                </input></li>`;
source/use-case/todoapp/final/final/src/view/TodoItemView.js:                                </input></li>`
source/use-case/todoapp/final/final/src/view/TodoItemView.js:                                </input></li>`;
source/use-case/todoapp/final/more/src/view/TodoItemView.js:                                </input></li>`
source/use-case/todoapp/final/more/src/view/TodoItemView.js:                                </input></li>`;
source/use-case/todoapp/update-delete/README.md:const todoItemElement = element`<li><input type="checkbox" class="checkbox">${item.title}</input></li>`;
source/use-case/todoapp/update-delete/add-checkbox/src/App.js:                    ? element`<li><input type="checkbox" class="checkbox" checked><s>${item.title}</s></input></li>`
source/use-case/todoapp/update-delete/add-checkbox/src/App.js:                    : element`<li><input type="checkbox" class="checkbox">${item.title}</input></li>`;
source/use-case/todoapp/update-delete/delete-feature/src/App.js:                    </input></li>`
source/use-case/todoapp/update-delete/delete-feature/src/App.js:                    </input></li>`;
source/use-case/todoapp/update-delete/update-feature/src/App.js:                    ? element`<li><input type="checkbox" class="checkbox" checked><s>${item.title}</s></input></li>`
source/use-case/todoapp/update-delete/update-feature/src/App.js:                    : element`<li><input type="checkbox" class="checkbox">${item.title}</input></li>`;
```

**Comment by myakura** [comment]
> input要素の閉じタグは禁止されているようです。
>
> >タグの省略 | 開始タグは必須。終了タグを記述してはなりません。

そうですね。書くとバリデーターなどでエラーになるかと思います。

---

ちょっと突っ込んだ話をします。[input要素の定義](https://html.spec.whatwg.org/multipage/input.html#the-input-element)に次のようにあります。

> Content model:
> Nothing.

子に要素やテキストを持てないようになってます。なので、例のように

```html
<input>text</input>
```

と書いても、`text`というテキストノードがinput要素ノードの子になったりはしません。input要素と`text`テキストノードは兄弟関係になります。

で、`</input>`という終了タグですが、これはDOMツリーを作る過程でなくなります。
input要素はパーザにおいて[“special”というカテゴリ](https://html.spec.whatwg.org/multipage/parsing.html#special)に属しています。属する要素や書いた場所によって処理が違うのですが、こと`</input>`の場合は、["in body" insertion mode](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody)というモード内の[“Any other end tag”の3番](
https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody:special-3)で処理されるはずです。

> Otherwise, if <var>node</var> is in the <a>special</a> category, then this is a <a>parse error</a>; ignore the token, and return.

specialのカテゴリだったらパーズエラーになってそいつを無視すると。なのでDOM的には`<input>text`と変わらない感じになります。

ラッキーですが、例としてはあまりよくないので、とりあえず省いたほうがよいかなと。
（labelで囲うとか、さらに適切なマークアップがありそうですが、いったん置いときます）

**Comment by azu** [comment]
#1175 で 閉じタグが削除されたのでcloseします。
ご指摘ありがとうございます。
