### ISSUE TITLE
ループと反復処理の章について

### ISSUE THREAD

**Issue by masakinihirota** [asciidwango/js-primer#1172]
## 該当ページ

- [https://jsprimer.net/basic/loop/] 質問があるページのURLを入れてください

## 質問内容

> 配列のforEachメソッド
> 配列にはforEachメソッドというfor文と同じように反復処理を行うメソッドがあります。
> 
> forEachメソッドでの反復処理は、次のように書けます。

> const array = [1, 2, 3];
> array.forEach(currentValue => {
>     // 配列の要素ごとに呼び出される処理
> });
> 

この下に緑色の実行ボタンがあります。
このソースでは実行ボタンを押しても何も表示されません。
他の似たようなソースでは実行ボタンが付いていないので
ここの実行ボタンは余分なボタンだと思います。

**Comment by dogatana** [comment]
編集して動かせるのは大きなメリットなので、何か動作をするコードを入れてはどうでしょうか。
次のように単に出力するのでも良いと思います。

```js
const array = [1, 2, 3];
array.forEach(currentValue => {
    // 配列の要素ごとに呼び出される処理
    console.log(currentValue);
});
```

**Comment by azu** [comment]
ログを入れるだけでも良さそうですね。

**Comment by kangetsu121** [comment]
こちら #1604  で `{{book.console}}` を削除する方針で対応済みのようです。

https://github.com/asciidwango/js-primer/issues/1172#issuecomment-1030762190
> [{{book.console}}](https://github.com/asciidwango/js-primer/blob/6edc7cda9fedf7d2fc03ce62e2cf7fc97981602a/source/basic/loop/README.md?plain=1#L161) を削除する(ボタンが消える)で良さそうですね。
> 
> すぐ後で同じコンソールログ入れた例があるので、{{book.console}}を削除するほうがいいかもしれないです

もし他に必要な対応がなければクローズしても良いのかもしれません。

**Comment by azu** [comment]
ありがとうございます。クローズしちゃって問題なさそうですね。
