### ISSUE TITLE
Windows10 では build 不可でしょうか

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1173]
## 該当ページ

- [https://github.com/asciidwango/js-primer/blob/master/README.md ]

## 質問内容

RAEDME.md に従い、

```
npm install
npm run build 
```
と進めていますが、build で失敗します。
その時に表示される内容を添付しました。

[message.txt](https://github.com/asciidwango/js-primer/files/4774246/message.txt)

環境は

* Windows 10
* node v12.18.0
* npm 6.14.4

ですが、Windows環境はビルド対象外でしょうか。

**Comment by azu** [comment]
> Template render error: (C:\Git\ebook\js-primer\source\use-case\todoapp\update-delete\README.md) [Line 112, Column 18]
>   expected variable end

GitBookのビルドで何故か失敗していますね。

CIでも試してみましたが、たしかに同じところで落ちてますね。
https://github.com/asciidwango/js-primer/pull/1174/checks?check_run_id=767795453

`npm run build` はウェブサイトのビルドするコマンドなので、特にWindowsでやってなくて確認してなかったので落ちてるだけではありますね。

**Comment by azu** [comment]
おそらく、この `{{` がGitBookの変数参照として解決されて落ちてるような気がしますが、なぜWindowsだけなるのかが謎ですね…

https://github.com/asciidwango/js-primer/blob/b6a24ad79f33733caee4602ce7f9872d587d2cde/source/use-case/todoapp/update-delete/update-feature/src/model/TodoListModel.js#L57

gitbookのpluginなしでは落ちなかったので、 https://github.com/azu/gitbook-plugin-include-codeblock でコードをインライン化したときに `{{` が入ると変数としてレンダリング仕様として失敗してる感じがしますね

**Comment by dogatana** [comment]
早速確認いただき、ありがとうございます。
Windows では何か不都合が発生するということですね。

Gitbook は使ったことがなかったので、gitbook-cli をインストールして gitbook build としても同じエラーが発生しました。

```
Template render error: 
expected variable end
```

と出ているので、テンプレートのレンダリングで変数展開しようとして失敗しているように見えます。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/1174/commits/93a858aa7861579276bebbc0c5f45be1c66d2916
JSDocを消してみたところはビルドはできたので、やっぱりこの部分が変数として認識されるのが原因のようですが、
`{% raw %}` で囲まれたエリアは変数として無視されるはずだけど無視されない現象がWindowsだけ発生するみたいですね。
nunjucksかGitBookのバグを踏んでいる気がしています。

**Comment by yumetodo** [comment]
`* @param {{ id:number, completed: boolean }} `って`* @param { { id:number, completed: boolean } } `としたらだめなんでしたっけ？

**Comment by dogatana** [comment]
```
* @param { { id:number, completed: boolean } } 
```
これでもエラーになりますね。
表示される行番号は異なりますが、桁位置は同じで、```expected variable end``` が出ます。

wsl2 の ubuntu 20.04LTS では ```npm install``` でエラーになります。
rename がエラーのようで、これは wsl2 に起因するように思えます。

vagrant の ubuntu 18.04 では gitbook サーバを上げるところまで行きますが、目次（サイドバー）のリンクを触っていると gitbook が落ちました。。

素の Windows 10でbuild は失敗しますが、_book の下の各フォルダに index.html が生成されているので、_book に移動して
```
python -m http.server 4000 --bind 127.0.0.1
```
としてやって一応見られるようになりました。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/1174
でGitBookをforkしたものに差し替えてみたら、Windowsでもビルドが通るようになりました。
GitBookが依存してたNunjuksのバージョンが古かったのが主な原因だったのかもしれないです。

**Comment by azu** [comment]
[GitHon](https://github.com/githon/githon)を作ってこちらに移行したので、WIndowsのビルドも通るようになったと思います。

**Comment by dogatana** [comment]
ありがとうございました。
無事ビルドもでき、プレビューサーバも安定して動作するようになりました。
