### ISSUE TITLE
GitBook → GitHon → HonKit

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1176]
READMEとかで `GitBook` という単語があると思うので、 [HonKit](https://github.com/honkit/honkit) に書き換える。

## TODO

- [ ] README
- [ ] CONTRIBUTING.md
- [ ] 他にあったら書き換える
- [x] https://github.com/asciidwango/js-primer/blob/edf31e1766671885025c52e1224d84e10259e19a/source/manifest.json この辺のパスとかは特に書き換えなくても問題ない(HonKitで互換性があるため)

**Comment by DuGlaser** [comment]
@azu こちらやらせていただいてもよろしいでしょうか？

**Comment by azu** [comment]
@DuGlaser OKです！
