### ISSUE TITLE
表記統一: -> を → に変更する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1192]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/todoapp/final/README.md

<img width="873" alt="image" src="https://user-images.githubusercontent.com/19714/85941087-a20aca00-b95b-11ea-9d81-63242fb7dfab.png">

`->` よりも `→` の方が適切な気がするため。

**Comment by azu** [comment]
他に残ってなかればクローズ

**Comment by azu** [comment]
地味に `->` を使ってる箇所は他にもありそうだった。
(GitHubの検索だとかからない…)

**Comment by gogogodx** [comment]
私のほうで `->` を使ってる箇所を探したところ、次の4か所が見つかりました。
修正しようと思うのですが、いかがでしょうか。
<br>
- URL: https://github.com/asciidwango/js-primer/blob/master/source/basic/async/README.md

![image](https://user-images.githubusercontent.com/36806951/85944356-11d77f80-b971-11ea-82b9-251d3d005ce0.png)


- URL: https://github.com/asciidwango/js-primer/blob/master/source/basic/function-scope/README.md

![image](https://user-images.githubusercontent.com/36806951/85944340-fff5dc80-b970-11ea-9cec-7fa7be3c7cc9.png)


- URL: https://github.com/asciidwango/js-primer/blob/master/source/basic/implicit-coercion/README.md
    - 次と同じようなものが4か所存在

![image](https://user-images.githubusercontent.com/36806951/85944164-b3f66800-b96f-11ea-95c0-e2c449ba7c06.png)


- URL: https://github.com/asciidwango/js-primer/blob/master/source/basic/prototype-object/README.md

![image](https://user-images.githubusercontent.com/36806951/85944334-e94f8580-b970-11ea-83bf-42ce156d174c.png)

**Comment by azu** [comment]
全部 → に置き換えて問題ない気がしますね。

**Comment by gogogodx** [comment]
ご回答ありがとうございます。
対応いたします。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/prh.yml#L596
後 prhの辞書の追加しちゃってもいい気がしますね。
文中で `->` と書く場合は多分ないと思われるので、今後統一していくためにも。

**Comment by gogogodx** [comment]
ご教授ありがとうございます。
併せて対応させていただきます。

**Comment by azu** [comment]
すべて書き換わったはずなのでクローズします。
@gogogodx ありがとうございました！
