### ISSUE TITLE
テンプレートリテラルの箇所のシンタックスがおかしい

### ISSUE THREAD

**Issue by isdh** [asciidwango/js-primer#1199]
## 該当ページ
https://jsprimer.net/basic/string/#what-is-string

## 説明
シンタックスがおかしい。
コードの説明の部分だけにコードシンタックスが適用されるべき。
![js-primer-string](https://user-images.githubusercontent.com/11797443/86192880-926ec980-bb85-11ea-8c79-f45cf64ad211.png)

**Comment by azu** [comment]
ご報告ありがとうございます！

#1200 で修正しました。
