### ISSUE TITLE
encodeURIComponent() での処理ダブり

### ISSUE THREAD

**Issue by Yoshida-aisamurai** [asciidwango/js-primer#1207]
## 該当ページ
[Promiseを活用する-ユーザーIDを変更できるようにする]( https://jsprimer.net/use-case/ajaxapp/promise/#changeable-userid)
## 説明

最終的な「index.js」にて
```
function getUserId() {
    const value = document.getElementById("userId").value;
    return encodeURIComponent(value);
}
```
と
```
function fetchUserInfo(userId) {
    return fetch(`https://api.github.com/users/${encodeURIComponent(userId)}`)
        .then(response => {
            if (!response.ok) {
                return Promise.reject(new Error(`${response.status}: ${response.statusText}`));
            } else {
                return response.json();
            }
        });
}
```

の両方でencodeURIComponent() 使って同じ値を処理しているようです。

---
この場を借りて作者様へ
この記事も含め、jsprimerにはjava scriptの面白さを教えてもらいました。作成、公開に深く感謝します。

**Comment by azu** [comment]
ご報告ありがとうございます。


`getUserId`関数がencodeしたIDを返すのがちょっと変な気がしますね。
`getUserId`から`encodeURIComponent`を取り除くのがいい気がしますね。
