### ISSUE TITLE
[Website]BugReportボタンを分かりやすくする

### ISSUE THREAD

**Issue by ryo-gk** [asciidwango/js-primer#1209]
## はじめに
JavaScriptを体系的に学びなおそうと思い、JSPrimerのウェブサイト版を見つけました。
全体を通して説明が分かりやすく、非常に参考になっています。
読んでいる中で気になった点があったので、issueを上げさせていただきます。

## 該当ページ
JavaScript Primer のウェブサイト版
URL: https://jsprimer.net/

## リクエスト/提案内容
改善提案をしたいのは、ウェブサイト版画面右下の「BugReport」ボタンについてで、
具体的には、
* 「BugReport」ボタンがこの位置にあるのに気付きにくい点
* 「BugReport」と英語で書かれている点

の２つです。
1つ目に関しては、このボタンだけ特別にスタイルがあてられていなくて、かつボタンの大きさも小さく画面の端によっているので、少し気付きにくいかもしれないと思いました。

2つ目に関しては、書籍が日本語なので、
このボタンも「問題を報告する」や「バグレポート」などの日本語の方が、分かりやすいかなと思いました。

## 期待する結果
1つ目は「ボタンがあること」が分かりやすい状態、
2つ目は「日本語で書かれている」状態が期待する結果です。

[参考イメージ」
![image](https://user-images.githubusercontent.com/62658104/87321666-7e54a000-c567-11ea-9514-714e2a888eca.png)

以上です。よろしくお願いします。

**Comment by azu** [comment]
https://github.com/azu/gitbook-plugin-github-issue-feedback/blob/9e6625ac4e28a5d0ef0d3e34a45fad6076cff61f/src/plugin.js#L65
プラグイン側でラベルをハードコードしちゃってるので、まずはオプションで受け取れるようにしないといけないですね。

**Comment by ryo-gk** [comment]
プラグインだったんですね。（便利😃）
プラグイン側のコード見てみます

**Comment by ryo-gk** [comment]
プラグインの方にPR出しましたので、お時間あるときにご確認ください。
https://github.com/azu/gitbook-plugin-github-issue-feedback/pull/11

**Comment by azu** [comment]
ありがとうございます。
https://github.com/azu/gitbook-plugin-github-issue-feedback/releases/tag/v1.4.0 で `label` オプションの対応をリリースしました

**Comment by ryo-gk** [comment]
プラグインのバージョンアップと`label`オプションの設定をしたPRを出しましたので、
こちら(https://github.com/asciidwango/js-primer/pull/1210) の確認もお願いします。

**Comment by ryo-gk** [comment]
PRの承認ありがとうございました！


> 「BugReport」ボタンがこの位置にあるのに気付きにくい点

こちらについても、できればボタンにスタイルを当てて修正を入れたいと思ってるのですが、
スタイルは当てずにこのままのボタンの方がよいなどあったりしますか？

修正してもよければ、
・シンプルに、js-primer側でボタンのクラスを指定して、スタイルを当てる
or
・github-issue-feedback側にスタイルを当てるオプションを追加した上で、オプション経由でスタイルを当てる
　※https://github.com/aleung/gitbook-plugin-page-toc みたいな形になるかなと。

のどちらかになると思うのですが、どちらにするのがよいか意見もらえたら嬉しいです。

**Comment by azu** [comment]
`.gitbook-plugin-github-issue-feedback` に対してスタイルを当てるで問題ないと思います。

https://github.com/asciidwango/js-primer/blob/master/source/_layouts/website/page.html
にスタイルを定義する形で良さそうな気がします。

**Comment by ryo-gk** [comment]
早速ですが、PR出させていただきました。
https://github.com/asciidwango/js-primer/pull/1213
お時間ある際、ご確認お願いします。

**Comment by azu** [comment]
#1213 をマージしました。
対応ありがとうございます！

**Comment by ryo-gk** [comment]
期待する結果となりましたので、こちらのissueを閉じさせていただきます。
ありがとうございました！
