### ISSUE TITLE
String

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#121]
#17 基本文法

Stringオブジェクト

**Comment by azu** [comment]
- UTF-16
- indexOf
- includes
- match 正規表現

**Comment by azu** [comment]
[What every JavaScript developer should know about Unicode](https://rainsoft.io/what-every-javascript-developer-should-know-about-unicode/ "What every JavaScript developer should know about Unicode")
詳しくて良い

**Comment by yumetodo** [comment]
#106 はどうなりますかね？

**Comment by azu** [comment]
Tagged Templateの課題で、safe property access とか結構面白いかもと思った(処理を限定させれば結構シンプルに書けるかも)
https://github.com/azu/azu/issues/78

**Comment by azu** [comment]
[「文字数」ってなぁに？〜String, NSString, Unicodeの基本〜 // Speaker Deck](https://speakerdeck.com/takasek/wen-zi-shu-tutenaani-string-nsstring-unicodefalseji-ben "「文字数」ってなぁに？〜String, NSString, Unicodeの基本〜 // Speaker Deck")

**Comment by azu** [comment]
`"𠮟る".length; //  => 3`
叱ると𠮟るがあるのか

**Comment by yumetodo** [comment]
[FAQ - Characters and Combining Marks#How are characters counted when measuring the length or position of a character in a string?](http://unicode.org/faq/char_combmark.html#7)

Unicode公式の文字の定義計4パターン

**Comment by azu** [comment]
絵文字のlength [Emoji.prototype.length — a tale of characters in Unicode - Contentful](https://www.contentful.com/blog/2016/12/06/unicode-javascript-and-the-emoji-family/ "Emoji.prototype.length — a tale of characters in Unicode - Contentful")

**Comment by azu** [comment]
テンプレートリテラル ここに含めると微妙に関数が先にあって欲しいみたいなことがおきるんだな。

概念をまとめると

- テンプレート文字列
  - テンプレートリテラル
  - タグ付きテンプレートリテラル

という関係になるはず。
表記も統一しないと。

@laco0416 ↑の表記に統一かな? (個人的にはTemplate literalとかそのまま使うの好きだけど、中途半端になりそうだし)


- [テンプレート文字列 - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/template_strings "テンプレート文字列 - JavaScript | MDN")
  - MDNはやや半端なんだな

**Comment by azu** [comment]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/slice
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/substring

String#slice と String#substring ってどういう理由で２つあるんだろ?
JavaScriptの仕様的にどちらも破壊的じゃないし、同等のことは表現できるだろうし。
この使い分けってあるのかな?
(説明としてどちら(とも)を出すのかが迷う感じ)

**Comment by azu** [comment]
SubstrとAnnex Bの話
https://esdiscuss.org/topic/moving-string-prototype-substr-to-normative-part-of-the-spec

**Comment by azu** [comment]
sliceとsubstringの違いを出すには `-` をつかうケースで、典型的なのは0桁埋めだったけど、
今ならString#padStartで解決できてしまう ということに気づいてしまった。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/source/OUTLINE.md#string
この章のメインテーマとしては、目的の文字列を組み立てる方法を学ぶという所に集約しそう。
そのために文字とは何かとか文字列操作の方法とかを見ていく感じ。
(具体的に目的の文字列としていい感じのものがまだないけど。タグ付きテンプレートを説明しようと思ったら思った以上に難しかった)

**Comment by azu** [comment]
タグ付きテンプレートの典型的なユースケースはやっぱりHTMLエスケープなのかな。
Ajaxのところでも出てくるので、ここでは仕組みを上手く解説できるといいのだけど。
題材はHTMLエスケープ以外だとなんかいい感じのあるのかな

- [テンプレート文字列 - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/template_strings)
- [JavaScript の テンプレートリテラル を極める！ - Qiita](http://qiita.com/kura07/items/c9fa858870ad56dfec12)
- [Template Literals are Strictly Better Strings](https://ponyfoo.com/articles/template-literals-strictly-better-strings)
- [New string features in ECMAScript 6](http://www.2ality.com/2015/01/es6-strings.html)
- [Getting Literal With ES6 Template Strings  |  Web  |  Google Developers](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings)
- [8. Template literals](http://exploringjs.com/es6/ch_template-literals.html)

**Comment by azu** [comment]
Unicode周り 詳しくはMathiasさん参照みたいな感じになるかなー
combining marksあたりになると、物理的に印刷が正しくできるのか不安になるレベル。
(ECMAScriptの範疇じゃなくてUnicodeの話になってしまうし)

- [26. Unicode in ES6](http://exploringjs.com/es6/ch_unicode.html)
- [JavaScript has a Unicode problem · Mathias Bynens](https://mathiasbynens.be/notes/javascript-unicode)

多くのケースでは直にこの問題を扱わないで、事前に正規化を書けて扱いやすくしたものを扱うはずなので、普通にプログラミングする範囲では知りたいときに調べる感じになるものだと思う。

- [Regexp.ja · neologd/mecab-ipadic-neologd Wiki](https://github.com/neologd/mecab-ipadic-neologd/wiki/Regexp.ja "Regexp.ja · neologd/mecab-ipadic-neologd Wiki")

combining marksはString#normalizeで正規化できないので、正しく説明するのが単純に難しい感じ。

code unit, code pointあたりは、JavaScriptのAPIとして扱う方法が存在するので、APIを使いつつ説明できる範囲にしておくのがちょうどいい感じかなと思った。

**Comment by yumetodo** [comment]
いや、Unicodeを真面目に考えれば、正規化なんて甘えで、ひとつのコードポイントで一文字を表そうとするのが傲慢ということでは・・・。**たまたま**等価な(等価の定義がまた面倒)コードポイントひとつに変換できる場合の変換が正規化なのであって。
もちろんECMAScriptの範疇じゃなくなるので、正規化は例えば検索(比較)可能性の向上のために等価な文字を同じコードポイントで表すように変換するためにあるのであって、combining characterを1codepointで表すためのものではない、と言及するに留めるしかないと思いますが。

>combining marksあたりになると、物理的に印刷が正しくできるのか不安になるレベル。

あ・・・

**Comment by azu** [comment]
いつも忘れるのでメモ。

```js
var str = "x\uD83D\uDE80y";
console.log("\\u" + str.codePointAt(0).toString(16));
console.log("\\u" + str.codePointAt(1).toString(16));
console.log("\\u" + str.codePointAt(3).toString(16));
// code unit
console.log("\\u" + str.charCodeAt(0).toString(16));
console.log("\\u" + str.charCodeAt(1).toString(16));
console.log("\\u" + str.charCodeAt(2).toString(16));
console.log("\\u" + str.charCodeAt(3).toString(16));
```

via http://www.2ality.com/2015/01/es6-strings.html

**Comment by azu** [comment]
StringとRegExp 改めて仕様読んでてたけど、関係がもっと深いな。
String#methodはRegExp#[SymbolMethod]として使うことができるのか

https://tc39.github.io/ecma262/#sec-properties-of-the-regexp-prototype-object

```js
"ab".split(/a*?/)
/a*?/[Symbol.split]("ab")
```
みたいにかける

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/183 これを書き直すといいのかも。
Symbolで対となる表現が存在するという話を書くだけ(実際には使わない)
関係性の深さを意識として置いておきたい。後将来的にSymbolの活用例として

**Comment by azu** [comment]
String#split

- https://tc39.github.io/ecma262/#sec-string.prototype.split
- "".split("") の場合は  code unit 要素ごとに分割される

> The value of separator may be an empty String. In this case, separator does not match the empty substring at the beginning or end of the input String, nor does it match the empty substring at the end of the previous separator match. If separator is the empty String, the String is split up into individual code unit elements; the length of the result array equals the length of the String, and each substring contains one code unit.

`"文字列".split("").join("")` は絵文字がきた段階で破綻する。
Array.fromや`...`でましになるけど、結合文字まで考えるとそこは自前でやる必要があるやつ。

- [mathiasbynens/esrever: A Unicode-aware string reverser written in JavaScript.](https://github.com/mathiasbynens/esrever)
- [JavaScript has a Unicode problem · Mathias Bynens](https://mathiasbynens.be/notes/javascript-unicode)

**Comment by azu** [comment]
Java @ プログラマのための文字コード技術入門
![mu pdf viewer 2017-02-20 20-23-53](https://cloud.githubusercontent.com/assets/19714/23123156/9e4be5fa-f7aa-11e6-87e1-c18d064f87b7.png)

**Comment by azu** [comment]
文字数(正確にはcode point) みたいな言い回しするのが難しさを出してる感じがする

![mu pdf viewer 2017-02-20 20-25-51](https://cloud.githubusercontent.com/assets/19714/23123192/ca1e4eca-f7aa-11e6-9dd6-f1636bddc7be.png)

**Comment by azu** [comment]
stringの比較は === ぐらいかな?
> < >= <= 一応書くけど、sortとセット以外で使わない感じがするな。
この辺の仕様を見て、そのアルゴリズムをJavaScriptで書いてみるのが分かりやすいのかな?

```
"100" > "20" ; // false
```

**Comment by azu** [comment]
[String.prototype.localeCompare() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare "String.prototype.localeCompare() - JavaScript | MDN")
[Intl.Collator.prototype.compare - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator/compare "Intl.Collator.prototype.compare - JavaScript | MDN")

i18nのcompareもそういえば今なら使えるのか。
i18n API自体がこなれてない感じなので、これを含めるか難しいな。(微妙に使えない環境あるし)

**Comment by azu** [comment]
文字列比較の  `===` のアルゴリズム

> If x and y are exactly the same sequence of code units (same length and same code units at corresponding indices), return true; otherwise, return false.
> -- https://tc39.github.io/ecma262/#sec-samevaluenonnumber

なので、code unitが同じ長さで同じ並びになっているかというもの

**Comment by azu** [comment]
C#とかSwiftでのUnicode周りの話

[プログラミング言語における文字コードの話 | ++C++; // 未確認飛行 C ブログ](http://ufcpp.net/blog/2016/9/unicode/ "プログラミング言語における文字コードの話 | ++C++; // 未確認飛行 C ブログ")

**Comment by azu** [comment]
http://qiita.com/teyosh/items/b126f21a16b795885067#intlcollator
言語によって文字列の比較結果は異なるため、i18nの機能を使ってL10Nをしないと求める結果は得ることができない。

**Comment by azu** [comment]
配列の場合は特定の要素を探すということをするが、文字列から特定の文字1つを探すということはあまりしない。

代わりに特定の文字の並びを探すということを行うため、その文字集合へのマッチ方法が重視されることが多い。そこで役立つのが文字集合を特殊文字として表現できる正規表現。

StringとRegExpは内部的に同じ処理を共有しているため、別のオブジェクトではあるがとても密接な存在である。

**Comment by azu** [comment]
[Jonathan New | "💩".length === 2](http://blog.jonnew.com/posts/poo-dot-length-equals-two "Jonathan New | &#34;💩&#34;.length === 2")

❤️ のlengthの例

**Comment by azu** [comment]
- [sindresorhus/strip-indent: Strip leading whitespace from each line in a string](https://github.com/sindresorhus/strip-indent "sindresorhus/strip-indent: Strip leading whitespace from each line in a string")
- https://github.com/declandewet/common-tags#stripindent

カスタムタグテンプレート インデント消すやつとか、正規表現も混ざって面白いかも

```js
stripIndent`
 class YourStore extends Store {
    getState(){
      return {
          yourStore: this.state
      };
    }
 }
`;
```

**Comment by azu** [comment]
i18nタグがいいかも？
数値の複数形とか

**Comment by azu** [comment]
文字単位の分割i18n APIの分かち書きでできるのかなー。
結合文字とかもいい感じに分割してくれるのかな

- [tc39/proposal-intl-segmenter: Unicode text segmentation for ECMAScript](https://github.com/tc39/proposal-intl-segmenter "tc39/proposal-intl-segmenter: Unicode text segmentation for ECMAScript")

**Comment by azu** [comment]
[javascript - JavaScriptで絵文字の正確な長さを取得する - スタック・オーバーフロー](http://ja.stackoverflow.com/questions/5918/javascript%e3%81%a7%e7%b5%b5%e6%96%87%e5%ad%97%e3%81%ae%e6%ad%a3%e7%a2%ba%e3%81%aa%e9%95%b7%e3%81%95%e3%82%92%e5%8f%96%e5%be%97%e3%81%99%e3%82%8b "javascript - JavaScriptで絵文字の正確な長さを取得する - スタック・オーバーフロー")
https://github.com/tc39/proposal-intl-segmenter に近いものとしてV8はそういうIteratorにするやつが生えてるのか

**Comment by azu** [comment]
[Regular Expressions in a post-ES6 world](https://ponyfoo.com/articles/regular-expressions-post-es6 "Regular Expressions in a post-ES6 world")
named captureを踏まえて、execとかは単純な配列じゃないということを明記しておいたほうがいいのかも

**Comment by azu** [comment]
#225 構造的な文字列 = ドメイン固有言語的な表現にしたほうがいいかも。
URL文字列もドメイン固有言語といえるのかな。

**Comment by azu** [comment]
テンプレートリテラル周りの用語整理

| Name                                     | Code                       |
| ---------------------------------------- | -------------------------- |
| タグ関数([tag function](https://tc39.github.io/ecma262/#sec-string.raw)) | **String.raw**\`template\` |
| タグ付きテンプレート([Tagged Templates](https://tc39.github.io/ecma262/#sec-tagged-templates)) | **String.raw\`template\`** |
| テンプレートリテラル([Template Literals](https://tc39.github.io/ecma262/#sec-template-literals)) | **\`template\`**           |
| テンプレート文字列([TemplateStrings](https://tc39.github.io/ecma262/#sec-static-semantics-templatestrings)) | \`**template**\`           |

[8. Template literals](http://exploringjs.com/es6/ch_template-literals.html#sec_faq-template-literals "8. Template literals") 過去の仕様だとTemplte Stringが違う名前だったりしてややこしいけど、これであってるのかな?

**Comment by azu** [comment]
[zeeshanu/learn-regex: Learn regex the easy way](https://github.com/zeeshanu/learn-regex "zeeshanu/learn-regex: Learn regex the easy way")

正規表現について簡単にまとまっててよさそう。
リンクを追加するかなー
