### ISSUE TITLE
実行時エラー TypeError の説明

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1218]
## 該当ページ

https://jsprimer.net/basic/read-eval-print/

## 説明

> 「APIに渡す値の問題から起きる ```TypeError```」

ですが、広くは

>「APIに渡す値のデータ型の問題から起きる ```TypeError```」

としてはいかがでしょうか。

**Comment by azu** [comment]
よさそうです。
修正するPR出していただいても大丈夫です。

**Comment by dogatana** [comment]
細かなものはPRが良いと書いてありましたね 。。
私には敷居が高いですが、トライしてみます。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/edit/master/source/basic/read-eval-print/README.md
から直接ブラウザで内容を変更できるので、変更した内容をコミットすると自動的にPull Requestを出す画面が出てくるので、Pull Requestを作成すればOKです。

次のコメントが参考になるかもしれません。

https://github.com/asciidwango/js-primer/issues/983#issuecomment-545273628

**Comment by dogatana** [comment]
ご教示ありがとうございます。
作成してみましたが、これで良ければ、Issueに挙げたほかの2件も同じようにPRを作成したいと思います。

**Comment by azu** [comment]
PRありがとうございます。特に問題ないと思います。
