### ISSUE TITLE
実行時エラーの修正の説明文で、「行数」とある個所について

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1219]
## 該当ページ

https://jsprimer.net/basic/read-eval-print/

## 説明

> 実行時エラーが発生した際には、発生したエラーの行数の周辺をよく見ることや

の「行数」は数になるので、「行」もしくは「位置」としてはいかがでしょうか。

> 実行時エラーが発生した際には、エラーが発生した行の周辺をよく見ることや

> 実行時エラーが発生した際には、エラーが発生した位置の周辺をよく見ることや

**Comment by azu** [comment]
>   実行時エラーが発生した際には、エラーが発生した行の周辺をよく見ることや

こっちが良さそうですね！

**Comment by azu** [comment]
closed by #1222
