### ISSUE TITLE
オブジェクトリテラルのプロパティ名の書式

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1225]
## 該当ページ

 [データ型とリテラル](https://jsprimer.net/basic/data-type/) 

## 提案内容

オブジェクトリテラルで識別子として使用可能なプロパティ名を使用する場合、文字列リテラルではなく、識別子のままとすることが多いと思います。

ついては

> キー名には、文字列またはSymbolを指定し、

を

> キー名には、識別子、文字列リテラル、数値リテラル、またはSymbolを指定し、

に変更してはどうでしょうか。

これに合わせてサンプルも次のように修正します（2か所）。

```js
const obj = {
    key: "value"
};
```

その後にある、"123" はコメントに「文字列」とあるのでそのままで良いと思います。

この修正は、[A.2 Expressions](https://tc39.es/ecma262/#sec-lexical-grammar) の定義に対応するものです。

```
 LiteralPropertyName:
        IdentifierName
        StringLiteral
        NumericLiteral
```

## 期待する結果

広く使用されている書式に合わせたサンプルコードとなっていることが期待する結果です。

**Comment by azu** [comment]
> キー名には、識別子、文字列リテラル、数値リテラル、またはSymbolを指定し、

指定できるだけであって、数値リテラルは推奨はできないですね。
暗黙的な型変換が行われます。
https://jsprimer.net/basic/object/#object-property-is-to-string

識別子の意味合いが文章で異なる気がするので、余計な混乱を作っている気がします。

```js
const obj = { key }
```

とも解釈できる気がしますが、これは別表現になりますね。

> オブジェクトリテラルのプロパティ名（キー）はクォート（"や'）を省略できます。 そのため、次のように書いても同じです。

としているので、次の`key`が識別子として認識できるかは微妙な気がします。
言われてそう認識する気がします。

```js
const obj = {
    key: "value"
};
```

#1161 キー名の基本をダブルクオートに統一しているのは、余計な混乱を避けるためですね。(JSONとの兼ね合いもあります)
また、すべての構文を網羅することは[目的ではない](https://jsprimer.net/intro/#do-not)のもありますね。

**Comment by dogatana** [comment]
おっしゃるとおり、識別子というのは固い表現です、ここでは識別子そのものではありませんね。
数値は指定できますが、key として取り出すと文字列になっているので、推奨されないのも理解で、文章は元の方が分かりやすいです。

> オブジェクトリテラルのプロパティ名（キー）はクォート（"や'）を省略できます。 そのため、次のように書いても同じです。

最初から順に読んでいるので、この説明までたどりついていないのでした。。

"" ありは Issue https://github.com/asciidwango/js-primer/issues/1161  で決定されたんですね。

"" のあるなしは確かに混乱しますが、私は逆に「なぜ "" があるのか」と混乱しました。
（JSON そのものは 他の言語で使用していたので、"" が必要なのは理解しています）

私見ですが、空白を含まないキー名は "" で囲まない方が自然（＝普段の実装で使用する書式）であれば、ここでは "" なしとして、オブジェクトの章で詳細を説明する、元の説明の流れの方が良いように思います。

実務では使用していないので、これが自然かどうか、あるいは コーディングルールで必ず”” で囲む書式で統一するケースがあるかどうかは分かりませんが、次の書籍では "" なしでの説明が先に来ており、"" なしが自然だと思っていた次第です。

* 独習 JavaScript 第2版, 翔泳社
* 初めての JavaScript 第3版, オライリー

意図的に記載されているということなので、Close とします。
