### ISSUE TITLE
introduction: JavaScriptとECMAScriptの区別について

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#123]
> - [ ] JavaScriptとECMAScriptについて明確な区別を付けずに記述しているという点について書く 
> - https://asciidwango.github.io/js-primer/basic/introduction/

色々な実行環境があるということは既に示している。
JavaScriptは事実上ECMAScriptのスーパーセットのような扱いであるため、
本書ではJavaScriptといった場合にECMAScriptを含んでいるということを明記する。

似た記述を見つけた

> 事実上、JavaScript処理系のほとんどはECMAScriptのスーパーセットです。このため移植性を考慮したければECMAScript準拠の機能だけを使えばいいことになります
> -- [パーフェクトJavaScript](https://gihyo.jp/book/2011/978-4-7741-4813-7)

**Comment by azu** [comment]
#367 と話を統合するのが良いのかもなー
そうして結構前の方に持ってくるとか

**Comment by yumetodo** [comment]
@azu それだと冒頭が冗長にならないですかね・・・

**Comment by azu** [comment]
@yumetodo 統合しないことにしました。
https://github.com/asciidwango/js-primer/pull/427/files#diff-9082166a89a3821ae698c3167d339fcbR36
