### ISSUE TITLE
オブジェクト: shallow copyについて

### ISSUE THREAD

**Issue by satoshi-kimura** [asciidwango/js-primer#1232]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/object/README.md

shallow copyの説明で、

// `nest`オブジェクトは複製されていない
とコメントがありますが、
// `nest`オブジェクトは同じオブジェクト
という方が分かりやすいと思いました。

さらに、そのオブジェクトを変更して、両方に変更があることを示した方が良いと思います。

**Comment by azu** [comment]
> そのプロパティの値がオブジェクトである場合に、ネストした先のオブジェクトまでも複製するわけではありません。

コードのすぐ上の文で複製されないことは説明しているので、コード中のコメントは `// nestオブジェクトは同じオブジェクト` の方がわかりやすそうですね。
