### ISSUE TITLE
第二部ユースケース：CLIアプリのユニットテストにおける不具合報告

### ISSUE THREAD

**Issue by sasahara-study** [asciidwango/js-primer#1233]
## 該当ページ

- [ ] https://jsprimer.net/use-case/nodecli/refactor-and-unittest/

## 説明

* 現状のテストコードではユニットテストが成功しません

* Markdown文字列をHTMLに変換する過程で末尾に期待値にはない余計な改行コードがはいってしまっているため、ユニットテストが成功しません
（変換過程でsample.mdの末尾に余計な改行コードが追加され、expected.html、expected-gfm.htmlと一致せずユニットテストが成功しない）

* 改善案としては以下の3点があげられます
①md2html-test.jsにsample.mdの末尾に追加された余計な改行コードを削除するコードを追加する
②md2html.jsにMarkdownの変換処理されたファイルに追加された改行コードを削除するコードを追加する
③expected.html、expected-gfm.htmlの末尾に改行コードを追加する

この3点のうち、②は影響範囲が多いため、③はユニットテストの根本的解決にはならないため、
私からは①を提案します

### 原因と改善案のコード
* Markdownの変換処理後に、改行コードが末尾に加わる原因
リスト作成するたびにタグと改行コードが追加されていることがわかります
（md2html.jsのmarkedからたどる）

Renderer.js
```
list(body, ordered, start) {
    const type = ordered ? 'ol' : 'ul',
      startatt = (ordered && start !== 1) ? (' start="' + start + '"') : '';
    return '<' + type + startatt + '>\n' + body + '</' + type + '>\n';
  }
```

* 改善案
Markdownから変換処理されたファイルの前後の空白と改行を削除します
先頭行に空白や改行コードが必要なユースケースが想定できないため、trim()を使用します

md2html-test.js
```
assert.strictEqual(md2html(sample, { gfm: false }).trim(), expected);
});
//中略
assert.strictEqual(md2html(sample, { gfm: true}).trim(), expected);
});
```
↓↓↓
```
assert.strictEqual(md2html(sample, { gfm: true }).trim(), expected);
});
//中略
assert.strictEqual(md2html(sample, { gfm: false }).trim(), expected);
});
```

**Comment by sasahara-study** [comment]
もし、これらの方法以外でユニットテストが成功した場合は教えてください。

もし上記の報告と改善案が適切ならば、https://github.com/js-primer/local-serverにおけるブランチの作成権限を私のアカウントに付与してください
（現在、このリポジトリに対して私はcreate branchができないです）

**Comment by azu** [comment]
これはリポジトリのテストケース自体が通ってないということですかね?

うーん、CIでは通っているので、別の所で改行が入ってる可能性はあります。

- LF以外の改行コードを使っているケース
  - https://jsprimer.net/use-case/nodecli/helloworld/#create-project
- OSの違い(Windowsとその他で違うことがある)
- エディタとかがEOLを入れているケース(fixturesに改行コードが入ってるケース)

ブレやすいので、normalizeするのは賛成です。

**Comment by azu** [comment]
Forkすれば、Pull Requestは出せますね。

https://docs.github.com/ja/github/getting-started-with-github/fork-a-repo

**Comment by sasahara-study** [comment]
@azu 
コメントありがとうございます。

> LF以外の改行コードを使っているケース
確認しましたがすべてLFでした

> OSの違い（Windowsとその他で違うことがある）

Windowsです。私が作成した資材で第三者（macユーザー）にもやってもらいましたが失敗したそうです

> エディタとかがEOLを入れているケース（fixturesに改行コードが入ってるケース）

VSCodeをつかっているのですが、あてはまりますか？

**Comment by azu** [comment]
ファイル保存時にEOLに改行を入れる設定ができるものは多いので、その辺は関係あるかもしれません。

Windowsも一応CIでテスト通ってるように見えましたが、 @lacolaco これってCIでテストしている?
https://github.com/asciidwango/js-primer/runs/930570408?check_suite_focus=true
https://github.com/asciidwango/js-primer/tree/master/source/use-case/nodecli/refactor-and-unittest/src/test
(リポジトリ上では[.editorconfig](https://github.com/asciidwango/js-primer/blob/master/source/use-case/nodecli/refactor-and-unittest/src/test/.editorconfig)で末尾に改行が入らないように設定していました。)

なんにせよ、ノーマライズする方法を入れるのがいいかなと思います。

**Comment by sasahara-study** [comment]
@azu 

> Forkすれば、Pull Requestは出せますね。

ありがとうございます。
ブランチ作成からの流れしかやったことないので時間がかかると思いますがやってみます

**Comment by daisuke-yoshimoto** [comment]
@azu 

> ファイル保存時にEOLに改行を入れる設定ができるものは多いので、その辺は関係あるかもしれません。

sample.mdの内容をテストケースのようにmarkedに変換させると、 https://github.com/markedjs/marked/blob/v1.0.0/src/Renderer.js#L71 の部分で`<ul>`タグの後ろに改行コード(LF)が挿入されるようです。そのため、expected.htmlの内容とAssertすると改行コードのあるなしで差が出るようです。

* markedのコード部分
```
  list(body, ordered, start) {
    const type = ordered ? 'ol' : 'ul',
      startatt = (ordered && start !== 1) ? (' start="' + start + '"') : '';
    return '<' + type + startatt + '>\n' + body + '</' + type + '>\n';
  }
```

### 変換前（HTML）

```
- サンプル1
- サンプル2

```

### 変換後（HTML）


```
<ul>
<li>サンプル1</li>
<li>サンプル2</li>
</ul>


```

**Comment by sasahara-study** [comment]
@azu @daisuke-yoshimoto 
コードを修正しました
ご確認お願い致します。

今回追加したコードはこけていないのですが、npmインストールでこけているようです。

**Comment by lacolaco** [comment]
> ファイル保存時にEOLに改行を入れる設定ができるものは多いので、その辺は関係あるかもしれません。
> 
> Windowsも一応CIでテスト通ってるように見えましたが、 @lacolaco これってCIでテストしている?
> https://github.com/asciidwango/js-primer/runs/930570408?check_suite_focus=true
> https://github.com/asciidwango/js-primer/tree/master/source/use-case/nodecli/refactor-and-unittest/src/test
> (リポジトリ上では[.editorconfig](https://github.com/asciidwango/js-primer/blob/master/source/use-case/nodecli/refactor-and-unittest/src/test/.editorconfig)で末尾に改行が入らないように設定していました。)
> 
> なんにせよ、ノーマライズする方法を入れるのがいいかなと思います。

今確認しましたがテストコードのテストはされていないですね

**Comment by sasahara-study** [comment]
プルリクがマージされましたのでこのissueもクローズします
