### ISSUE TITLE
「ユニットテストを記述する」のユニットテスト成功時のメッセージ

### ISSUE THREAD

**Issue by nekoTheShadow** [asciidwango/js-primer#1235]
## 該当ページ

- https://jsprimer.net/use-case/nodecli/refactor-and-unittest/

## 説明

「31.5.4 ユニットテストを記述する」で、mochaによるユニットテストが成功すると、以下のようなメッセージが表示されるとあります。

```
$ npm test
> mocha

  ✓ converts Markdown to HTML
  ✓ converts Markdown to HTML (GFM=true)

  2 passing (31ms)
```

しかし実際には以下のようになると思うのですが、いかがでしょうか? (つまり、`(GFM = false)`が漏れている)

```
$ npm test
> mocha

  ✓ converts Markdown to HTML (GFM=false)
  ✓ converts Markdown to HTML (GFM=true)

  2 passing (31ms)
```

また、この直前に「1件のテストが通れば成功です。」とありますが、これは「2件のテストが通れば成功です。」のほうがより適切なように思われます。

**Comment by azu** [comment]
たしかにそうですね。

**Comment by nekoTheShadow** [comment]
誤りということなので、修正用のPull Request投げました。よろしくお願いいたします。

**Comment by azu** [comment]
修正されたのでCloseします。
対応ありがとうございました。

**Comment by lacolaco** [comment]
修正ありがとうございます！
