### ISSUE TITLE
Objectはすべての元 の継承の説明文

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1239]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/prototype-object/README.md

> Objectのインスタンスは、このObject.prototypeオブジェクトに定義されたメソッドやプロパティをインスタンス化したときに継承します。

「メソッドやプロパティをインスタンス化する」ようにも取れ、ややわかりづらいです。

> Objectのインスタンスは、このObject.prototypeオブジェクトに定義されたメソッドやプロパティを、インスタンス化したときに継承します。

のように読点を入れると明確になります。

もしくは、イスタンス化のについては続く文で補足説明されているため、次のように「インスタンス化」は省略してよいのではと思います。

> Objectのインスタンスは、このObject.prototypeオブジェクトに定義されたメソッドやプロパティを継承します。

**Comment by azu** [comment]
`、` を入れて回避するのは本質的じゃないので、文を分ける or 文を変えて解決するのが良いですね。

> Objectのインスタンスは、このObject.prototypeオブジェクトに定義されたメソッドやプロパティを継承します。

でも"インスタンス化"する時に継承されることは伝わりそうなので、"インスタンス化"を省略するのが良さそうな気がします

**Comment by dogatana** [comment]
ありがとうございます。
PR を出しました。
