### ISSUE TITLE
[提案]見出しリンクをクリックしやすくする

### ISSUE THREAD

**Issue by kenzoukenzou** [asciidwango/js-primer#1253]
JavaScriptを学習する際、とても参考にさせて頂きました🙇‍♂️
サイトにて復習していた際、気づいた点がありましたのでご提案致します。

## 該当ページ

- [ ]  [https://jsprimer.net/basic/class/#class-declaration](https://jsprimer.net/basic/class/#class-declaration)

他のページも同様。

## 説明
![スクリーンショット 2020-08-30 16 23 59](https://user-images.githubusercontent.com/33926355/91653637-8055cc80-eadd-11ea-8f95-98c5486e4231.png)

- Google Chromeの画面サイズを横幅1280pxにする
- 見出しのリンクをクリックとすると、プレビューナビゲーションが近いため誤クリックしてしまいやすい

## 対策

- プレビューナビゲーションの `min-width` を小さくする
- Qiitaのように見出しのテキストごと、クリックできるようにする

**Comment by azu** [comment]
そうですね。

今は[gitbook-plugin-anchors](https://github.com/rlmv/gitbook-plugin-anchors)というプラグインを使ってるだけなので、これのスタイルがイマイチな感じがしますね。
https://github.com/rlmv/gitbook-plugin-anchors/blob/ba139e94705b71d7c752015e6e7407aaaf07528f/index.js#L5-L20

処理自体は難しくないので、プラグインを書いて

> Qiitaのように見出しのテキストごと、クリックできるようにする

のような実装にしてしまうのがよいかもしれないですね。

**Comment by kenzoukenzou** [comment]
ご返信ありがとうございます！
ちょっと空き時間にやってみます👀

既存コードでプラグインを自作(拡張)しているところなどありますでしょうか？
ざっとコード目を通したのですが、どういうディレクリ構造で書くのかな..という点が掴めずでして😓

**Comment by azu** [comment]
https://github.com/honkit/honkit/issues/118
HonKit(このサイトの生成ツール)自体にもちょっとにた話が来ていて、少し調べていたのですが、

このクリックしにくい問題の根本的な原因は、ナビゲーションが `page-inner` のpaddingを無視して覆いかぶさってしまうことがあるからな気がしました。
アンカーのクリックしやすさを改善しても、ナビゲーションがページにかぶってきている問題のほうが少しおかしい感じがします。

<img width="899" alt="image" src="https://user-images.githubusercontent.com/19714/91703469-3213fc80-ebb5-11ea-90a3-5aa5087a55d2.png">

![image](https://user-images.githubusercontent.com/19714/91704148-296ff600-ebb6-11ea-8295-30d7de14ba6a.png)

> プレビューナビゲーションの min-width を小さくする

そのため、こちらを調整して被らないようにするのが良いかもしれません。
コレ自体はCSSで上書きする形で実現できるとい思うので、この辺に `min-width` の定義を追加するのがよさそうな気がします。
https://github.com/asciidwango/js-primer/blob/master/source/_layouts/website/page.html

これ自体はHonKitのデフォルトテーマの問題(被るのスタイルがおかしい)とも言えるので、HonKitのデフォルトテーマ側で直してもいいのかな?
calcとかでうまく計算できると一番いいのですが、イマイチいい方法が思いついてないです。。
https://github.com/honkit/honkit/issues/119

**Comment by kenzoukenzou** [comment]
調べて頂き、Issue作成もありがとうございます🙇‍♂️
確かにそうですね.. かぶさってしまうので見出しを修正してみ意味がなさそうですね.. 

> そのため、こちらを調整して被らないようにするのが良いかもしれません。
コレ自体はCSSで上書きする形で実現できると思うので、この辺に min-width の定義を追加するのがよさそうな気がします。
https://github.com/asciidwango/js-primer/blob/master/source/_layouts/website/page.html

このやり方でできそうか一度試してみます 👀
