### ISSUE TITLE
タグ関数の補足説明追加

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1256]
## 該当ページ

- https://jsprimer.net/use-case/ajaxapp/display/

## リクエスト/提案内容

タグ関数の説明文と `escapeHTML` を読んでもどのように動作するのかわかりづらかったので、

>タグ関数には、第一引数に文字列リテラルの配列、第二引数に埋め込まれる値の配列が与えられます。

とあるのを次のように変更し、動作例を追加すると理解しやすくなるように思いまいますが、どうでしょうか。

>タグ関数には、第一引数にテンプレートリテラルをプレースホルダ（ `${ }` ）で分割した文字列の配列、第二引数以降にプレースホルダの値が与えられます。

```js
function tagFunction(strings, name, price) {
    console.log(strings); // => [ '商品', 'の価格は', '円です' ]
    return strings[0] + name + strings[1] + price + strings[2];
}

const name = "abc";
const price = 123;
const message = tagFunction`商品${name}の価格は${price}円です`;
console.log(message); // => 商品abcの価格は123円です
```

## 期待する結果

このような補足があれば、`escapeHTML` のコードを理解しやすくなると思います。

**Comment by azu** [comment]
そうですね。その方がわかりやすそうですね。
多分プレースホルダーという言葉を「文字列」の章では使ってなかったと思うので、この辺はどちらかに統一したいですね。

>  このとき、関数の第一引数にはテンプレートの中身が${}で区切られた文字列の配列、第二引数以降は${}の中に書いた式の評価結果が順番に渡されます。
> https://jsprimer.net/basic/string/#tagged-template-function

**Comment by dogatana** [comment]
リテラルの方は確認してたのですが、文字列の方に説明があるんですね。見落としてました。。
次のようにタグ関数から飛べるようなっていると、（私のように忘れていても）理解しやすくなると思います。

次の`escapeHTML`関数はテンプレートリテラルにタグづけするための[**タグ関数**](https://jsprimer.net/basic/string/#tagged-template-function)です。

**Comment by dogatana** [comment]
#1261 を出したので、こちらは Close します。
