### ISSUE TITLE
Node.js で CLI アプリ ｰ デフォルト設定を定義する 

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1257]
## 該当ページ

- [デフォルト設定を定義する  ](https://jsprimer.net/use-case/nodecli/md-to-html/#declare-default)

## 説明

次のコードは説明文から `--gfm` が指定されていない場合、デフォルトの `false` が有効(=**上書きされない**) ことを意図されていると理解しましたが、`--gfm` が指定されていない場合、`program.opts()` は `{ gfm: undefined }` となり、`undefined` で上書きされてしまう挙動となりました。

```js
const cliOptions = {
    gfm: false,
    ...program.opts(),
};
```

**Comment by lacolaco** [comment]
スプレッドではなく `gfm: program.opts().gfm ?? false` だといいのかな？ES2020対応もしたし

**Comment by lacolaco** [comment]
今週末テストしてみます
