### ISSUE TITLE
Todo App の HTML に DOCTYPE がないことの見た目の影響

### ISSUE THREAD

**Issue by dogatana** [asciidwango/js-primer#1263]
* 該当ページ  [入力内容をTodoリストに表示する ](https://jsprimer.net/use-case/todoapp/form-event/#input-to-todolist)

* 内容

サンプルソースでは先頭に `<!DOCTYPE html>` がありません。
手元で写経しているときには `<!DOCTYPE html>`  をつけていて、これによる見た目の違いがあったので、報告しておきます。使用ブラウザは Firefox です。

昨今では `<!DOCTYPE html>` をつけて、HTML5 であることを宣言するのが通例と読んだことがあります。それが正しければ、つけた状態としておくのが良いように思います。

* 詳細

1. What・・ の後の空白行がなく、線が1本になる
![space](https://user-images.githubusercontent.com/12756480/92983174-ca2ab380-f4dc-11ea-8b20-409e519d6bf0.png)

 `<!DOCTYPE html>` がない場合、User Agent の Style Sheet の `margin-block-end: 1em` が適用されるようです。（Chromeで確認）

2. 箇条書きのマークが枠外にはみでる
![dot](https://user-images.githubusercontent.com/12756480/92983214-f8a88e80-f4dc-11ea-949c-bac162dd9649.png)

`<li>` が単独で（`<ul>` で囲まれずに）存在するためのようです。`<ul>` があれば css の `.todo-list ul { list-sytle: none; }` でマークが消されます。

**Comment by azu** [comment]
`<!DOCTYPE html>` つけないとHTML5にならないのでつけたほうがいいですね。
抜けているのは意図的ではないと思うので、追加してしまうのがよさそうです

**Comment by dogatana** [comment]
細かいですが、コードの他に画面キャプチャも差し替えが必要になりますね。

**Comment by azu** [comment]
`<!DOCTYPE html>` を追加してスクショを更新しました。
最初方だけ ul がコード的に抜けているので、これは別Issueで作りました
https://github.com/asciidwango/js-primer/issues/1316
