### ISSUE TITLE
用語の統一: 「返り値」と「戻り値」

### ISSUE THREAD

**Issue by kangetsu121** [asciidwango/js-primer#1284]
- 「戻り値」を「返り値」に統一
- 「返り値」を用いるルールを `prh.yml` に追記

---
本文中には「返り値」と「戻り値」が混在しています。  
現時点で数の多い「返り値」に統一するのはいかがでしょうか。  
また, 統一する場合ルールを `prh.yml` に追記するのはいかがでしょうか。

```console
kangetsu@ubuntu18:~/workspace/js-primer
$ grep -rn "返り値" source/* | wc -l
71
kangetsu@ubuntu18:~/workspace/js-primer
$ grep -rn "戻り値" source/* | wc -l
18
kangetsu@ubuntu18:~/workspace/js-primer
```

**Comment by azu** [comment]
どこかで決めたような気がしますが[meeting](https://github.com/asciidwango/js-primer/tree/master/meetings)にないので決まってなかったのかもしれないですね。

`返り値` に統一でよいと思います。

cc @lacolaco
