### ISSUE TITLE
巻き上げ対象の変数の種類の説明について

### ISSUE THREAD

**Issue by kangetsu121** [asciidwango/js-primer#1289]
## 該当ページ

- https://jsprimer.net/basic/function-scope/#function-declaration-hoisting  (「関数とスコープ」の「関数宣言と巻き上げ」)

## 質問内容

> 注意点として、varやletなどで宣言された変数へ関数を代入した場合はvarのルールで巻き上げられます。 そのため、varで変数へ関数を代入する関数式では、hello変数が巻き上げによりundefinedとなるため呼び出せません（「関数と宣言（関数式）」を参照）。

` varやletなどで宣言された変数へ関数を代入した場合はvarのルールで巻き上げられます` とありますが, `let` で宣言した変数は巻き上げの対象にならないのではないでしょうか。
確認として, この説明の直後にある script 例で, 以下の様に `var` を `let` に変えると, `hello` 変数が `undefined` なエラーでなく,  `ReferenceError: Cannot access 'hello' before initialization` となりました。

確認用スクリプト
```js
hello(); // => ReferenceError: Cannot access 'hello' before initialization

// 例では `var で宣言しており, その場合は TypeError となる
let hello = function(){
    return "Hello";
};
```

**Comment by azu** [comment]
> ` varやletなどで宣言された変数へ関数を代入した場合はvarのルールで巻き上げられます` とありますが, `let` で宣言した変数は巻き上げの対象にならないのではないでしょうか。

巻き上げは `var` と `function` 宣言の性質なので、`let`では巻き上げは起きません。

```diff
- 注意点として、varやletなどで宣言された変数へ関数を代入した場合はvarのルールで巻き上げられます。 
+ 注意点として、varで宣言された変数へ関数を代入した場合はvarのルールで巻き上げられます。 
```
これ `let` が入ってるが間違いですね。
