### ISSUE TITLE
`Note` の節の style の混在について

### ISSUE THREAD

**Issue by kangetsu121** [asciidwango/js-primer#1290]
## 該当ページ

- https://jsprimer.net/basic/class/#inner-property (「クラス」の「Note: [[Prototype]]内部プロパティを読み書きする」)

## 質問内容

ここのみ上下に水平線がありますが, この style は意図的なものでしょうか。
また, 同じ章に別の Note [[Note] クラス名は大文字ではじめる](https://jsprimer.net/basic/class/#class-name-start-upper-case) もありますが, そちらは節のタイトルの `Note` 表記方法も異なり, 水平線もありません。

この違いが意図したものか気になり質問させていただきました。

**Comment by azu** [comment]
ただの表記ゆれなため、 `[Note]` に統一して良い気がします。
