### ISSUE TITLE
「ユニットテストを記述する」ページの heading の重複について

### ISSUE THREAD

**Issue by kangetsu121** [asciidwango/js-primer#1293]
## 該当ページ

- [ユニットテストを記述する#ユニットテストを記述する](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/#write-unit-test)

## 質問内容

「ユニットテストを記述する」という heading が `h1` と `h2` で重複しています。  
[markdownlint の MD024](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024---multiple-headings-with-the-same-content) では非推奨となっていますが, こちらは意図的なものでしょうか。  
markdownlint は必ずしも従うべきものでもないので, 意図的であればもちろんこのままでよいと思います。

**Comment by azu** [comment]
> Rationale: Some markdown parsers generate anchors for headings based on the heading name; headings with the same content can cause problems with that.

markdownlintだとidの重複を根拠にしているみたいですね。
一応異なるIDを振ってあるのでセマンティクス的な問題はない気がしますね。
https://jsprimer.net/use-case/nodecli/refactor-and-unittest/#unit-test
https://jsprimer.net/use-case/nodecli/refactor-and-unittest/#write-unit-test

**Comment by kangetsu121** [comment]
markdownlint が懸念している点は問題ないこと、強調的意味を持たせていることに納得しました。  
こちら、必要に応じてクローズで問題ありません、ご回答ありがとうございました！
