### ISSUE TITLE
ajax: UserIDに相対パスが入れられる

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#130]
`https://api.github.com/users/${userId}` だと `../` みたいな任意のパスへリクエストできるなーと思った。(このサンプルだと何か出来るわけでもないのでいいけど)

![ajax example 2016-08-24 10-12-49](https://cloud.githubusercontent.com/assets/19714/17915167/5c9706ee-69e3-11e6-8cac-b0f227857ce7.png)

正規表現でIDを絞るとかあると丁寧なのかも

**Comment by azu** [comment]
IDは英数字です みたいな話を追加するぐらい?

**Comment by laco0416** [comment]
脱線するんじゃないかと心配だけど、書いてみて考える。処理的には正規表現で弾いて終わり

**Comment by vvakame** [comment]
http://goo.gl/79E7xl 書いた(これは載らない(確信

**Comment by azu** [comment]
@laco0416 これ `encodeURIComponent(userID)` するのがいいんじゃないかなって気がしてきた。
これなら説明別にいらないし、パス文字列にはならない
