### ISSUE TITLE
GitHub Discussionを公開する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1300]
読んでいる人同士で質問し合ったりする場所とかがあった方がいいという話があります。
いわゆるコミュニティ的なものがあると学習に役立つと思うので、GitHub Discussionを掲示板として公開するのはどうかな?というIssueです。

書籍のリポジトリ自体にあるべきかは良し悪しがありますが、他に適切な場所が浮かばないのでこのリポジトリのGitHub Discussionを質問/勉強会的な用途で使えるように開放するのはどうかなという感じです。

意見を募集中

関連:

- https://twitter.com/sardine_bird/status/1371379735826030597

**Comment by azu** [comment]
考えるポイント

- [コントリビューター行動規範](https://github.com/asciidwango/js-primer/blob/master/.github/CODE_OF_CONDUCT.md)などを整える必要がある
- Q&Aなどある種のテンプレートを用意して上手く質問できるようにする仕組みが必要
- GitHub Issueからの転換のしやすさなども考えるとこのリポジトリになる
  - https://github.com/js-primer のどこかというのもあるが、リポジトリと分ける積極的な理由がないため
  - 結局モデレートが必要なのは変わらないため
- Watchしている人にはデフォルトでDiscussionの通知も飛ぶが、設定ができる

![image](https://user-images.githubusercontent.com/19714/113500412-bfa73880-9558-11eb-8398-6157353d77a0.png)

**Comment by kahei** [comment]
読者にディスカッションの場を提供するというのは、いいアイデアだと思います。
場所はこのリポジトリでよいでしょう。
行動規範やQ&Aテンプレートに時間がかかりそうなら、ベータ版として公開して、そこで規範やら運用について意見交換をするというのもありかも。

**Comment by azu** [comment]
とりあえずベース書いてDiscussion公開するのやります。
https://jsprimer.net/intro/feedback/ とTopページあたりに誘導も置いておきたい

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/discussions/1304
CONTRIBUTING.md みたいなテンプレートはまだないみたいなので、Pinしたスレッドに大まかな使いみちを書きました。

- [Templates (like issue templates) for discussions · Discussion #2838 · github/feedback](https://github.com/github/feedback/discussions/2838?sort=top)
