### ISSUE TITLE
HTTP通信

### ISSUE THREAD

**Issue by ren-suyama** [asciidwango/js-primer#1301]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/ajaxapp/http/README.md

レスポンスの受け取りのところで、

$ npm install node-fetch

をコマンド実行して、

$ const fetch = require("node-fetch");

をindex.js上に書かないとfetchが実行できませんでした。

**Comment by azu** [comment]
これはブラウザで動かすコードなので、Node.jsだとFetch APIはないため、`node-fetch`などが必要となってしまいますね。
