### ISSUE TITLE
-2の31乗とはなにか

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#1313]
## 該当ページ

https://github.com/asciidwango/js-primer/tree/master/source/basic/operator

## 説明

#1312 にコメントするのが遅れたのですが、

> そのため符号付き32ビット整数で表現できる数値の範囲は-2の31乗（`1111_1111_1111_1111_1111_1111_1111_1111`）から2の31乗（`0111_1111_1111_1111_1111_1111_1111_1111` ）までとなります。

`-2の31乗`というのが、`(-2)^31`と`-(2^31)`で曖昧な表現になっているように思います。

**Comment by azu** [comment]
たしかにおかしいですね。

- `-(2の31乗)`
- `-(2^31)`

後者のほうがわかりやすいのですが、`^` を文章中で使ってないんですよね。
何かいい表現方法が必要ですね。

**Comment by yumetodo** [comment]
そういえばC++だと

```cpp
#include <limits>
#include <cstdint>
using limit = std::numeric_limits<std::int32_t>;
static_assert(limit::min() + 1 == -limit::max());
int main()
{}
```

という環境もあるのですが、Javascriptはどうなのでしょう。

**Comment by azu** [comment]
> The abstract operation ToInt32 takes argument argument. It converts argument to one of 232 integral Number values in the range 𝔽(-231) through 𝔽(231 - 1), inclusive. 
> https://tc39.es/ecma262/#sec-toint32
みたいですね
