### ISSUE TITLE
変数名fulFilledPromiseはfulfilledPromiseに変更する

### ISSUE THREAD

**Issue by sn6t** [asciidwango/js-primer#1325]
## 該当ページ

- [非同期処理:コールバック/Promise/Async Function: Promise.resolve](https://jsprimer.net/basic/async/#promise-resolve)

## 説明

fulFilledPromiseという変数名ですが、fulfilledで一つの単語のため、キャメルケースのルールに従うのであれば、fulfilledPromiseに変更したほうがいいと思います。

```
const fulFilledPromise = new Promise((resolve) => {
```

**Comment by azu** [comment]
そうですね、 `fulfilledPromise` の方が適切な気がします。
