### ISSUE TITLE
currentValueが仮引数である旨を明示

### ISSUE THREAD

**Issue by eatplaynap** [asciidwango/js-primer#1343]
## 該当ページ

- [ループと反復処理 · JavaScript Primer \#jsprimer](https://jsprimer.net/basic/loop/#array-foreach)

## リクエスト/提案内容

> コールバック関数の`currentValue`には1から3の値が順番に渡されます。

こちらの表記ですが、`currentValue`がコールバック関数を指していると勘違いする可能性がありそうだと思いました。
`currentValue`自体がコールバック関数なのではなく、コールバック関数の仮引数である旨を表記したほうが誤解せずに済みそうです。

## 期待する結果

下記のように変更

> コールバック関数の仮引数である`currentValue`には、1から3の値が順番に渡されます。

**Comment by azu** [comment]
仮引数と明示した方がよさそうですね。
