### ISSUE TITLE
出力結果がおかしい

### ISSUE THREAD

**Issue by shirotamaki** [asciidwango/js-primer#1353]
# 出力結果がおかしい
以下のページでプログラムを実行すると、出力結果が同時に実行されます。
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/async/README.md

ChromeデベロッパーツールのConsole機能を使い試してみると、
まず、`console.log("処理を開始");`が出力され、
その後、`blockTime(1000)`が実行され、1000ミリ秒待機します。
待機後、`console.log("この行が呼ばれるまで処理が1秒間ブロックされる");` が出力されます。

上記のConsoleでの出力結果が正しいと思われますが、
電子書籍の出力結果は、全て同時に出力されてしまいます。

ご確認お願いいたします。

## 以下、問題のプログラム

> ```javascript
> // 指定した`timeout`ミリ秒経過するまで同期的にブロックする関数
> function blockTime(timeout) {
>     const startTime = Date.now();
>     // `timeout`ミリ秒経過するまで無限ループをする
>     while (true) {
>         const diffTime = Date.now() - startTime;
>         if (diffTime >= timeout) {
>             return; // 指定時間経過したら関数の実行を終了
>         }
>     }
> }
> console.log("処理を開始");
> blockTime(1000); // 他の処理を1000ミリ秒（1秒間）ブロックする
> console.log("この行が呼ばれるまで処理が1秒間ブロックされる");
> ```
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/basic/async/README.md#L31 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/basic/async/README.md#L31>

**Comment by azu** [comment]
多分実行を押して 1秒ブロックされてると思います。
UIがブロックされると、コンソールログが出るのもブロックされてしまうため、同時に出ているように感じるのだと思います。

```js
console.log("処理を開始" + new Date());
blockTime(1000); // 他の処理を1000ミリ秒（1秒間）ブロックする
console.log("この行が呼ばれるまで処理が1秒間ブロックされる" + new Date());
```

などにしてみると、1秒ずれているのがわかると思います。

<img width="966" alt="image" src="https://user-images.githubusercontent.com/19714/140671347-5a398e24-5b79-45e8-9e85-fe89889eab83.png">

**Comment by shirotamaki** [comment]
なるほど、そうなのですね！
上記のプログラムで試してみると、1000ミリ秒ブロックされていました。
電子書籍の仕様では、「UIがブロックされると、コンソールログが出るのもブロックされてしまう」ということなのですね。
理解できました。
ご回答いただきありがとうございました！
