### ISSUE TITLE
ES2022: prototypeを表すのに # を使うべきかどうか

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1368]
- #1337 
- #1364 

ES2022のクラスに  `#` が導入される。

- [proposal-class-fields/PRIVATE_SYNTAX_FAQ.md at main · tc39/proposal-class-fields](https://github.com/tc39/proposal-class-fields/blob/main/PRIVATE_SYNTAX_FAQ.md)

なので `#` はPrivate Fieldsを意味するように見える。

```js
class MyClass {
  #method = () => {
     console.log("private method")
  } 
}
```

`MyClass#method` と書いてしまうと、`MyClass.prototype.method` と `MyClass`のprivate `#method`のことかが区別できなくなる。
(📝 実際には `this.#method` としてアクセスするので、`.`はあるけど、表現的に紛らわしいのは同じ)

そのため、`Array#includes` みたいに prototypeを表す記号として `#` を使うのは、避けたほうがいい可能性が高い。

## 変更後の基本ルール

- セクションタイトル: 
  - 正式名称の 「`Array.prototype.includes` メソッド 」を使う
- 文中
  - prototoypeメソッドは、「Arrayの`includes`メソッド」を使う
  - 静的メソッドの場合は、「 `Array.from` 静的メソッド 」と言うことで区別する
  - プロパティの場合は、「Objectの `a` プロパティ」という表現
  - ~Class Fieldは `メンバー` と呼ぶ感じで、プロパティと区別~ まだ未定
- 例外
  - CSSセレクタでのID指定: `div#result` はlintのオプションで例外としてる

## やるべきこと

- `#` を prototype に置き換える
- この記法の紹介は消す 
  - > この書籍では、プロトタイプメソッド（インスタンスメソッド）をクラス#メソッド名のように表記します。
  - https://jsprimer.net/basic/class/#class-prototype-method-definition
- 代わりに、prototypeの紹介の時に、`#` がprototypeを表す記号として使われていることがあったと言うコラムをたす
  - この書籍からは `#` === `prototype` は取り除くけど、他の文章でも使われてること多い

@lacolaco どうですかね?

**Comment by azu** [comment]
https://zenn.dev/qnighy/articles/3a999fdecc3e81#comment-aaac501b3562a4
`#` が示していたものは、
prototype or インスタンスのプロパティにあたるFields #1364 
の2つがある。
なので、それぞれ別々に使い分ける必要性があるのかなー

**Comment by azu** [comment]
https://exploringjs.com/impatient-js/ch_arrays.html#methods-iteration-and-transformation-.find-.map-.filter-etc.
は `.map()` とか親を完全に削ってる

**Comment by azu** [comment]
要検証ではあるけど、次のようなイメージ

- タイトルは正式名称の `Array.prototype.includes` メソッド
- 内部では Array の `includes` メソッド 
  - 静的メソッドの場合は `Array.from` 静的メソッド と言うことで区別できる
  - プロパティにも `#` を使ってるケースあるので Objの `a` プロパティ的な表現
  - Class Fieldは `メンバー` と呼ぶ感じで、プロパティと区別

**Comment by lacolaco** [comment]
> 内部では、 Array の includes メソッド

これに賛成です。

**Comment by azu** [comment]
https://jsprimer.net/use-case/todoapp/

`div#result` というCSSセレクタのパターンもあったことに気づいた。
でもこれは `#` 自体に IDセレクタの意味があるから、そういう説明するしかないか。
textlintルールでいまいち制御できなくて不便だな

**Comment by azu** [comment]
#1382 で変更をまとめてした
