### ISSUE TITLE
falsyな値の一覧の不足

### ISSUE THREAD

**Issue by ToshihiroWatanabe** [asciidwango/js-primer#1378]
## 該当ページ

[演算子 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/operator/#and-operator)
[暗黙的な型変換 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/implicit-coercion/#any-to-boolean)
[関数と宣言 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/function-declaration/#function-default-parameters)
[条件分岐 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/condition/#if-statement)

## 説明

falsyな値として7種類の値が挙げられていますが、正しくは-0を含めた8種類ではないでしょうか。

### 参考
[Falsy (偽値) - MDN Web Docs 用語集: ウェブ関連用語の定義](https://developer.mozilla.org/ja/docs/Glossary/Falsy)

**Comment by azu** [comment]
厳密にはそうだと思いますが、`-0` 自体を説明してないので、入れるのが適当かは微妙な気がしますね。

**Comment by azu** [comment]
`7種類` という言葉が限定してるように見えるので、次の値は〜 ぐらいで具体例としてリストアップする書き方もありそうですね。

**Comment by azu** [comment]
```
次の値は、暗黙的な型変換を `false` となることが仕様で決まっています。

...

これらの値のことをfalsyな値と呼びます。
```

**Comment by azu** [comment]
falsyは仕様的な定義があるわけではないのに、
仕様的な定義っぽく書かれていたので、もう少し通称的な意味として読めるように変更。
`-0`と`+0`については、特に言及しないままの形にしました。
https://github.com/asciidwango/js-primer/pull/1482
