### ISSUE TITLE
Todoアイテムの追加を実装する: # が残ってる

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1389]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/todoapp/form-event/README.md

> App#mountの呼び出し
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/use-case/todoapp/form-event/README.md#L124 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/use-case/todoapp/form-event/README.md#L124>

`App#mount` とかが残ってた。

Refs #1382 

## やること

- [ ] `App#mount` を `App`クラスの`mount`メソッド とかに変更する
- [ ] 同じようなものを見つけて治す

**Comment by komura-c** [comment]
こちら取り組みたいです

**Comment by azu** [comment]
ありがとうございます！
