### ISSUE TITLE
2016-09-09 Meeting アジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#139]
2016-09-09のミーティングで話したいことを事前に書いておく場所です。

/cc @laco0416

**Comment by azu** [comment]
[クラスメソッド/インスタンスメソッドの表記 · Issue #110 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/110 "クラスメソッド/インスタンスメソッドの表記 · Issue #110 · asciidwango/js-primer")

**Comment by azu** [comment]
基本文法: プチユースケースの扱い/書く場所

セクションによってはもう少し具体的な例題を出したい場合があるが、その話をすると無駄に長くなる感じがする。

コラムのような本文とは別で解説したいけど、課題が中心な話になる気がするのでコラムとはまた違った性質がある気がしている。
セクション末尾の練習問題なようだけど、なぜそういう書き方をするのかというプチユースケースにもとづく話なのでもう少し具体的な解説が付くイメージ

- https://github.com/asciidwango/js-primer/issues/17#issuecomment-244540827
- [condition: switch文の例を追加する · Issue #135 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/135 "condition: switch文の例を追加する · Issue #135 · asciidwango/js-primer")

こういうのをどう扱うべきか。
本文に入れた時に、その本文と混じってしまって今後の拡張性が悪い気がしている。

**Comment by azu** [comment]
[ajax: UserIDに相対パスが入れられる · Issue #130 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/130 "ajax: UserIDに相対パスが入れられる · Issue #130 · asciidwango/js-primer")

**Comment by azu** [comment]
js-primer organizationを作ってみた(ちゃんと使うのかわからないけど、サンプルサイトとか置きたい場合にorganizationの方が都合がいいことが出てきそう)

- [js-primer](https://github.com/js-primer)
- [js-primer/lean: Lean Canvas](https://github.com/js-primer/lean)
- [https://js-primer.github.io/lean/](https://js-primer.github.io/lean/)

https://github.com/asciidwango/js-primer/issues/42

**Comment by azu** [comment]
- [js-primer/lean: Lean Canvas](https://github.com/js-primer/lean#high-level-concept)
- [『JavaScript: The Good Parts』で紹介されている標準メソッドまとめ - Qiita](http://qiita.com/kenju/items/9b289567bbc359abe54f)

コンセプトとして[本書の目的](https://github.com/asciidwango/js-primer/issues/103 "本書の目的")でも書いていたように、

> JavaScriptは変化を取り入れている言語であるため、JavaScriptの変化に対して対応できる基礎をつけていく

という部分を、もう少し強調できる素材が欲しい。

-----

[暗黙的な型変換 · JavaScriptの入門書 #jsprimer](https://asciidwango.github.io/js-primer/basic/implicit-coercion/ "暗黙的な型変換 · JavaScriptの入門書 #jsprimer")をブログ向けに書きなおしてみて [NaNはNot a NumberだけどNumber型である話 | Web Scratch](http://efcl.info/2016/09/06/nan/ "NaNはNot a NumberだけどNumber型である話 | Web Scratch") を書いてみた。
#138 に反応や書きなおしての感想をまとめている。
この時に思ったのは、本文ですべてのBad Partsを触れるのは難しいという点が明確にでてきた。

JavaScriptには明らかに誤用するものや悪いものというのが存在するので、
Bad Partsはどこかでしれたほうがいいと思った。

[前回のミーティング](https://github.com/asciidwango/js-primer/tree/master/meetings/2016-07-29#%E4%BD%BF%E3%82%8F%E3%81%AA%E3%81%8F%E3%81%A6%E3%81%84%E3%81%84%E3%82%A4%E3%83%87%E3%82%A3%E3%82%AA%E3%83%A0%E6%96%87%E6%B3%95)でも出たように[既に使わなくていいイディオム/文法 · Issue #108 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/108 "既に使わなくていいイディオム/文法 · Issue #108 · asciidwango/js-primer")はあるので、これをセクション? 何らかの形でまとめているといいのかもしれないと思った。

**Comment by azu** [comment]
基本文法のロードマップ: [Meta(基本文法): ロードマップ · Issue #137 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/137 "Meta(基本文法): ロードマップ · Issue #137 · asciidwango/js-primer")

**Comment by azu** [comment]
やっとES6対応した書籍が出始めた。

- [改訂新版JavaScript本格入門　～モダンスタイルによる基礎から現場での応用まで：書籍案内｜技術評論社](http://gihyo.jp/book/2016/978-4-7741-8411-1)
- [JavaScript本格入門　～モダンスタイルによる基礎からAjax・jQueryまで：書籍案内｜技術評論社](http://gihyo.jp/book/2010/978-4-7741-4466-5)

**Comment by azu** [comment]
--------------

ここからミーティング中

**Comment by azu** [comment]
> 基本文法: プチユースケースの扱い/書く場所

ユースケースで上手く消化できるならユースケースにしたい。
ジャブ的な例題があるといいのではという話

**Comment by azu** [comment]
> 基本文法: プチユースケースの扱い/書く場所

後からいい例がでてきたら追加する感じ。

**Comment by laco0416** [comment]
自由な文字列から数字だけを抜き出す処理の例

**Comment by azu** [comment]
switch文のやつもっと少ないコードブロックにする?
https://asciidwango.github.io/js-primer/basic/condition/

**Comment by azu** [comment]
> JavaScriptには明らかに誤用するものや悪いものというのが存在するので、
> Bad Partsはどこかでしれたほうがいいと思った。

Bad Parts + ESLint 的な話でまとめたセクションみたいのがあってもいいのかも。
https://github.com/asciidwango/js-primer/issues/102#issuecomment-236162759
https://github.com/asciidwango/js-primer/issues/108

**Comment by azu** [comment]
非推奨の章

**Comment by azu** [comment]
うっかり踏みそうな legacy Annex Bみたいなのを紹介する。

**Comment by azu** [comment]
[Object.is()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is "Object.is()") がTypeScriptにない…?

**Comment by azu** [comment]
> 基本文法のロードマップ: Meta(基本文法): ロードマップ · Issue #137 · asciidwango/js-primer

基本文法の後半

**Comment by laco0416** [comment]
`Object.assign` はNode.jsのCLIユースケースでコマンドライン引数とデフォルトオプションのマージで使うので、アプリケーション用途寄りの話を基本文法側で述べておかないといけない

**Comment by azu** [comment]
feature detection はユースケース内で出てきて欲しい

**Comment by azu** [comment]
コラム https://github.com/asciidwango/js-primer/issues/102#issuecomment-236432834

**Comment by azu** [comment]
> Elixir本を読んでいてディレクトリ構造についても言及する(いわゆるプロジェクトの作り方)例が上手くあるといいのかなとも思った。

ユースケース側で察する作りにする
Nodeとブラウザでそもそもディレクトリとか異なるだろうし

**Comment by azu** [comment]
実際にはまだ動かないよって注意書きで良いが…

**Comment by azu** [comment]
modules 現段階では、まだツールがないと動かないというような注意書きと共に基本文法を紹介する?

**Comment by azu** [comment]
TypeScript, Babel, SystemJSで読み方違う。
SystemJSはなぜ…

**Comment by azu** [comment]
注意書きを付けて文法だけを出すのが現実的かな

**Comment by azu** [comment]
次回は10月28日
