### ISSUE TITLE
文章の改善の提案：NaNになってしまった場合の処理のコード

### ISSUE THREAD

**Issue by chick-p** [asciidwango/js-primer#1410]
## 該当ページ

- [暗黙的な型変換 | 文字列 → 数値](https://jsprimer.net/basic/implicit-coercion/#string-to-number)

## リクエスト/提案内容

文章（コード）の改善の提案です。

以下の部分は、説明文に合わせたコードにすると、より良いのではと思っています。
https://github.com/asciidwango/js-primer/blob/master/source/basic/implicit-coercion/README.md?plain=1#L327-L336
````markdown
そのため、任意の値から数値へ変換した場合には、NaNになってしまった場合の処理を書く必要があります。   
変換した結果がNaNであるかはNumber.isNaN(x)メソッドで判定できます。
```js
const userInput = "任意の文字列";
const num = Number.parseInt(userInput, 10);
if (!Number.isNaN(num)) {
    console.log("NaNではない値にパースできた", num);
}
```
````

コードの上に、「NaNになってしまった場合の処理を書く必要がある」という説明があります。
一方、コードでは、NaN ではない値となった場合 が `true` になる条件になっています。
条件の `!` を外すほうが、より「NaNになってしまった場合の処理」に近づきそうだなと思いました。
また、`userInput` にも文字列が入っているので、true に入って `console.log()` されると良さそうと思いました。

## 期待する結果

コードの内容が、説明文の内容に沿っている

案：
```diff
```js
const userInput = "任意の文字列";
const num = Number.parseInt(userInput, 10);
- if (!Number.isNaN(num)) {
-     console.log("NaNではない値にパースできた", num);
+ if (Number.isNaN(num)) {
+     console.log("パースした結果NaNになった", num);
}
```
```

**Comment by azu** [comment]
否定系は読みにくくなるので、提案していただいた形の方が読みやすそうですね。
PR歓迎です
