### ISSUE TITLE
ajax: honkit-plugin-sandpackのプレビューに対応する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1421]
https://github.com/asciidwango/js-primer/blob/master/CONTRIBUTING.md#%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BFhtml%E3%83%97%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%83%A2%E3%83%BC%E3%83%89
https://github.com/honkit/honkit-plugin-sandpack

を使ってHTMLプレビューを埋め込めるようになったので、HTMLプレビューを埋め込みたい。
https://jsprimer.net/use-case/ajaxapp/

基本的にはスクショになっている部分に実行ボタンをつけるイメージでいいような気がする。

- https://jsprimer.net/use-case/ajaxapp/display/#section-checklist の前
- https://jsprimer.net/use-case/ajaxapp/promise/#section-checklist の前

cc @lacolaco

**Comment by azu** [comment]
これES Modulesの章も、実際に動く感じに書き直せるかも

**Comment by lacolaco** [comment]
なるほど、今日やってみます

**Comment by lacolaco** [comment]
@azu ログを確認するステップがあるんですがコンソールを表示させるオプションってありますか？

**Comment by azu** [comment]
まだないんですよねー
https://github.com/codesandbox/sandpack/pull/301
でちょうど実装中

**Comment by azu** [comment]
ログ自体はforwardされてメインのDevToolsに出てくるので、特に何も説明してない感じですね。
メインの文中ではまだこのプレビューについて触れてなくて、まだおまけ感がある扱いにしちゃってます。

**Comment by azu** [comment]
対応した
