### ISSUE TITLE
関数と宣言: 関数式の説明が分かりにくい

### ISSUE THREAD

**Issue by pklion** [asciidwango/js-primer#1427]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/function-declaration/README.md

[関数式の説明](https://jsprimer.net/basic/function-declaration/#function-expression)にある、
```
// 関数式
const 関数名 = function() {
    // 関数を呼び出したときの処理
    // ...
    return 関数の返り値;
};
```
と
```
// 関数式は変数名で参照できるため、"関数名"を省略できる
const 変数名 = function() {
};
// 関数宣言では"関数名"は省略できない
function 関数名() {
}
```
の const 関数名 / const 変数名 に表記ゆれがあり、説明が分かりにくくなっています。
多分下の説明の方が正しいかと思うのですが…

**Comment by azu** [comment]
最初の例は
```js
// 関数式
const 変数名 = function() {
    // 関数を呼び出したときの処理
    // ...
    return 関数の返り値;
};
```
が良さそうですね。

**Comment by yumetodo** [comment]
https://github.com/asciidwango/js-primer/commit/9e5709ea236de2c6d58927bbcb8baa0862424456

での修正もれそう
