### ISSUE TITLE
HTML-likeコメントが使える場合、使えない場合？

### ISSUE THREAD

**Issue by miy4** [asciidwango/js-primer#1494]
## 該当ページ

- [[ES2015] HTML-likeコメント](https://jsprimer.net/basic/comments/#html-like-comment)

## 質問内容

HTML-likeコメントを含んだコードをNode.jsとDenoで実行してみたところ、挙動が異なり、DenoではSyntaxErrorになりました。

```shell-session
$ cat html-like-comment.js
<!-- この行はコメントと認識される
console.log("この行はJavsScriptのコードとして実行される")
--> この行もコメントと認識される

$ node html-like-comment.js
この行はJavsScriptのコードとして実行される

$ deno run html-like-comment.js 
error: Uncaught SyntaxError: HTML comments are not allowed in modules
<!-- この行はコメントと認識される
   ^
    at <anonymous> (file:///workspaces/note-jsprimer/html-like-comment.js:1:4)
```

`deno run`のエラーメッセージをみると、モジュールのコンテキストで実行しようとしており、その場合、HTMLコメントは許容していない、と言っているように読めます。
HTML-likeコメントは使える場合と使えない場合があるのでしょうか？

**Comment by azu** [comment]
> B Additional ECMAScript Features for Web Browsers
> https://tc39.es/ecma262/#sec-additional-ecmascript-features-for-web-browsers

これはAnnex-Bというウェブブラウザのための後方互換性に定義されている仕様の一部でも、ECMAScriptでもオプショナルな仕様になっています。ウェブブラウザの場合は、既にこの機能使ったサイトがあるので実装しないと動かないサイトが出てきますが、HTMLを扱わないJavaScriptエンジンなら不要な仕様です。

- https://tc39.es/ecma262/#sec-html-like-comments

そのため、そもそもとしてHTMLを評価することがないNode.jsやDenoなどはこの仕様を実装してないことがあります。
なので、エラーになる実行環境があるという感じになります。
