### ISSUE TITLE
2016-10-28 ミーティング

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#154]
2016年10月28日のミーティングのアジェンダなどを書く場所です。

**Comment by azu** [comment]
test: doc-testでSyntaxエラーをFailにする #151

**Comment by azu** [comment]
Arrayの草案の草案を書いたやつ http://efcl.info/2016/10/11/array-patterns/

**Comment by laco0416** [comment]
Node.jsのユースケース

バージョンの話

**Comment by laco0416** [comment]
#7

**Comment by azu** [comment]
-----

ここっからログ

**Comment by azu** [comment]
基本は公式サイトからLTSをダウンロードしてインストールしてもらう

**Comment by laco0416** [comment]
https://nodejs.org/ja/ へのリンクを置いてあげる

**Comment by laco0416** [comment]
LTSと最新版があるからLTSを使うんだよという話

```
node --version
```

して6.9を確認させる

**Comment by laco0416** [comment]
local packageとglobal packagesの話 Node特有なのでちゃんと説明しないといけなさそう

**Comment by laco0416** [comment]
Node.js v6? Node v6?

**Comment by azu** [comment]
Nodeだとrequireでどこから読まれるんだっけ?的な話

**Comment by azu** [comment]
Node.jsとNodeという表記

**Comment by laco0416** [comment]
.js側に寄せていく `Node` は `Node.js` に校正できそう

**Comment by azu** [comment]
package.json depsとdevDeps

**Comment by laco0416** [comment]
devDependencies はmochaで使っていく

**Comment by azu** [comment]
- bin
- lib
- (src)
- test

**Comment by azu** [comment]
`index.js` については触れなくてもいい感じ。
欄が余ったらコラム的に触れるとかそういうレベルでよさそう

**Comment by azu** [comment]
TODOでツールを使うケースがあるかもしれないけど、devDepsに入れるのとnpm run-scriptで実行できるぐらいの知識がアレばいい感じ

**Comment by azu** [comment]
配列、Iterableじゃないですね。

**Comment by laco0416** [comment]
Map/Setのissue https://github.com/asciidwango/js-primer/issues/148

**Comment by azu** [comment]
配列とMapとオブジェクトの違いは意識できるようにしたい

**Comment by azu** [comment]
`[][0]` でundefinedが返ってくる減少について

**Comment by laco0416** [comment]
JavaScriptは`IndexOutOfBoundsException` 的な例外が無いので、存在しないindexにもアクセスできるのが他の言語から来ると引っかかるかも

**Comment by azu** [comment]
長さが足りなかったときの対応方法の違い(他の言語と)

**Comment by azu** [comment]
文字列と文字コードの話。どこまでという感じ

**Comment by azu** [comment]
文字列と正規表現の関連

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/21

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/128

**Comment by azu** [comment]
次のミーティング: 11月30日(水曜日) 〜

**Comment by azu** [comment]
@laco0416 https://twitter.com/yosuke_furukawa/status/791983870413459456 とのこと
