### ISSUE TITLE
Map/Set: WeakMapのコード例

### ISSUE THREAD

**Issue by jack77** [asciidwango/js-primer#1555]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/map-and-set/README.md

    eventEmitter.addListener(() => {
        // ここを不通過してるね。サイトのそのままでは。
        console.log("イベントが発火しました");
    },fooListener);

このログを出力させるには、addListener() を次のようにしないと出力されない。
        addListener(func, listener) {
            func();

**Comment by azu** [comment]
もう少し具体的な問題を説明できますか?

**Comment by jack77** [comment]
そうですね。自分は改めてJavascriptを学習しなおしているのですが。
ご指摘のようにWeakMapの概念的な説明なので問題はないように思います。
しかし、自分のように学習初期にいろいろ試しながら進めていない場合は

eventEmitter.addListener(() => {
    console.log("イベントが発火しました");
});
と記述すれば、正しく動作すると誤解を招く可能性があります。
すごく丁寧な解説と実行可能なスクリプトが多数存在するので、その誤解を
を払拭するのは初心者には困難に思われます。

したがって、実行可能なものと概念的な説明で実行不可能なものは分かるよう
にすべきではないでしょうか？
つまらない意見かもしれないですが、今後の参考になればと思っただけです。

**Comment by azu** [comment]
ありがとうございます。

次のようにコメントにするとどうでしょうか?

```js
// イベントリスナーを管理するマップ
const listenersMap = new WeakMap();

class EventEmitter {
    addListener(listener) {
        // this にひもづいたリスナーの配列を取得する
        const listeners = listenersMap.get(this) ?? [];
        const newListeners = listeners.concat(listener);
        // this をキーに新しい配列をセットする
        listenersMap.set(this, newListeners);
    },
    // ... 残りのEventEmitterの実装
}
let eventEmitter = new EventEmitter();
// eventEmitterへイベントリスナーを追加する
eventEmitter.addListener(() => {
    // `eventEmitter`に保持されているイベントリスナーの処理
});
// eventEmitterへの参照がなくなったことで、保持されていたイベントリスナーが自動的に解放される
eventEmitter = null;
```

**Comment by jack77** [comment]
It’ｓa Excellent !!

すごく、いいと思います。
ご丁寧な対応に感謝すると共にますますのご活躍に期待したいと思います。
つまらない、指摘に真摯に向き合っていただき、ありがとうございました。 m( _  _)m
See Ya

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/1618 で修正しました

**Comment by jack77** [comment]
お疲れ様でした。
