### ISSUE TITLE
 for...of文内のGenerator関数の説明削除

### ISSUE THREAD

**Issue by 2nofa11** [asciidwango/js-primer#1559]
## 該当ページ
[ループと反復処理](https://jsprimer.net/basic/loop/#for-of-statement)内の[[ES2015] for...of文内](https://jsprimer.net/basic/loop/#for-of-statement:~:text=iterable%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%81%AFgenerator%E3%81%A8%E5%AF%86%E6%8E%A5%E3%81%AA%E9%96%A2%E4%BF%82%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%81%8C%E3%80%81%E3%81%93%E3%81%93%E3%81%A7%E3%81%AF%E5%8F%8D%E5%BE%A9%E5%87%A6%E7%90%86%E6%99%82%E3%81%AE%E5%8B%95%E4%BD%9C%E3%81%8C%E5%AE%9A%E7%BE%A9%E3%81%95%E3%82%8C%E3%81%9F%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%A8%E8%AA%8D%E8%AD%98%E3%81%97%E3%81%A6%E3%81%84%E3%82%8C%E3%81%B0%E5%95%8F%E9%A1%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82)にgeneratorへの言及について
- [x] 関係するページがあるならばURLを書いてください

### リクエスト
本書で割愛されているGenerator関数に関しての記載の省略  
背景としては第二版のレビュー #1547 を参照
#### 修正前

> iterableについてはgeneratorと密接な関係がありますが、ここでは反復処理時の動作が定義されたオブジェクトと認識していれば問題ありません。
> iterableオブジェクトは反復処理時に次の返す値を定義しています。 それに対して、for...of文では、iterableから値を1つ取り出し、variableに代入して反復処理を行います。

#### 修正案
> iterableオブジェクトは反復処理時の動作が定義されたオブジェクトの総称で、反復処理時に次の返す値を定義しています。
> for...of文では、iterableオブジェクトから次の返す値を1つ取り出し、variableに代入して反復処理を行います。

#### 修正内容
* [ご指摘いただいた説明案](https://github.com/asciidwango/js-primer/discussions/1547#discussioncomment-4818836)の適用
* 次文章と内容が重複部分をまとめる

## 期待する結果
* Generator関数をユースケースに出さない本書の方針にあわせることができる。
* for...of文の習得が節の目的であることを明確できる。

**Comment by azu** [comment]
fixed in https://github.com/asciidwango/js-primer/pull/1560
