### ISSUE TITLE
falsy な値を条件式に指定した場合のプログラム例の改善

### ISSUE THREAD

**Issue by morinokami** [asciidwango/js-primer#1573]
## 該当ページ

- https://jsprimer.net/basic/condition/#if-statement

## リクエスト/提案内容

上記 URL の if 文の節の最後において、falsy な値を条件式に指定した場合のプログラム例として以下が記述されています:

```js
if (false) {
    // この行は実行されません
}
if ("") {
    // この行は実行されません
}
if (0) {
    // この行は実行されません
}
if (undefined) {
    // この行は実行されません
}
if (null) {
    // この行は実行されません
}
```

書籍でこれを読んだ場合は特に問題はないかもしれませんが、ブラウザでこのプログラムを実行したときに、ブロックの中身がコメントのみであるため、条件式が false に変換されて本当に各ブロックが実行されなかったのか、それともコメントしか書かれていないから出力がないのか、厳密には判断できないと思いました。よって、実際にプログラムを実行して、確かに各ブロックが実行されていないことを確認するためには、コメントではなく `console.log("この行は実行されません")` などと記述すべきであると思いました。

実質的にそれほど混乱をきたすことはなさそう、かつウェブ版のみの話であるため、いきなり PR は作成せず、Issue として書くことにしました。（問題がなければ PR を作成しようと思います）

## 期待する結果

プログラムを実行したとき、ブロック内の文が実行されていないと確認できること。

**Comment by azu** [comment]
これは、`console.log`を書くと実行されてしまうと認識する人がいるため、コメントに変更した経緯があります。

- https://github.com/asciidwango/js-primer/blob/ba4de2c8e97462e00b1fbc9cee51744edb468b55/meetings/2019-02-25/README.md#-%E3%81%93%E3%81%AE%E6%96%87%E3%81%AF%E5%AE%9F%E8%A1%8C%E3%81%95%E3%82%8C%E3%81%BE%E3%81%9B%E3%82%93%E3%81%AE%E7%B5%B1%E4%B8%80
- https://github.com/asciidwango/js-primer/issues/1555
