### ISSUE TITLE
謝辞に第二版のレビューアーを追加する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1590]
https://jsprimer.net/intro/#thanks

- ランダムソート
- PRで確認

対象

- https://github.com/asciidwango/js-primer/discussions/1546#discussioncomment-4792571

**Comment by azu** [comment]
WIP

```
- staticWagomU(林　永遠)
- 2nofa11(ツノ)
- keisuke kudo
- haruguchi(池奥 悠馬)
- kakts (阿久津 恵太)
- 藤野慎也 (morinokami)
```

**Comment by azu** [comment]
@nikukyugamer @matobaa @kobakazu0429 謝辞に表記する名前の方いただけますか?

**Comment by nikukyugamer** [comment]
> 謝辞に表記する名前の方いただけますか?
滝谷修

でお願い致します。

**Comment by matobaa** [comment]
すみません、レビュー時間が取れず貢献できておりませんので、表記なしでおねがいできますでしょうか。

**Comment by kobakazu0429** [comment]
@azu 

遅くなって申し訳ないです。下記にてよろしくお願いいたします。

- kobakazu0429 (小畠 一泰)
