### ISSUE TITLE
Travis CI上のNode.jsバージョンが7系になってる

### ISSUE THREAD

**Issue by laco0416** [asciidwango/js-primer#160]
travis.ymlで `stable` にしているので、 7.0.0がインストールされているけど、LTSに固定したほうがいいんじゃないかなーという気がする　どうでしょう？ @azu

**Comment by laco0416** [comment]
参考: http://qiita.com/Linda_pp/items/2f32716d534c97685ab1

**Comment by azu** [comment]
stableとltsにこていかな
