### ISSUE TITLE
「データ型とリテラル」のページにおけるBigIntの表記揺れ修正

### ISSUE THREAD

**Issue by kakts** [asciidwango/js-primer#1609]
## 該当ページ

- https://jsprimer.net/basic/data-type/#bigint-literal

## 説明
BigIntの章における `BigInt` の表記揺れ修正
最後のまとめのところに記載されている文言が`Bigint` となっているので`BigInt`に合わせる

**Comment by azu** [comment]
fixed in https://github.com/asciidwango/js-primer/pull/1610
