### ISSUE TITLE
除算: 0除算の結果がエラーにならず、Inifinityになることの説明追記

### ISSUE THREAD

**Issue by kakts** [asciidwango/js-primer#1616]
## 該当ページ
https://github.com/asciidwango/js-primer/discussions/1547#discussioncomment-5066577

## リクエスト/提案内容

0除算の結果がエラーにならず、Inifinityになることを追記する
https://jsprimer.net/basic/operator/#division-operator
Infinityの説明も軽く追記する

**Comment by azu** [comment]
fixed in  #1623
