### ISSUE TITLE
p44 第6章 数値の表記がページから溢れている

### ISSUE THREAD

**Issue by lacolaco** [asciidwango/js-primer#1630]
この行

https://github.com/asciidwango/js-primer/blob/eed4bcaed0878be25a8f8b2ab89c1eb9a68cb06e/TeX/chap06.tex#L513

**Comment by azu** [comment]
![F1E00D4B-8B1D-4848-A274-300815E0CFC3](https://user-images.githubusercontent.com/19714/223934754-ed3e9a4a-7566-4eb3-93dc-f4fd111676ef.png)

P44
