### ISSUE TITLE
TodoItemView、TodoListViewのJSDocのparamについて

### ISSUE THREAD

**Issue by flyingsc** [asciidwango/js-primer#1657]
## 該当ページ

- <https://jsprimer.net/use-case/todoapp/final/>

## 質問内容
TodoItemViewとTodoListViewのcreateElementではイベントリスナーを引数に取っています。
この部分のJSDocでid:stringとなっていますが、これはid:numberではないでしょうか。

**Comment by azu** [comment]
あー、ほんとですね、`{number}` が正しいと思います。
