### ISSUE TITLE
Publish: npm 8 → npm 9

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1659]
## 該当ページ

Markdownは修正されていた
https://github.com/asciidwango/js-primer/blob/20ce197334898688f22e136d90c97178b12c5e90/source/intro/README.md?plain=1#L197

TeXがnpm 8のままになっている。
https://github.com/asciidwango/js-primer/blob/375ed584593b063cc5a9c9d959b1d1d696a0e2d9/TeX/intro.tex#L226

## 説明

TeXへの反映漏れ。

**Comment by kahei** [comment]
修正しました。
