### ISSUE TITLE
markedjsのアップデート

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1694]
- [Releases · markedjs/marked](https://github.com/markedjs/marked/releases)

ユースケースの章のmarkedとそろそろだいぶ変わってきているのでアップデートする。
Deprecatedなオプションが消えたのでちょうどいいはず

## TODO

- [ ] markedのアップデート
- [ ] [MarkdownをHTMLに変換する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/nodecli/md-to-html/)の変更
- [ ] デフォルトの動作からidが消えているので[ユニットテストを記述する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/)も変更が必要

**Comment by azu** [comment]
marked がバージョン上げすぎてちょっと扱うにくい気がする。

**Comment by azu** [comment]
@SotaYamaguchi さんお願いした。

ちょっとアップデートでどういう変更が必要かが見えてないので、アップデートしてみて文章やテストを変更しないといけない箇所を調べるところからやるのが良いと思います。

📝 ほかの変更と重なってしまう部分があるので、最初か最後にマージしないといけない

- https://github.com/asciidwango/js-primer/issues/1719

**Comment by SotaYamaguchi** [comment]
- markedのバージョンは最新の 12.0.X を使う
- > デフォルトの動作からidが消えているので[ユニットテストを記述する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/)も変更が必要
  - [MarkdownをHTMLに変換する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/nodecli/md-to-html/) のサンプルコードでも修正が必要
- marked側でサニタイズは責務外だから自分でしてねと警告されている。今回は外部ライブラリを用いたCLIアプリケーション作成の理解が目的。HtmlParserを作る際のセキュリティ面の注意喚起は本書では扱わなくてよさそう。
  - > JavaScriptのライブラリやフレームワークの使い方を学ぶのが目的ではない

**Comment by azu** [comment]
他の Node.jsの変更はマージしました #1719

**Comment by azu** [comment]
これそろそろ進める
