### ISSUE TITLE
脱字の報告（「関数とスコープ」）

### ISSUE THREAD

**Issue by sugiwe** [asciidwango/js-primer#1707]
## 該当ページ

- [クロージャー](https://jsprimer.net/basic/function-scope/#closure)

## 説明

> // `myCounter`と`newCounter`は別々の状態持っている

「を」が抜けているのではないかと思いました。
（「別々の状態持っている」→「別々の状態を持っている」）

**Comment by azu** [comment]
ありがとうございます。(メールの通知が来てなくて気づくの遅れました9
