### ISSUE TITLE
ES2022: Error Cause

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1714]
- https://github.com/asciidwango/js-primer/issues/1337#issuecomment-1000668450_

ここで対応しないとしていたけど、再検討する。

具体的には次の場所では、Error causeを使った方が明らかに良いので、ここで使えるように基礎文法で紹介したい。

```js
function main() {
    fetchUserInfo("js-primer-example")
        .catch((error) => {
            // Promiseチェーンの中で発生したエラーを受け取る
            console.error(`エラーが発生しました (${error})`);
        });
}
```

[Promiseを活用する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/ajaxapp/promise/#error-handling)        

## TODO

- [ ] [例外処理 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/error-try-catch/)にError Causeを入れる
- [ ] [Promiseを活用する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/ajaxapp/promise/#error-handling) などでError Causeを使う

課題として、Error Causeの効果(スタックトレースの話とか)をどうやって表現するかという問題がありそう

**Comment by azu** [comment]
他にも文中にこういうケースがないかは見つけないといけない。
非同期 or try-catchぐらいだと思うので、ないような気もしているけどどうだろ?

**Comment by azu** [comment]
@himanoa さんに担当してもらう。

入れること自体([例外処理](https://jsprimer.net/basic/error-try-catch/)での説明と[Promiseを活用する](https://jsprimer.net/use-case/ajaxapp/promise/#error-handling)などでの利用)は多分そこまで難しくないのですが、
[例外処理](https://jsprimer.net/basic/error-try-catch/)で、スタックトレースの説明が最後になってるので、
スタックトレースの説明してからじゃないとError Causeを説明できない気がしていて、説明の順番どうしようというのがちょっと悩みどこになってます。

**Comment by himanoa** [comment]
@azu 
説明ありがとうございます！

[例外処理](https://jsprimer.net/basic/error-try-catch/)の最後に `Error Cause[^E2022]` のセクションを追加して、re-throwした時にスタックトレースを維持するための説明を書く方針で進めようとおもいます！

**Comment by azu** [comment]
- https://github.com/mochajs/mocha/pull/4829

Error Causeの表示を対応してる例
