### ISSUE TITLE
ES2024: Object.groupBy/Map.groupBy

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1716]
## [tc39/proposal-array-grouping: A proposal to make grouping of array items easier](https://github.com/tc39/proposal-array-grouping)

Web互換性のために`Object.groupBy`になった。
`Map.groupBy(array, fn)`もある。

グループ化は頻出ではあるので含めるのは妥当そうだけど、配置が難しい

- `Array.prototype.group` → `Object.groupBy(array, cb)`
- `Array.prototype.groupToMap` → `Map.groupBy(array, cb)` 

という経緯。
どちらも配列を引数として受け取るようになってるので、配列関係。

データの変換的に見れば

- `Object.groupBy` は 配列をオブジェクトにするメソッド
- `Map.groupBy` は配列をMapにするメソッド

として捉えられる。

`Object.groupBy`は、 配列 to objectなので、[Array.prototype.reduce ](https://jsprimer.net/basic/array/#array-reduce)の近くにあるのが良さそう。
`Map.groupBy`は、[Map/Set](https://jsprimer.net/basic/map-and-set/)にあるのが良さそう。
`Map.groupBy`はちょっと必要かは怪しい。

## TODO

- [x] `Object.groupBy`: 配列の章に追加する
- [x] `Map.groupBy` は Map/Setの章に追加する?

_Originally posted by @azu in https://github.com/asciidwango/js-primer/issues/1706#issuecomment-1936870421_

**Comment by azu** [comment]
@koralle 配列の章とMap/Setの章は別々のPRとして進めるのが良いと思います。(Assignするためにmentionしちゃいました)

**Comment by azu** [comment]
- ユースケース/モチベーションの整理
- exampleを考える
- ユースケースの章でgroupByを使うべき場所がないかを確認する
- 文章として追加する

作業としては毎回こういうイメージのことをやっています。

ちょっと考えるところとしては、Web互換性のためにStatic Methodになってるというのを説明するべきかどうかという点ぐらいなのかなとは思います。(多分冗長になるので不要になりそうな気はしています)

- [Why static methods?](https://github.com/tc39/proposal-array-grouping?tab=readme-ov-file#why-static-methods)

参考

- https://github.com/asciidwango/js-primer/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Lang%3A+ES2022%22+
- https://github.com/asciidwango/js-primer/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Lang%3A+ES2021%22
- https://github.com/asciidwango/js-primer/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Lang%3A+ES2020%22

**Comment by koralle** [comment]
@azu 
ありがとうございます。

**Comment by azu** [comment]
- #1749 

配列の方を追加しました。
Mapの方がまだあるので、re-open

**Comment by azu** [comment]
Mapの方もiterateの流れで入れるのが正しそう。
https://jsprimer.net/basic/map-and-set/#map-iteration

**Comment by azu** [comment]
Mapを読んでいてショッピングカートの例がちょっと冗長な感じがしたので別のissueを作りました

- https://github.com/asciidwango/js-primer/issues/1750

**Comment by azu** [comment]
- #1749 
- #1751 

それぞれ追加したのでcloseします。
