### ISSUE TITLE
mochaを `node:test` に変更する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1717]
Node.js 20 から `node:test` が利用できるようになった。
そのため[ユニットテストを記述する](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/)でMochaをあえて使う理由がなくなったため、`node:test`に置き換えたい。

## TODO

- [x] #1718 に依存している
- [ ] ~~#1698 に依存している~~
- [x] [ユニットテストを記述する ](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/)をMochaから `node:test` へ変更する

_Originally posted by @azu in https://github.com/asciidwango/js-primer/issues/1698#issuecomment-1935345984_

**Comment by windchime-yk** [comment]
@azu 
まとめてくださり、ありがとうございます！
文章の変更だけ先に行なって、利用法の追記が終わり次第に実装側の修正も行おうと思います！

**Comment by windchime-yk** [comment]
@azu 
お疲れ様です！
こちらのIssueにつきまして、[ユニットテストを記述する](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/)の修正が終わったためTODOすべて完了した認識なのですが、残っているタスクはございますか？
残っているものあれば着手しようかと思い、お送りした次第です！

**Comment by azu** [comment]
このIssueは閉じて大丈夫だと思います！
