### ISSUE TITLE
data-type/#文字列（string）: "全く同じ意味"

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#172]
https://asciidwango.github.io/js-primer/basic/data-type/#%E6%96%87%E5%AD%97%E5%88%97%EF%BC%88string%EF%BC%89

"全く" なのに 否定じゃないのは気になる

**Comment by laco0416** [comment]
個人的には気にならないですね `全く` は肯定でも使えるはず

1328509_03.pdf (文科省の資料) http://www.mext.go.jp/b_menu/shingi/chukyo/chukyo3/047/siryo/__icsFiles/afieldfile/2012/12/07/1328509_03.pdf
`全くそうだと思う`

**Comment by azu** [comment]
肯定でも使えるとは思いますが、文章だと `全く同じ` ってくどい印象があるんですよね。

- https://github.com/btford/write-good#toowordy
- https://github.com/duereg/too-wordy

英語のLintで過度な表現は不要なら省くべき みたいな指摘を受けたのもそう感じるようになった原因かも。この場合は `全く` 自体はなくても通じるとは思いますがどうですかね?

**Comment by laco0416** [comment]
```
"（ダブルクオート）と'（シングルクオート）は全く同じ意味となります。 PHPやRubyなどとは違い、どちらのリテラルでも評価結果は全く同じとなります。
```

どちらか1回だけでよさそう。2回使われているのはたしかにくどい気がする
