### ISSUE TITLE
npm initとcommonjsの件を「コマンドライン引数を処理する」から「Node.jsでHello World」に移動する

### ISSUE THREAD

**Issue by yossydev** [asciidwango/js-primer#1731]
```
- [ ] mpm initとcommonjsの件を [コマンドライン引数を処理する](https://jsprimer.net/use-case/nodecli/argument-parse/) → [Node.jsでHello World](https://jsprimer.net/use-case/nodecli/helloworld/) に移動する
  - プロジェクトのセットアップの話としてnpm initする
```

## 関連
- https://github.com/asciidwango/js-primer/discussions/1727#discussioncomment-8872964
- https://github.com/asciidwango/js-primer/issues/1698#issue-1977703276

**Comment by azu** [comment]
こちらはページ間の移動間をやめて、"ECMAScriptモジュールを使う"の中にまとめた方が自然な気がしたので、
https://github.com/asciidwango/js-primer/issues/1698 にマージしました。

- [ ] `mpm init` の話を[コマンドライン引数を処理する](https://jsprimer.net/use-case/nodecli/argument-parse/) → [ECMAScriptモジュールを使う](https://jsprimer.net/use-case/nodecli/argument-parse/#esmodule)の中に移動する
- [ ] [commanderパッケージをインストールする ](https://jsprimer.net/use-case/nodecli/argument-parse/#install-commander)を削除する

これなら、commonjsの話はそのままの位置で済むはず。
