### ISSUE TITLE
REPLエディタがError Causeに対応していない

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1735]
https://jsprimer.net/basic/error-try-catch/#error-cause を実行するCauseも自動で表示されてほしい

![image](https://github.com/asciidwango/js-primer/assets/19714/716c8159-4c2a-4cce-83fb-bdbc1c8000ec)

https://github.com/azu/codemirror-console/blob/323c5acccd660164de27a50b871e2cc56bc057df/packages/codemirror-console-ui/components/mirror-console-component.js#L69-L70

おそらくこの辺で `.cause` をformatするような仕組みが必要になる

**Comment by himanoa** [comment]
https://github.com/azu/codemirror-console/pull/23 こっち側にPull-Request立ててみました

**Comment by azu** [comment]
https://github.com/azu/codemirror-console/releases/tag/v3.2.0
でリリースしました
