### ISSUE TITLE
ループと反復処理

### ISSUE THREAD

**Issue by vb-tsukakoshi** [asciidwango/js-primer#1741]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/loop/README.md

はじめまして、いつもこちら利用し学習させていただいております。
引数の表記が誤っているのではないかと思い、ご連絡です。

内容としては、「もちろん、次のようにcontinue文を使わずに「偶数ならresultsへ追加する」という書き方も可能です。」の以下に続くコードについて現在のコードでは引数が異なるためかうまく動作しませんでした。

初学者ゆえ、当方の書き損じや誤認識もあるかも知れませんが、ご確認いただければ幸いです。

現在
`
if (isEven(number)) {
    results.push(number);
}
`
修正案
`
  if(isEven(num)) {
      results.push(num);
  }
`

**Comment by azu** [comment]
ありがとうございます！
`num` とするのが正しいので、#1742 で修正しました。

以前、 https://github.com/asciidwango/js-primer/pull/829 で サンプルコードをまとめて `number` → `num` に変更したときに、漏れていたようです。ご報告ありがとうございます！
