### ISSUE TITLE
markdownファイルをソースコードに含められない

### ISSUE THREAD

**Issue by laco0416** [asciidwango/js-primer#185]
front-matter-testで `source` 以下の `*.md`ファイルがすべて原稿としてチェックされているので、nodecliのサンプルの中で`sample.md`を作れない

サンプルコードはだいたい`src`以下だから、 `!${sourceDir}/**/src{,/**}` を除外する？

@azu

**Comment by azu** [comment]
src除外か特定のファイル無視か どっちでもいいと思う

**Comment by laco0416** [comment]
そんなにたくさん発生するケースじゃないし特定のファイル指定にします
