### ISSUE TITLE
関数宣言、関数式、Arrow Function

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#20]
#17 基本文法
#112 関数のうち "関数宣言" について
- [ ] function declaration
- [ ] function expression
- [ ] Arrow function
- その他
  - 関数宣言
    - 関数宣言はセミコロンがいらない
    - セミコロンは文を区切るための構文
    - 関数宣言自体は文で終わっているワケではないため
  - 関数式
    - 関数は値である
    - ファーストクラスである関数
    - const fn = function(){}ができる
  - Arrow Function
    - 関数式の現代版といえるもの
    - 関数式を利用する場合は多くのケースでこちらを使ったほうが良い
    - this(see スコープ)の問題などがおきにくいため
    - また、Arrow Functionに名前を付けるにはletやconstを使わないと行けない。
    - そのためvarはやっぱりダメ
    - 短く誤解がない表現なので、function式よりはArrow Functionを使いましょう
  - メソッド
    - ES2015まではメソッドはただの関数が値として入ってるプロパティの事だった(定義は今も同じ)
    - JavaScriptのメソッドは var obj = { method(){} } で定義できる
    - `var obj = { method : function(){} }` と書くこともできるがこれは関数式と同じ
    - なので現在的にはメソッド定義をする方法はメソッド定義の記法でやる

**Comment by azu** [comment]
ASI 自動セミコロン挿入については関数宣言がでてきたら話す必要がある。
どういう時にセミコロンがいるのか、いらないのかは何かなれるまで分からない感じがする。
逆にどういうとセミコロンのありなしの区別ができるのか調べる必要がある。

ステートメントは必要で、宣言は不要という認識だったけど

>   Most ECMAScript statements must be terminated with semicolons.
> ....
> Because the convention for C-like languages is that the elements of a statement list (statements and declarations) each terminate with a semicolon unless their last token is a } such as FunctionDeclaration and Block (or if the syntactic tail of the statement is another statement). ES6 applied the same convention to ClassElementList. 

https://github.com/tc39/ecma262/pull/341

これを一言で説明して理解できる文章が必要

**Comment by azu** [comment]
Arrow Functionは式しかなれない関数という言える?

**Comment by azu** [comment]
関数の種類ってどういう分類になるんだろ?
ES5以下では一つの関数の書き方の違いと言えたけど、今は明確使える機能が違ったりするから結構種類がありそうな気がするけど、どういう分類になるんだろ?

`[[Construct]]` と `[[Callable]]]` があるかという組み合わせなのかな?

- new && Callable -  function declaration, expression, constructor function
- Callable - shorthand method, Generator
- New - class
- super - class, shorthand method

**Comment by azu** [comment]
話の流れ的に次のような形にするとすっきりするかも。

- JavaScriptの関数宣言は `function` でおこなえる
- JavaScriptの関数は値として利用できるので `const fn = function(){}` function式が使える
- JavaScriptの関数式としてfunction式とArrow Functionがある
- 短く誤解がない表現なので、function式よりはArrow Functionを使いましょう
- JavaScriptのメソッドは `var obj = { method(){} }` で定義できる
- 先ほども書いたようにJavaScriptで関数は値なので、var obj = { method : function(){} }` と書くこともできる

**Comment by azu** [comment]
http://www.ecma-international.org/ecma-262/7.0/#sec-function-definitions
"関数宣言" と呼ぶのがいいのかなー。
関数宣言文だとStatementっぽくてセミコロンが不要となる話がよくわからない

**Comment by azu** [comment]
[JavaScript ／ function文でセミコロン - スタック・オーバーフロー](http://ja.stackoverflow.com/questions/8189/javascript-function%E6%96%87%E3%81%A7%E3%82%BB%E3%83%9F%E3%82%B3%E3%83%AD%E3%83%B3 "JavaScript ／ function文でセミコロン - スタック・オーバーフロー")

**Comment by yumetodo** [comment]
関数とはなにか？という議論がjQueryのIssueで出てきている。``JQuery.isFunction``とpromiseとGenerator Functionと実行可能なDOMを巡って。

- https://github.com/jquery/jquery/issues/3596 : Deferred: behavior different from ECMAScript Promise for objects with [[Call]]
- https://github.com/jquery/jquery/pull/3601 : Core: use instanceof and typeof instead of jQuery.type in jQuery.isFunction
- https://github.com/jquery/jquery/issues/3609 : Deprecate jQuery.isFunction
- https://github.com/jquery/jquery/issues/3610 : Internal API succeeding to jQuery.isFunction

**Comment by akihikodaki** [comment]
そのissueを立てた張本人です. リファレンスが飛んでいた見てみましたが, 気づいたことがあるので報告させていただきます. 全て _ECMAScript 2016 Language Specification_ を斜め読みした結果に沿っています.

> [[Construct]] と [[Callable]]] があるかという組み合わせなのかな?
>
> * new && Callable - function declaration, expression, constructor function
> * Callable - shorthand method, Generator
> * New - class
> * super - class, shorthand method

[関数は`[[Call]]`内部スロットを持つ全てのオブジェクトであり](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-terms-and-definitions-function), `[[Construct]]`を持っているかに依りません. つまり, constructorであっても関数ではないオブジェクトというのはありえるように読めます.
しかしECMAScriptで定義されているconstructorは関数です. [クラス定義に依るクラスは`[[FunctionKind]]`内部スロットが`classConstructor`であり](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-makeclassconstructor), [呼び出す際にはこれを確認して例外を投げることになっています](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-ecmascript-function-objects-call-thisargument-argumentslist). また, 呼べないビルトイン関数は実際には呼ばれると例外を投げる関数として定義されています.

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/20#issuecomment-235758247 の元ネタはたしか
http://exploringjs.com/es6/ch_callables.html#_cheat-sheet-callable-entities あたりですね。

ECMAScriptの仕様上の関数の定義は基本的に後付な部分が多いので、そこに直感的に理解できる一貫性があるわけではないですよね。そこが説明する上で問題なんですよね。

関数であっても(`[[Call]]`を持っていても)、Callableとは限らないというのがやっかいですね。
これを上手く説明する方法が難しいなーと思っています。(仕様上の挙動は決っているけど、普通はそこまで読まないとは思うので)

- [ljharb/is-callable: Is this JS value callable? Works with Functions and GeneratorFunctions, despite ES6 @@toStringTag.](https://github.com/ljharb/is-callable "ljharb/is-callable: Is this JS value callable? Works with Functions and GeneratorFunctions, despite ES6 @@toStringTag.")

「Aは関数です。」これ以上の説明しようとした場合に、一般的なユーザーが知る必要がない内部プロパティについて言及しないと説明できなくなってしまうという問題がやっかいだなーと思ってメモってました。(Arrow Functionで定義したものも関数ですが、これは`new`で呼び出すことはできませんとかなってしまう)

そういえば以前Callable ConstructorのProposalがあったのを思い出しました(これは却下された)

- [Status of callable class constructors proposal · Issue #470 · tc39/ecma262](https://github.com/tc39/ecma262/issues/470)
- [ecma262/callconstructor.md at master · tc39/ecma262](https://github.com/tc39/ecma262/blob/master/workingdocs/callconstructor.md)
- [tc39-notes/sept-24.md at master · rwaldron/tc39-notes](https://github.com/rwaldron/tc39-notes/blob/master/es7/2015-09/sept-24.md#56-proposal-call-constructor)

**Comment by azu** [comment]
(jQueryのissueちゃんと見てないですが、関数かを判定したいという用途なら `typeof x === "function"` する以外の結論にはならない気はします。classを除きたいとかなどは「Callableな関数かを判定する」みたいな異なる意味合いが"関数"という言葉に混ざってしまっている印象)

**Comment by akihikodaki** [comment]
確かに関数という枠組みの中での一貫性は感じられません. 「関数」としてまとめてしまうのではなく、関数の定義の仕方によって個別にその特徴を記述するのが妥当なように思えます. 例えば, 「呼べる関数を作るアロー関数」「呼ぶと例外になってしまうがconstructorとして使えるクラス定義」「呼ぶのにもconstructorとするのにも使える関数定義」といったようにです.

jQueryのissueではDOMの`applet`, `embed`, `object`要素が関数でもあることが問題視されています. jQuery内では「渡された値が関数でなければそれをそのまま用いる、関数であればその関数を呼んで戻り値を用いる」というコードが多用されており, 関数そのものが値として用いられることを想定していないのです. 実際には関数もオブジェクトなのでその前提は往々にして成り立ちません.

**Comment by yumetodo** [comment]
https://github.com/jquery/jquery/pull/3617
どうやら``typeof obj === "function" && typeof obj.nodeType !== "number"``という、DOM Elementを除くfunctionを関数と定義する動きがある

**Comment by azu** [comment]
[The Many Faces of Functions in JavaScript - Bocoup](https://bocoup.com/blog/the-many-faces-of-functions-in-javascript "The Many Faces of Functions in JavaScript - Bocoup")

**Comment by azu** [comment]
[JavaScript のもう一つの「関数名」 —— name プロパティ - Qiita](http://qiita.com/8x9/items/34272b59b5aa68e33256 "JavaScript のもう一つの「関数名」 —— name プロパティ - Qiita")
Function.nameについて
"Inferred function names" って呼び方初めて聞いたなー
後は仕様外だとdisplayNameとかかな

**Comment by azu** [comment]
closed by #112  #119
