### ISSUE TITLE
string: 文字結合とコンテキスト

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#203]
文字結合は単なる+しゃなくてUrlやpathと言ったコンテキストに基づいた結合をした方が良い話を書く

コラム的な位置づけ。

Pathはnodeの話、urlはajaxの話で出てきてるのでそれの前触れ的なもの。

後pathはクロスプラットフォームを意識する場所なので書いておくと良さそう

**Comment by yumetodo** [comment]
参考までに、

- VSCodeのURI周りの実装  
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts
- RFC 3986 - Uniform Resource Identifier (URI): Generic Syntax  
https://tools.ietf.org/html/rfc3986
- 先日TLで観測したURIとshemeがごっちゃになった例
https://twitter.com/croce1/status/843045776037048320
