### ISSUE TITLE
2017-03-24 ミーティング

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#209]
アジェンダ置き場

**Comment by azu** [comment]
#121 StringのTagged Template Literalのサンプルどうするか

候補

- i18n + 複数形 
  - [i18n with tagged template literals in ECMAScript 2015 — Jack Hsu](https://jaysoo.ca/2014/03/20/i18n-with-es2015-template-literals/)
  - [Introduction · c-3po javascript es6 localization tool](https://c-3po.js.org/)
- HTMLエスケープ
  - ajaxでやってるやつ
- [declandewet/common-tags: Useful template literal tags for dealing with strings in ES2015+](https://github.com/declandewet/common-tags "declandewet/common-tags: Useful template literal tags for dealing with strings in ES2015+")

**Comment by azu** [comment]
console.logと// => の使い分け #195 

```js
console.log(a); // => x
a; // => x
```

https://github.com/asciidwango/js-primer/issues/195

**Comment by azu** [comment]
ラベル管理について

色々カテゴリ別に追加した。
(多分使わないのがあると思うのでいらないのは消して良さそう)

- [Labels · asciidwango/js-primer](https://github.com/asciidwango/js-primer/labels "Labels · asciidwango/js-primer")

議論で方針が決まったIssueは`Status: Ready for PR`をつけるか閉じるかしていきたい。

- [Status: Ready for PR](https://github.com/asciidwango/js-primer/labels/Status%3A%20Ready%20for%20PR "Issues · asciidwango/js-primer")
  -

**Comment by azu** [comment]
ここからログ

----

**Comment by azu** [comment]
`encodeURIComponent()` + template literalでURLのパス?

**Comment by laco0416** [comment]
```js
const tagName = "空白が 混ざった 文字列";

path`/tags/${tagName}`
```

**Comment by azu** [comment]
APIのパス組み立ての例をtagged templateで簡単に紹介。

**Comment by laco0416** [comment]
```
`https://${apiHost}/${path}`
```

**Comment by azu** [comment]
#214 Issueを作った

**Comment by azu** [comment]
> console.logと// => の使い分け #195

について。
ウェブだとあった方が便利。だけど書籍だと醜そう。

**Comment by azu** [comment]
場合によって分けるとかで良い気がする。

`console.log(a); // => aの結果` がconsole.logの結果が右側っぽく見える

**Comment by azu** [comment]
Node.だと`console.log({}) ; [Object object]` なので意味が異なる可能性がある。

**Comment by azu** [comment]
node -v
v7.2.0
```
> console.log({s:1})
{ s: 1 }
undefined
> console.log({s:1})
> var object = { a : {} }
undefined
> console.log(object)
{ a: {} }
undefined
> var object = { a : { b : 1} }
undefined
> console.log(object)
{ a: { b: 1 } }
undefined
> var object = { a : { b : 33  } }
```

**Comment by azu** [comment]
コメントのところに評価コメントの書式についてをちゃんと説明を書く。
不要なところについてはconsole.logは省いても良い。

**Comment by azu** [comment]
Issue化 https://github.com/asciidwango/js-primer/issues/215

**Comment by azu** [comment]
ラベルの管理方法についてを説明

https://github.com/asciidwango/js-primer/labels/Status%3A%20Ready%20for%20PR は議論済みでコミットできる状態のissue

**Comment by laco0416** [comment]
https://github.com/asciidwango/js-primer/pull/202/files/246a42967bfa5dc4f6724639927ae1bbe313504e#diff-e17432ce26c5c47f53bf2a852cf2f57a

**Comment by azu** [comment]
`console.error(error.message, error.stack)`

**Comment by azu** [comment]
エラーの出し方

**Comment by azu** [comment]
`console.error(error)`に揃える。

**Comment by azu** [comment]
string: 「文字列」「部分文字列」「検索文字列」 #208

**Comment by azu** [comment]
先人の知恵を頼ろう。

**Comment by azu** [comment]
正規表現は文字列の章に混ぜた。

**Comment by laco0416** [comment]
Rest https://github.com/asciidwango/js-primer/blob/master/source/basic/function-method/README.md#rest-parameters

**Comment by azu** [comment]
目次のカバレッジの話

**Comment by azu** [comment]
https://github.com/js-joda/js-joda

**Comment by azu** [comment]
手が空いたらビルトインオブジェクトに手を付ける?

**Comment by laco0416** [comment]
nodecliの次はJSON辺りから手を付ける

**Comment by laco0416** [comment]
目次整理

**Comment by azu** [comment]
[徹底マスター JavaScriptの教科書　プログラミングの教養から、言語仕様、開発技法までが正しく身につく | 磯 博 | インターネット・Web開発 | Kindleストア | Amazon](https://www.amazon.co.jp/dp/B06XNQCW7B/ "徹底マスター JavaScriptの教科書　プログラミングの教養から、言語仕様、開発技法までが正しく身につく | 磯 博 | インターネット・Web開発 | Kindleストア | Amazon")

**Comment by laco0416** [comment]
- PromiseはErrorのつづき

とか書いとかないと忘れる

**Comment by azu** [comment]
http://www.sbcr.jp/products/4797388640.html

**Comment by azu** [comment]
目次 http://blog.livedoor.jp/dan4423/archives/5191202.html

**Comment by azu** [comment]
次回: 5月26日(金曜日)

**Comment by azu** [comment]
[Screen Object](https://www.w3schools.com/jsref/obj_screen.asp "Screen Object") こんなのあるんだ
