### ISSUE TITLE
String: 構造的文字列 -> ???

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#228]
#121 構造的文字列はやっぱり「コンテキスト（文脈）のある文字列」にするか。

- 「ファイルパスというコンテキストのある文字列」
- 「URLというコンテキストのある文字列」

**Comment by azu** [comment]
コンテキストという言葉はスコープでも使う可能性があるのか。

**Comment by yumetodo** [comment]
#255 で構造的な文字列としたんでしたっけ。

**Comment by azu** [comment]
@yumetodo そうですね。 #225では"構造的な文字"にしてると思います。
#227 の方だとコンテキストと書いてるので、統一する必要があります。

**Comment by azu** [comment]
#208
