### ISSUE TITLE
JSONの章

### ISSUE THREAD

**Issue by laco0416** [asciidwango/js-primer#237]
- JSONとは
- APIの説明

**Comment by laco0416** [comment]
parseとstringifyはtry-catchしようねって話

**Comment by laco0416** [comment]
application/json

**Comment by yumetodo** [comment]
JSON5とかってどうなります？

**Comment by azu** [comment]
> JSON5とかってどうなります？

JSON5は星の数ほどあるJSONの独自拡張に過ぎないので、特になにもない気がします。
JSONはJavaScriptよりSyntaxが厳密なので、それを緩くしたい例としてJSON5などがありますというのを書くのが精一杯だと思います。
が、実際のユースケースに紐付いてないとその必要性はわかりにくく、JSONを理解する上では余計な情報に思えるので、JSONの章としては特にでてこないんじゃななと思います。

**Comment by laco0416** [comment]
parseのreceiver引数は触れるか触れないかって感じする

**Comment by laco0416** [comment]
`{{book.console}}`が改行を含む文字列の出力に対応してないのでstringifyのspace引数が試せない cc/ @azu
