### ISSUE TITLE
Map/Setの章

### ISSUE THREAD

**Issue by laco0416** [asciidwango/js-primer#238]
Map/WeakMap/Set/WeakSetについて

- 概要
- 例

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/148 過去にメモってた。
こっちに移して閉じるか

**Comment by azu** [comment]
[ES6 — set, map, weak – ECMAScript 2015 – Medium](https://medium.com/ecmascript-2015/es6-set-map-weak-a2aeb7e2d384 "ES6 — set, map, weak – ECMAScript 2015 – Medium")

よくあるMap/Set解説。単なるAPI解説っぽい
