### ISSUE TITLE
prototype/ブロックスコープ/クロージャー

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#24]
基本文法 #17 

これやっかいな概念で2-3箇所にまたがったものになってる。
- ブロックスコープの機能 - 定義は #31 の手前で
- 変数宣言 #15 
- 関数宣言 #20 (これは宣言についてのみ)
- for + let
- hoisting
- TDZ

これだけで一つのまとまりとして振り返る形でやったほうが理解がし易い(スコープってどこに書いてあったけ? みたいなときに、この辺かというまとまりが見える)ような気がする

この節では、JavaScriptのFunctiuonコンストラクタ的な話。
#20 関数宣言では、宣言方法、呼び方、値の返し方について学ぶ。

ここでは、 #20 では解説してない、スコープやクロージャーなどの挙動的な動作が中心になる。

---

[Let’s Learn JavaScript Closures — Free Code Camp](https://medium.freecodecamp.com/lets-learn-javascript-closures-66feb44f6a44#.hfps3d9t6)
この記事、クロージャーとArrow Functionを理解するのにすごくよく書けてる

**Comment by laco0416** [comment]
`addEventListener` あたりがプチユースケースになりそう

**Comment by azu** [comment]
📝  #31 #69 switchの話として、関数と組み合わせて(つまり抽象化)扱うものというリンクを貼った

**Comment by azu** [comment]
これを専門に扱った薄い電子書籍があった。
無料から購入できる

- [JavaScript Functions… by Amin Meyghani [PDF/iPad/Kindle]](https://leanpub.com/javascript-closure "JavaScript Functions… by Amin Meyghani [PDF/iPad/Kindle]")

**Comment by azu** [comment]
[関数の話 // Speaker Deck](https://speakerdeck.com/yuroyoro/guan-shu-falsehua "関数の話 // Speaker Deck")

関数、クロージャー、ファーストクラスあたりの用語

**Comment by azu** [comment]
#277 スコープという分類にまとめることにしたので、このissueは #277 にうつして閉じる
