### ISSUE TITLE
初期化か代入か

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#261]
# 要約

```js
var a;
a = 3;
```

が代入なのは疑いないのですが、

```js
var b = 3;
```

これも代入なのでしょうか？

# 詳細

>§ 12.2.6 [Object Initializer](https://tc39.github.io/ecma262/#sec-object-initializer)
>*Initializer*[In, Yield, Await] :
>= *AssignmentExpression*[?In, ?Yield, ?Await]
>
>§ 13.3.2 [Variable Statement](https://tc39.github.io/ecma262/#sec-variable-statement)
>
>*VariableStatement*[Yield, Await] :
>var *VariableDeclarationList*[+In, ?Yield, ?Await] ;
>
>*VariableDeclarationList*[In, Yield, Await] :
>*VariableDeclaration*[?In, ?Yield, ?Await]
>*VariableDeclarationList*[?In, ?Yield, ?Await] , *VariableDeclaration*[?In, ?Yield, ?Await]
>
>*VariableDeclaration*[In, Yield, Await] :
>*BindingIdentifier*[?Yield, ?Await] *Initializer*[?In, ?Yield, ?Await] <sub>opt</sub>
>*BindingPattern*[?Yield, ?Await] *Initializer*[?In, ?Yield, ?Await]

と定義されているので

```js
var b = 3;
```

の

```js
= 3
```

は`Initializer`であり、代入ではなく初期化なのではないか？

# 影響

>https://asciidwango.github.io/js-primer/basic/variables/
>変数宣言と同時に初期値を代入することもできます。 次の例では、`bookTitle`という変数を宣言し、`"JavaScriptの本"` という文字列を代入しています。
<blockquote>

```js
var bookTitle = "JavaScriptの本";
```

</blockquote>

では代入として紹介しています。

# 参照
- #15 
- #28
- https://github.com/asciidwango/js-primer/pull/256#discussion_r128002912

**Comment by azu** [comment]
@yumetodo ありがとうございます。

Initializerは[初期化子](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Object_initializer "初期化子")みたいな話だと思うので、"初期化"にするかは別のところなのかと思います。仕様的な正しさを用語まで追求すると代入もbindingみたいな話になってくるので、そこよりは直感的な理解のしやすさを優先したいですね。
あと前提 https://asciidwango.github.io/js-primer/intro/goal/ に仕様を厳密になぞるのが目的ではないという趣旨書き忘れてたので追記しておきます。

![image](https://user-images.githubusercontent.com/19714/28328455-98a72966-6c21-11e7-80b4-c874aa0ece2f.png)
- https://tc39.github.io/ecma262/#_ref_9607

Initializerを評価した結果の値をPutするなので、"初期値を代入"でも理解はできるかなとは思います。

今このIssueを読んだ感じだと "初期化" という用語をそもそも定義してなかったので、"初期値を代入"という言葉を使っているんだなと思いました。("初期化"という言葉は、JavaScriptみたいな動的なものだと後から空の配列を代入するのも初期化とか言われてることがあるので避けたいなという気持ちがでてきました。)

しかし、前文で初期化という言葉使ってるんですね。。

> デフォルト値としてundefinedで初期化されます。

JavaScriptにおいて明確に"初期化"と"初期値を代入"(初期値として代入?)に論理的な違いが出てくる部分があるなら、それに併せて直すのがいいかなと思います。

用語の表記揺れは修正したいですね。

**Comment by yumetodo** [comment]
>Initializerは初期化子みたいな話だと思うので、"初期化"にするかは別のところなのかと思います。

ええっと「初期化子」は「初期化するもの」なので、代入**式**を使うが初期化ではないかと思うのですが・・・？

>https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer
>Objects **can be initialized** using new Object(), Object.create(), or using the literal notation (initializer notation). An object initializer is a comma-delimited list of zero or more pairs of property names and associated values of an object, enclosed in curly braces ({}).

**Comment by azu** [comment]
"初期化"という言葉が分かりやすいかどうかの話ですね(仕様的な話じゃないです)

```js
var array = [1,2,3];
// これを初期化と言ってる人もいる
array = []
```

用語をあんまり増やしたくないので、文章としてはどうするかという話でした。

Issueの答えとしては初期化でいいじゃないでしょうか。

**Comment by yumetodo** [comment]
すると

>変数宣言と同時に初期値を代入することもできます。 次の例では、`bookTitle`という変数を宣言し、`"JavaScriptの本" という文字列を代入しています。`

や

```js
 var myArray = ["A", "B", "C"];
// `myArray`の参照を代入している
```

はどうしましょうか？

**Comment by azu** [comment]
最初にこの本における初期化の定義が説明できていれば、初期化で良いと思います。

宣言と共に初期値を代入、つまりxという変数をyという値で初期化しています。

みたいな。この言い回しをもう少しスムーズにしたい感じですね。
