### ISSUE TITLE
2017-07-21 MTGアジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#263]
2017年7月21日のミーティングアジェンダを書く場所

**Comment by laco0416** [comment]
#237 #259 
`JSON.stringify` の例外と、 `JSON.parse` の第2引数に触れるかどうか
使うユースケースあんまりないと思うんだけど、リファレンス的に触れるか流すかの判断

**Comment by azu** [comment]
配列 #49 はあと少し。

次は 関数をやる予定 https://github.com/asciidwango/js-primer/issues/112

**Comment by azu** [comment]
typoとか見つけたら簡単にIssue切れます。

![image](https://user-images.githubusercontent.com/19714/28459316-e68295ee-6e47-11e7-9ad2-1cc4e9e4f2aa.png)
[書いた文章をレビューしてGitHubにIssueを切るためのGitBookプラグイン | Web Scratch](http://efcl.info/2017/05/29/gitbook-plugin-github-issue-for-review/ "書いた文章をレビューしてGitHubにIssueを切るためのGitBookプラグイン | Web Scratch")

**Comment by azu** [comment]
> JSON

JSONの章でどこまで扱うかについて。

**Comment by azu** [comment]
- プリミティブ か オブジェクト
- オブジェクトのうち 列挙可能?で分類

**Comment by laco0416** [comment]
- プリミティブかどうか
- オブジェクトかどうか
  - 列挙可能なプロパティを再帰的にシリアライズ

**Comment by azu** [comment]
flags https://tc39.github.io/ecma262/#sec-get-regexp.prototype.flags

**Comment by azu** [comment]
```js
JSON.stringify({ get a(){return 1}})
// "{"a":1}"
```

**Comment by laco0416** [comment]
```
class Bar {
  get bar() { return "bar" }
}
var bar = new Bar()
JSON.stringify(bar)
"{}"
```

**Comment by laco0416** [comment]
代表的な変換についての表

**Comment by azu** [comment]
JSONは外部とのやり取りに使うという用途を書く。

**Comment by laco0416** [comment]
JSONのユースケース

**Comment by laco0416** [comment]
JSON.parseの第2引数は扱わない、ということで

**Comment by laco0416** [comment]
`// replacer引数を使わない場合はnullを渡すのが一般的です`

**Comment by azu** [comment]
> JSON.stringify()

再帰的になってるときに例外を投げる。

**Comment by azu** [comment]
JSONの次はMap/Setの章。

http://exploringjs.com/es6/

**Comment by laco0416** [comment]
https://gist.github.com/uupaa/8d2e5b19c1a1ef267ec2

**Comment by azu** [comment]
http://exploringjs.com/es6/ch_maps-sets.html#sec_weakset

**Comment by laco0416** [comment]
EventEmitterとWeakMap

**Comment by azu** [comment]
https://github.com/R1ZZU/events2

**Comment by laco0416** [comment]
メモリリークしないための仕組み

**Comment by azu** [comment]
関数どうするか

コラム押し?

**Comment by laco0416** [comment]
関数の章は実はクラスの章なのでは？

**Comment by azu** [comment]
関数で => クラスっぽい
クラス => 実は関数では

という流れ

**Comment by azu** [comment]
`this` は多くの場合 クラスで使う。
関数で`this`を使うケース jQuery, Vueなど 

```
$.each(function (){
   this // <= $自体
})
```

みたいなケース。Arrow Functionを使う。

**Comment by laco0416** [comment]
argumentsに触れるなら関数の章しかない

**Comment by azu** [comment]
`call` と `apply` について触れる。

**Comment by azu** [comment]
https://www.softel.co.jp/blogs/tech/archives/1377 とspread operator

**Comment by laco0416** [comment]
`bind`

**Comment by azu** [comment]
`call` と `apply` と `bind` と Arrow Function.

**Comment by laco0416** [comment]
`::this` はstage0 https://github.com/tc39/proposals/blob/master/stage-0-proposals.md

**Comment by azu** [comment]
https://www.amazon.co.jp/dp/B00ESXY9MA/

**Comment by azu** [comment]
## スコープの章

- 普通の値の解決
- thisという特殊な変数の解決

## クラス

- クラスの話
- 関数とprototypeチェーン

**Comment by azu** [comment]
hoisting はコラム的な外伝的な

**Comment by laco0416** [comment]
サンプルコードがなんで var なんだ ってツッコミが入りそうだからconst/let で書いておいたほうがよさそう

**Comment by azu** [comment]
なぜサンプルコードがconstではないのか

**Comment by azu** [comment]
`const` に書き換えよう

**Comment by laco0416** [comment]
そうなるとhoistingは完全にコラムで良くなる

**Comment by laco0416** [comment]
`lexical`

**Comment by azu** [comment]
const は レキシカル 見た目どおりのコードになるので、積極的に使いましょう。

[静的スコープ - Wikipedia](https://ja.wikipedia.org/wiki/%E9%9D%99%E7%9A%84%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97 "静的スコープ - Wikipedia")

**Comment by azu** [comment]
var は以上

**Comment by laco0416** [comment]
他の言語を一応かける人向けのJS本なので、むしろvarの説明を理解してもらうのが難しそう

**Comment by laco0416** [comment]
JSON > Map/Set > Date

**Comment by azu** [comment]
DateはDateオブジェクト、unix time(getTime、ISOのやつで交換可能な例をベースにする

**Comment by laco0416** [comment]
`YYYY/MM/DD` の実装例

**Comment by laco0416** [comment]
Symbolは章にならなさそう

**Comment by laco0416** [comment]
Date/i18n https://github.com/asciidwango/js-primer/issues/125

**Comment by azu** [comment]
クラス - stateを持ってる例
- Counter

**Comment by azu** [comment]
日付 https://github.com/asciidwango/js-primer/issues/125

**Comment by azu** [comment]
https://tatsu-zine.com/books/software-g11n

**Comment by azu** [comment]
次回:  8/24(木)
