### ISSUE TITLE
2章の序章: Node.jsのインストール

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#267]
別名: 環境の章

全体構成的には2部構成

1. 基本文法 
2. ユースケース

2ではそれぞれのユースケースを元にブラウザ、Node、ブラウザのような感じで話が進んでいく。
この2部に入る直前にユースケース(特定の実行環境)についての前置きがあると良さそうと思った。

https://github.com/asciidwango/js-primer/issues/6#issuecomment-318794654

今まで学んで来たJavaScript(つまりECMAScript)は実行環境に左右されにくい内容だけど、ここから先はブラウザやNodeなど実行環境に依存した部分があるよとか
そもそも実行環境ってどういうこと? みたいな1-3ページぐらいの内容。

---

追記(2018-09-06)

https://github.com/asciidwango/js-primer/issues/267#issuecomment-419065911 でNode.jsのインストール紹介を中心にする内容へと変更することにした。
ローカルサーバはajaxのところでそれぞれ紹介する

**Comment by azu** [comment]
基本文法のビルトインオブジェクト一覧とブラウザ、Nodeなどの環境の違いによるオブジェクトの紹介を軽くする

- ビルトインオブジェクト一覧
- Symbolとか本文ではちゃんとふれないやつ
- ブラウザにはDOMがある
- Nodeにはprocess, moduleとか

**Comment by azu** [comment]
NodeはCommonJSモジュール(最近はESM)
BrowserはES2015でES Modulesが増えて
環境毎にモジュールの扱いがあるよ。

それぞれユースケースで紹介するよ

**Comment by lacolaco** [comment]
さきにユースケースをTODOアプリまで終わらせてから何を書けばいいかを考えるのでpending

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/36342212-5e0dbdcc-143e-11e8-91db-42d8e0aef405.png)

https://timothygu.me/es-howto/#what-belongs-to-the-ecmascript-specification みたいな羅列あると便利かなー?

**Comment by azu** [comment]
- ブラウザのバージョン
    - Node.jsのインストールとバージョン
    - npxのバージョン

についてをこの章で入れる。
各章はこれを参照する

**Comment by azu** [comment]
ここにローカルサーバの立て方と必要性についてを書く

**Comment by azu** [comment]
#531 で

- Node.jsのインストール方法の紹介
- Node.jsのprocessとかのグローバルオブジェクトの紹介
- ブラウザのグローバルオブジェクトとは異なる = 実行環境の違い
- `node main.js` でのNode.jsのスクリプト実行
- nodeバージョン、npmバージョン

という感じにするといいのではという話をした。
Node.jsでする環境を作る章

**Comment by yumetodo** [comment]
Node.jsのインストール方法の紹介というのはnvmとかのことまでは想定していますか？

**Comment by azu** [comment]
ユースケースを進めるのに必要なNode.jsをインストールするという感じなので、
公式のインストーラーの紹介ぐらいという想定ですね。
nvmはWindows対応してるわけではないし、バージョン管理ツール使う人は自分で入れられると思うので、やり方として紹介する必要はない気がします。(インストーラーより手順が簡潔になるわけでもないので)
存在を書くのはいいと思いますが、書籍としての想定は公式インストーラーを前提に進めると思います。

[かんたん Ruby](http://gihyo.jp/book/2018/978-4-7741-9861-3)だと次のような感じでした。

- Windows + 他共通として公式インストーラー(スクショとか丁寧)
- mac で homebrew を使った方法
  - rbenv (これはmacだとシステムrubyが入ってるせいですね)

はじめてのJavaScriptでは

- 公式インストーラー(文字だけ)

[超速! Webページ速度改善ガイド](https://webperf.guide/)だと

- 公式インストーラー(文字だけ)
- noenv,nodebrew

改訂新版JavaScript本格入門では

- 公式インストーラー(文字だけ)
