### ISSUE TITLE
条件分岐: if/switch/block

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#31]
基本文法 #17 

- [ ] 文と式

------

- [x] if/else/elseif
- [x] swich
- [x] `{ }` block 
- [x] <del>space</del>
- [x] <del>ASI セミコロン自動挿入</del>

ラベルは次のコードが動くという豆知識ぐらいにしか使わない気はする

```
http:// 
```

ここは単純に説明するだけだとそうですねって感じがするので、できるだけ実際の細かいユースケースに寄せたい。
とくにswitchとかはなんとなく使うパターンがあるとは思う(アンチパターンになりやすい)

## 草案

- ブロックステートメントについての解説。ブロックの機能については #24 で扱う
- if文、else-if、elseについて一通り解説
- 全てを使ったサンプル - 閏年? [C言語入門：うるう年判定プログラム:Geekなぺーじ](http://www.geekpage.jp/programming/c/leap-year.php "C言語入門：うるう年判定プログラム:Geekなぺーじ")
- switchでは列挙するようなものが書ける
- break忘れによるミスの紹介
- もっと正しく使うには関数と組み合わせる必要がある

Iterator関連は #68 に分離

**Comment by azu** [comment]
switchがややこしい

最近Reduxとかでswitchを使うケースが増えたけど、使う条件はかなり限定的な気がする。
定数があって処理が1行でreturnできるものみたいな

- [Reducers | Redux](http://redux.js.org/docs/basics/Reducers.html)

`switch(true)` も普通はかかなくてもいい気はする

- [自分は switch(true) イディオムを使ってなぜクソコードを書くのか - Qiita](http://qiita.com/khsk/items/90f07f8bfeeb66cbaf32)
- [switch(true) イディオム考察 - Qiita](http://qiita.com/t_uda/items/1969e09a970d71e4cfd6)

**Comment by azu** [comment]
ここで初めて __文__ が出てくるのかな。
JavaScriptの場合はif文だから、if式ではないというのを上手く伝える事ができると良さそう。

文の中に式は書けるが、式の中に文を書くことはできない(ホント?)とか
値を返すのが式、返さないのが文。(例外がeval [知られてそうで知られてない少し知られてるECMAScript 2015 (ES6)の新機能: Days on the Moon](http://nanto.asablo.jp/blog/2016/05/12/8088330 "知られてそうで知られてない少し知られてるECMAScript 2015 (ES6)の新機能: Days on the Moon"))

- [] 仕様の中ではどういう解説なのか読む
- 文 = ステートメント、式 = Expressionと紐付ける話

**Comment by azu** [comment]
switchがそもそもあんまり使われてなかったのは、break忘れとかdefault忘れとか、罠が多かったからというのは大きそう。
今だとLintでわかるようになっているけど。

- [Rule default-case - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/default-case)
- [Rule no-fallthrough - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/no-fallthrough)

ただ、switchの中が膨れるのは読みにくいコードの原因なので、switchの使い方としてはそういうのを触れたい。switchの下にコード続けるのはあんまりしないと思うので基本的には #20 関数と組み合わせて使うものななんだよなー。

**Comment by twada** [comment]
> 式の中に文を書くことはできない(ホント?)

FunctionExpression (関数式) や SequenceExpression (俗にカンマ演算子というやつ) の中に文を書けてしまいます

**Comment by azu** [comment]
そうですよね。ありがとうございます

**Comment by azu** [comment]
やっぱりここに[12.14Conditional Operator ( ? : )#](http://www.ecma-international.org/ecma-262/7.0/#sec-conditional-operator "12.14Conditional Operator ( ? : )#")は入れたいな。
演算子でまとめる必要性なさそうな気がしてる。

これとifの違いを含めて、文と式の説明とするのがよさそう。

**Comment by azu** [comment]
`? :` 仕様的には条件演算子 になるけど、
三項演算子と言われることが多い気はする。
三項演算子って用語をメインにした方がいいのか、条件演算子をメインした方がいいのかが微妙だな。
条件演算子の方が正しいのだろうけど。

- [式と演算子 - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators)
- [三項演算子は悪か？ - Qiita](http://qiita.com/stkdev/items/cbb83cbd9921b9f755a4)
- [条件演算子 - Wikipedia](https://ja.wikipedia.org/wiki/%E6%9D%A1%E4%BB%B6%E6%BC%94%E7%AE%97%E5%AD%90)

> `? :`は条件演算子と呼びます。また `<条件式> ? <真式> : <偽式>` のように3つの式を使う演算子であることから三項演算子とも呼ばれます。

という感じかな

**Comment by azu** [comment]
`"文字列".length` ってelementsの数と言ってるのか

> The number of elements in the String value represented by this String object.
> [ECMAScript® 2016 Language Specification](http://www.ecma-international.org/ecma-262/7.0/#sec-properties-of-string-instances-length "ECMAScript® 2016 Language Specification")

**Comment by azu** [comment]
swiftだとdefault忘れはSyntax Error

- [[Swift]switch文のcaseやdefault節で何も処理しない場合はbreakが必要 - Qiita](http://qiita.com/ohkawa/items/3ee37cc133b7e4a68682 "[Swift]switch文のcaseやdefault節で何も処理しない場合はbreakが必要 - Qiita")
