### ISSUE TITLE
node-cli: util.promisifyについて触れる

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#311]
[util.promisify(original)](https://nodejs.org/api/util.html#util_util_promisify_original "util.promisify(original)#")についてを簡単に触れる

> fsのreadFileの紹介のところでさくっと util/promisify を紹介しておいて、NodeにもPromiseがあることを述べておく
> https://github.com/asciidwango/js-primer/issues/301#issuecomment-341380344

**Comment by lacolaco** [comment]
これ、nativeでfsにpromise入りそうだしどうなんだろうっていう感じがする

nodejs/node#18297

**Comment by azu** [comment]
たしかにー promisify自体は言及しなくてもいいのかな。

Node.js v8時点ではNode.jsのコアAPIはPromiseをサポートしていませんが、検討されていますって雰囲気。

**Comment by azu** [comment]
`fs.promise`はnode 10で入るらしい

**Comment by lacolaco** [comment]
一旦見なかったことにして必要性を感じたらコラムを書く
