### ISSUE TITLE
関数とthis

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#316]
#112 の関数と`this`の章

## 目的

- <del>Functionオブジェクトを理解する</del>
- thisを理解する
- Functionのメソッドを理解する

## アウトライン

- https://github.com/asciidwango/js-primer/blob/master/source/basic/function-this/OUTLINE.md

## TODO

- [ ] 簡易版を書く
  - 難易度が高い、ページ数を取ってるため
  - ページ数的に問題ないならこのままでもいい

**Comment by azu** [comment]
- [What is This in JavaScript?](https://developer.telerik.com/topics/web-development/what-is-this-in-javascript/ "What is This in JavaScript?")
- [JavaScriptにおけるthisの挙動まとめ(Node.js) - Qiita](https://qiita.com/knknkn1162/items/0fa7dcb6a735125d21db "JavaScriptにおけるthisの挙動まとめ(Node.js) - Qiita")

**Comment by azu** [comment]
[jQueryを使うときに安易にアロー関数を使ってはいけない(戒め) - Panda Noir](http://www.pandanoir.info/entry/2017/11/04/190000 "jQueryを使うときに安易にアロー関数を使ってはいけない(戒め) - Panda Noir")

**Comment by azu** [comment]
##  開眼JavaScript

開眼JavaScript(ES3)だと `this` の章は次のような感じ

- this とは何か、および this は何を参照するか
	- `obj.method` を `this.method`に置き換える例
	- `this`は混乱する
	- new、call,apply,bindは別
- this の値はどのように決められるのか?
	- コンテキストに基づく
- 入れ子関数内では、this は グローバルオブジェクトを参照する
	- ES5で直るパターン
- 入れ子関数内で this を見失う問題を スコープチェーンを使って回避する
	- `var that = this`
- call() や apply() を使って this の値を コントロールする
- this キーワードをユーザ定義の コンストラクタ関数で使う
	- newは特別
- プロトタイプメソッド内の this は 生成されるインスタンスを参照する

**Comment by azu** [comment]
タイトル変えました。`this`の章にします。

**Comment by azu** [comment]
実際にちょっと書いてみて流れ的な問題が悩ましいことが分かった。
関数の定義方法が色々あるのと、thisにおいてはその定義方法で意味が違うよって話がでてくる。
関数の定義方法の振り返りを先にやるか、先にthisってこんな感じのものだよって話をしてから、
thisはglobal、関数、arrow functionでそれぞれ動きが違うよって流れにするかが難しい。

出てくる内容は大まかに次のものからそこまで離れないだろうとは思ってるので完全に書き方の問題。

- タイトル: 関数と`this`
- 目的: `this`についてを理解する
- 目的: `this`には3種類の扱いがあり、それぞれの動作についてを理解する
- 目的: `this`の安定した扱い方についてを理解し、クラスにおける用法へ備える
- thisは特別なキーワード
	- オブジェクトのように振る舞うがthisは読み取り専用
- thisは暗黙的
	- argumentsのように呼び出し元によってどのような値になるかが決まる
	- thisは暗黙的だから使う
	- ただしArrow Functionは
- `this`という話
	- ThisModeという視点だと`this`は三種類
		- `global` = undefined
		- `strict` = dynamic
		- `lexical` = Arrow Function
- グローバルと`this`
- 関数と`this`
	- 関数の定義方法
		- Functionキーワード
		- Arrow Function
	- メソッドの定義方法
		- 関数式
		- 短縮記法
		- Arrow Function
	- thisにおいてはArrow Functionとそれ以外に分類される
- 関数
	- `function`キーワード
	- 短縮記法のメソッド
	- これらにおける`this`は
- Arrow Function
- thisとFunctionキーワード
	- var that = this
- thisとArrow Function
	- thisがlexicalモードになる
- thisを決めて関数を呼ぶ
	- call
	- apply
	- 3rd arguments(Array系))
	- bind
	- `this`はこの影響を受けない
		- `If thisMode is lexical, return NormalCompletion(undefined).`という回避ステップがある

**Comment by azu** [comment]
いろんな書籍とか調べててちょっと読み方がやっぱり既存のJavaScriptをやってた人向けだなという感じがしてきた。つまり関数でのthisを説明してからArrow Functionのthisは良いよって話の流れ。

スコープ #277 の章とかも最初からブロックスコープとかある前提で、古い関数スコープとかは既存のコードを理解するためだけに必要だよって流れで書いていた。
thisについてもこの流れで書いていくのが良いのではないかなと思ってきた。
つまり、Arrow Functionにおける this (静的なthis)の話をしてから、既存のコードの関数(function)における thisってこんな不思議な挙動するけど、古いコードを理解するには必要だよねって感じの流れ
[関数とスコープ · JavaScriptの入門書 #jsprimer](https://asciidwango.github.io/js-primer/basic/function-scope/ "関数とスコープ · JavaScriptの入門書 #jsprimer") におけるhoistingする書き方ってダメだけど、既存のコードを理解するには必要だよねって感じで。

hoistingとは違って、完全にfunctionは悪ではないのがちょっと違うけど(メソッド短縮記法とかは結局はfunctionと同じ動き)、Arrow Functionを最初に書いてしまうという感じ

**Comment by azu** [comment]
`this`の挙動を調べてたけど、Chromeはどうもおかしいのでバグ立てた。

- https://azu.github.io/what-is-this/
- [791334 - `this` in top level Arrow Function in Module Context should be `undefined` - chromium - Monorail](https://bugs.chromium.org/p/chromium/issues/detail?id=791334&q=Module%20Arrow%20Function%20this&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified "791334 - `this` in top level Arrow Function in Module Context should be `undefined` - chromium - Monorail")

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/33524675-92152bde-d864-11e7-9711-82f93646f709.png)

`this`が基本的な参照するルールとして

- 「関数を呼び出す際にその関数が所属するオブジェクト」
- 「関数を呼び出す際のレシーバーオブジェクト」

どっちがいいかというの難しいなー

レシーバーオブジェクトの定義が必要なんだけど「ドット演算あるいはブラケット演算でオブジェクトのメソッドを呼んだ時、演算子の左辺に指定したオブジェクト」とか小難しい。

![image](https://user-images.githubusercontent.com/19714/33524693-ea52376a-d864-11e7-93bc-f7adb1b8e55c.png)
仕様も ただの変数ぐらいにしかでてこないし、実際はもうちょっと違う仕組みとも言えるの、なんか簡単なルールが難しいな

**Comment by azu** [comment]
レシーバーオブジェクトにしよう。
最初に定義を書く

独自用語なので、
https://github.com/asciidwango/js-primer/issues/231 用語集にも追加する。

**Comment by azu** [comment]
> レシーバーオブジェクトにしよう。

これベースオブジェクトにして、レシーバーオブジェクトとも言われることがあるよって話にしよう。
https://tc39.github.io/ecma262/#sec-getbase
仕様でもベースという言葉がでてくるし、レシーバーに比べて分かりやすい気がする。

**Comment by azu** [comment]
https://twitter.com/awbjs/status/938272440085446657
簡易版を書く時はこれを目安にしてばっさり関数は消そう

**Comment by lacolaco** [comment]
簡易版については全体を見てから考えるので一旦close
