### ISSUE TITLE
モジュール(module)

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#329]
https://github.com/asciidwango/js-primer/issues/267
環境 > モジュールの章

ユースケースの一部

**Comment by azu** [comment]
https://groups.google.com/forum/m/#!msg/mozilla.dev.platform/DZ7YctNoUUk/c2w8Ue8QCgAJ
Firefox 60から

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/tree/master/meetings/2017-12-07#%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB

**Comment by azu** [comment]
拡張子はデフォルトでつけておいて、Node.jsでは省略できますと注記する

**Comment by lacolaco** [comment]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import

**Comment by azu** [comment]
[Native JavaScript modules by Serg Hospodarets](https://slides.com/malyw/native-js-modules#/)

**Comment by azu** [comment]
現実ではmoduleを直に使うよりbundlerを使ったほうがいいよという話を最後に入れる場合に参照しそうなやつ。

[Using JavaScript modules on the web  |  Web Fundamentals  |  Google Developers](https://developers.google.com/web/fundamentals/primers/modules)
