### ISSUE TITLE
リリース時に通知を受け取れるフォーム

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#33]
現在は特にないが、ウェブサイトとして公開した時に、リリース情報の通知を受け取れるフォームを用意する。
メールアドレスを入れてもらって、リリース時に通知する形での利用。

**Comment by laco0416** [comment]
- Googleフォーム
- MailChimp
- other

**Comment by laco0416** [comment]
MailChimpは2000人まで無料だけど、Googleフォームでいいんじゃないかという雰囲気。
