### ISSUE TITLE
オブジェクト: spread operatorについてを追加する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#349]
From https://github.com/asciidwango/js-primer/issues/343

> オブジェクトのコピー/マージ
> https://asciidwango.github.io/js-primer/basic/object/

ES2018で入る object spread/rest についてを追加する。

**Comment by lacolaco** [comment]
ユースケース側からも参照します #351

**Comment by azu** [comment]
spread 構文 にする
