### ISSUE TITLE
style: コードの整形にprettierを使う

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#358]
ESLintだと空改行とかのスタイルが統一するの面倒そうなので、[Prettier](https://prettier.io/ "Prettier")を適応するのがよさそう。(ESLint + Prettier)

ただ、説明的にスペースを明示的に空けたい場合もありそうなので、一回試してみる。
(prettierあんまり設定できないので、逆に説明のじゃまになる可能性も…。`,`は省略できるみたいな話で壊れる場合がある)

```js
// こういうやつのスペースが統一できてない
class A {

}
```

`width`と`indent`が問題になりそう。
紙面を考えたら`indent`は 4 spaceぐらいが妥当そうな気がする。
`width`はどれぐらいが妥当なんだろ?

80, 100, 120 のどれかになると思うけど。
ウェブと紙面で使い分けるもありそうなので、とりあえず

- width: 100
- indent: 4

あたりで設定して試してみる。

/cc @lacolaco

**Comment by nd-02110114** [comment]
@azu 
少し前のIssueになるのですが、
こちらの方 現在どのようなモチベーションでしょうか？

個人的に、やってみたいと考えてます 🙋‍♂️

**Comment by azu** [comment]
このIssueの最終的な目的は文章中のコードスタイルを揃えることで、雑味をなくすことですね。
なので最終的には目視でやるとは思いますが、機械的に揃えられるならそうした方がいいですねという感じのIssueです。

今はすごいゆるいESLintの設定([eslintrc.js](https://github.com/asciidwango/js-primer/blob/master/config/base.eslintrc.js))でインデントなど基本的なスタイルを揃えています。
(スタイル以外にもdouble quote, constベースといった一部コードの方針のルールがあります)

一方ちゃんと設定を吟味してないので、次のようにむだな(もしくはコメントを書いて埋めるべき)空改行が混ざっている(スタイルのずれがある)というのが気になって立てたIssueだったと思います。

![image](https://user-images.githubusercontent.com/19714/40887404-5658ec62-6783-11e8-83db-f6714309f8cb.png)

- <https://asciidwango.github.io/js-primer/basic/string/>

ゆるいESLintにしてるのは、基本文法ではそれぞれの書き方も紹介するのでどっちが正解というものではないからですね。(スペースとかインデントとかは完全にスタイルの問題なので全体的に揃えていい)

なのでベースではdouble quoteになってますが、sinle quoteの話もしてるので、そういう例外的なのは`<!-- textlint-disable eslint -->` コメントで無視するなどして、できる書き間違いが減るようなベースを設定してます。

	
	
	{{book.console}}
	```js
	var double = "文字列";
	console.log(double); // => "文字列"
	var single = '文字列';
	console.log(single); // => '文字列'
	// どちらも同じ文字列
	console.log(double === single);// => true
	```
	
	

今の所気になっているスタイルのずれは以下の2種類ですね。

- 空改行が入るタイミングが異なる
	- 関数定義のあとに空改行があったりなかったり。ないで統一かな
- ユースケースでHTMLなどのインデントや改行のスタイルが違う(azu or laco)

タイトルのprettierうんぬんはESLintと違ってPreitterは仕組み的に決定的なスタイルになるので、楽できるかなと思った形です。
(ただ基本文法の方でPrettierをかけると例外部分が大量にでてきて管理できない可能性はあるかなーという印象です)

なので、この問題を解決するにはいくつか試してみないと最適な方法がわからなくて後回しにしてました。

それぞれの問題に次のような選択肢が今の所あります。

- 空改行が入るタイミングが異なる
	- ESLintで空改行を決定的にするルールを探す
	- いちかばちかPrettierでいい感じになる
	- そこまで数が多くない or コメントを入れたほうが実は適当な可能性もあるので手作業でがんばる
- ユースケース
	- 基本文法とユースケースでESLintの設定を分けて、ユースケースにはPrettierをHTML,CSS,JSにかける(統一感)
		- 追記: PrettierはHTMLをサポートしてなかった…
		- [Supporting HTML/Mustache · Issue #1882 · prettier/prettier](https://github.com/prettier/prettier/issues/1882)
		- HTMLだけの整形ツールを何か入れる

**Comment by nd-02110114** [comment]
@azu 

ご説明ありがとうございます 🙇 

> 空改行が入るタイミングが異なる

こちらについては、
ESLintで空改行を決定的にするルールを探して、だめなら手作業が良さそうですね...
暇な時に探してみようと思います！

> ユースケース

こちらは、Prettier使えそうですがHTMLはまだ未対応なんですね 😇 
HTMLの整形用のCLIは、以下が有名そうです
https://github.com/beautify-web/js-beautify

大きめの変更だと、ユースケースにPretterを使うということになると思うのですが、
HTMLのFormatterを別に入れるのがあまりいけてないのと、
そこまでコード規模もなく(増える予定もあまりなさそう)急いでやる必要なさそうですね....

こちらも、気長にやってみたいと思います！
(PrettierがHTML対応するのを待ちながら...)

**Comment by nd-02110114** [comment]
ここの進捗 結構ありそうですね 👀 
落ち着いたら、試してみようと思います
https://github.com/prettier/prettier/pull/4753

**Comment by azu** [comment]
こちらはcloseでいいかな。
