### ISSUE TITLE
セクションのパーマネントURLに日本語を含まないようにする

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#359]
GitBookの機能でセクションのタイトルに 内部リンクを指定できる。

```
## タイトル {#header}
```

をつけると `url#header` の内部リンクでアクセスできるようになる。

ウェブ版はリンクを自由に貼れる書籍にしたいため、細かくリンクを貼れる仕組みをととのえる

## Tasks

- [x] textlintルール https://github.com/asciidwango/js-primer/pull/418
- [x] リンクを貼る

**Comment by azu** [comment]
基本的に各 `# タイトル {#title}` を付けていくだけなので、完全に人力作戦になる。
手伝ってくれる人も募集していいます。

**Comment by azu** [comment]
#360 DocSearch連携をマージした。
検索から直接セクションのパーマネントにジャンプできるようになった

**Comment by nd-02110114** [comment]
#361 を見た感じあまり進んでいないみたいなので、こちらの作業をお手伝いしたいです 🙋

**Comment by azu** [comment]
@nd-02110114 そうですね。訳語はその場で考えて適当に当てていることが多いですね。。
まあページ内リンクは最悪名前が変わっても問題ない(リンク切れにはならない)ので、ある程度適当で大丈夫です。

基本的には、名詞、固有名詞、動詞、and, or, ofぐらいだと思います。
(完全に訳さなくてもユニークになっていれば問題ないので、ざっくりとした単語を当てはめることが多いです)

固有名詞は大部分は[仕様書](https://tc39.github.io/ecma262/)の単語を元にしていて、一部(  #231 )だけ例外的に仕様的じゃない単語を使っています。
仕様書の単語と https://developer.mozilla.org/en-US/docs/Web/JavaScript の単語は大体一致していると思うので、基本的にはMDNの単語を参考にするのが手っ取り早いと思います。

(多分ですが) 既存のセクションタイトルの単語に `s` は付けてない気はします。

**Comment by nd-02110114** [comment]
@azu 
ご返答ありがとうございます。数日中に作業して、PRを出してみます。

**Comment by azu** [comment]
@nd-02110114 ありがとうございます。
コンフリクトを避けるために章(ファイル単位)毎ぐらいのPRだといいかもしれませんね。

**Comment by yumetodo** [comment]
通知が大爆発しているから何事かと思ったらこれか。びっくり。

**Comment by azu** [comment]
@nd-02110114 ありがとうございます！
ひとまず一通りみました。
https://github.com/asciidwango/js-primer/pull/397
https://github.com/asciidwango/js-primer/pull/399
https://github.com/asciidwango/js-primer/pull/400
https://github.com/asciidwango/js-primer/pull/403
https://github.com/asciidwango/js-primer/pull/410

**Comment by nd-02110114** [comment]
@azu 
ご確認ありがとうございました！
2部については、今週にまた少しずつやって行きたいと考えています。

**Comment by azu** [comment]
#418 で自動チェックするルールを追加したので、これからはヘッダを追加する際にIDを書いていく形になると思います。

@nd-02110114 @yumetodo ご協力ありがとうございました。
