### ISSUE TITLE
無効なエスケープシーケンスについてどこかに書けないか

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#372]
```js
console.log("\d".length)
// 1
console.log("\d" === "d")
// true
console.log("\\d".length)
// 2
console.log("\\d".codePointAt(0))
// 92, the code point for the backshlash
console.log("\\d".codePointAt(1))
// 100, the code point for the lower case "d".
```

のように無効なエスケープシーケンスは単にバックスラッシュがなかったように扱われる。

これはべつにC++でも

```cpp
#include <iostream>
int main()
{
    std::cout << "\d" << std::endl;// => d
}
```

https://wandbox.org/permlink/Qevm2lLrlhJNqxTA

同じ挙動なのですが、

GCC

>warning: unknown escape sequence: '\d'

Clang

>warning: unknown escape sequence '\d' [-Wunknown-escape-sequence]

のようにコンパイラが怒ってくれる一方、JavaScriptではそういうことはない(もしかして知らないだけでESLintでもできる？)

なのでどこかでこの件について取り上げることはできないでしょうか？

---

提案の背景: https://github.com/MithrilJS/mithril.js/issues/2089

**Comment by azu** [comment]
> ESLintでもできる？

ESLintだと以下のルールが恐らくそれだと思います。
https://eslint.org/docs/rules/no-useless-escape

Demo: [ESLint demo](https://eslint.org/demo/#eyJ0ZXh0IjoiXCJcXGRcIi5sZW5ndGhcbi8vIDFcblwiXFxkXCIgPT09IFwiZFwiXG4vLyB0cnVlXG5cIlxcXFxkXCIubGVuZ3RoXG4vLyAyXG5cIlxcXFxkXCIuY29kZVBvaW50QXQoMClcbi8vIDkyLCB0aGUgY29kZSBwb2ludCBmb3IgdGhlIGJhY2tzaGxhc2hcblwiXFxcXGRcIi5jb2RlUG9pbnRBdCgxKVxuLy8gMTAwLCB0aGUgY29kZSBwb2ludCBmb3IgdGhlIGxvd2VyIGNhc2UgXCJkXCIuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==)

**Comment by azu** [comment]
文字列と正規表現リテラルで無意味なエスケープは異なるので扱いが難しいですが、
文字列の章は後で整理するつもりです。そこで検討してみます。
無効なエスケープシーケンスについてというよりは、エスケープシーケンス自体についてですかね。

恐らくエスケープシーケンスで問題となる場合の殆どは文字列と正規表現の相互変換 か JSON周りだと思うので、その辺について気をつける必要があることについてがわかると良いのかもしれないですね。

一応、過去のECMAScriptに[RegExp.escape](https://github.com/benjamingr/RegExp.escape "RegExp.escape")を追加しようという話がありましたが、このプロポーザルの策定は中止されてましたね。
(経緯は忘れましたが、何か原理的に難しい要因があったような気がします)

**Comment by azu** [comment]
これあｈ #643 でかいけつ
