### ISSUE TITLE
演算子の章のTypoです

### ISSUE THREAD

**Issue by nd-02110114** [asciidwango/js-primer#374]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/operator/README.md
もうすでに気づいていたらすみません...

```js
const value = null; /* または undefined */
if (value == null || value === undefined) {
    console.log("valueがnullまたはundefinedである場合の処理");
}
// == で書いた場合
if (value == null) {
    console.log("valueがnullまたはundefinedである場合の処理");
}
```

`if (value == null || value === undefined) {`のところ

`if (value === null || value === undefined) {`な気がします

**Comment by nd-02110114** [comment]
PR出しました !
#376

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/376 マージしました 🎉
