### ISSUE TITLE
class/クラス

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#39]
基本文法 #17 

関数 #112 の続き

## 目的

- `class`構文の基本的な使い方について学ぶ
- JavaScriptのクラスの性質についての概要
  - prototype、関数との関係について

## 目的ではないこと

- オブジェクト指向のパターンなど考え方に近い部分
- 型としてのクラス
- 現在のProposalの詳細(privateとかpublic fieldの詳細、こう書けるようになるかも的な話)

## アウトライン

- <https://github.com/asciidwango/js-primer/blob/master/source/basic/class/OUTLINE.md>

## 関連

- #345 プロトタイプ(大きくなったのでIssueとして分けた)

## 参考文献

- [14. New OOP features besides classes](http://exploringjs.com/es6/ch_oop-besides-classes.html)
- [クラス - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Classes)

**Comment by azu** [comment]
[Why do ES6 Classes exist and why now? | appendTo](http://appendto.com/2016/06/why-do-es6-classes-exist-and-why-now/ "Why do ES6 Classes exist and why now? | appendTo")

**Comment by azu** [comment]
無名クラスについてはJavaScriptらしさがあるので触れる必要がありそう。
後、高階関数としてクラスを返すってのも珍しい気がする

**Comment by azu** [comment]
[3 Different Kinds of Prototypal Inheritance: ES6+ Edition — JavaScript Scene — Medium](https://medium.com/javascript-scene/3-different-kinds-of-prototypal-inheritance-es6-edition-32d777fa16c9#.v61dm04up "3 Different Kinds of Prototypal Inheritance: ES6+ Edition — JavaScript Scene — Medium")

**Comment by azu** [comment]
クラスとシングルトンについては触れたい気がする。
[Almin.js | JavaScriptアーキテクチャ](http://azu.github.io/slide/2016/child_process_sushi/almin-javascript-architecture.html "Almin.js | JavaScriptアーキテクチャ") とかでも書いていたけど、JavaScriptとシングルトンはなんだかんだ切り離しにくい存在なきがしている。
クラスで書くとシングルトンの作り方が何パターンがでてくるので、何か例示できると良さそうな気がする。

**Comment by azu** [comment]
[JavaScript Design Patterns: The Singleton](https://www.sitepoint.com/javascript-design-patterns-singleton/ "JavaScript Design Patterns: The Singleton")
シングルトンとfreezeの例

**Comment by azu** [comment]
[Is ''Class'' in ES6 the New ''Bad'' Part? - DZone Web Dev](https://dzone.com/articles/is-class-in-es6-the-new-bad-part "Is &#39;&#39;Class&#39;&#39; in ES6 the New &#39;&#39;Bad&#39;&#39; Part? - DZone Web Dev")

Good parts or Bad parts?
クラスってちゃんとした定義存在するのかな

**Comment by azu** [comment]
[itsy-bitsy-data-structures/itsy-bitsy-data-structures.js at master · thejameskyle/itsy-bitsy-data-structures](https://github.com/thejameskyle/itsy-bitsy-data-structures/blob/master/itsy-bitsy-data-structures.js "itsy-bitsy-data-structures/itsy-bitsy-data-structures.js at master · thejameskyle/itsy-bitsy-data-structures")
データ構造をclassで実装してる

**Comment by azu** [comment]
`new.target` class C extends null {
  constructor() {
    return Object.create(new.target.prototype);
  }
}

**Comment by azu** [comment]
[いまさらながらだけど、オブジェクトとクラスの関係を究めてみようよ - 檜山正幸のキマイラ飼育記](http://d.hatena.ne.jp/m-hiyama/20080109/1199863428 "いまさらながらだけど、オブジェクトとクラスの関係を究めてみようよ - 檜山正幸のキマイラ飼育記")
SmalltalkとかObjective-Cって確かにこういう説明をみた気がする。
JavaScriptでメタクラスみたいな話って見ないなーとか思ったけど、そもそも実体になるからか。
この辺はちゃんと仕様読んで解釈した方が良さそう。

**Comment by azu** [comment]
[thejsway/chapter09.md at master · bpesquet/thejsway](https://github.com/bpesquet/thejsway/blob/master/manuscript/chapter09.md "thejsway/chapter09.md at master · bpesquet/thejsway")

クラスの説明をしてからprototypeの説明をするパターン

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/328#issuecomment-349926589 より
```
## アウトライン

- クラス
- コンストラクタ
- new
- インスタンスメソッド
- prototype
- 静的メソッド
- getter/setter
- 継承
  - ビルトインオブジェクト
- mixin
- [コラム] minimal maximal

## 具体的な例題を決めたい

- クラスでどういうものを扱うか
- OOP
- オブジェクト
```

**Comment by azu** [comment]
無名クラスはJavaScriptのクラスは関数の一種である？と考えられる話から繋がりそう

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/34467225-67150798-ef2e-11e7-85ec-e5536381c274.png)

http://refactoringjs.com/ クラス周りの話 示唆に富んでていていいな。
JavaScriptのクラスは minimal maximal として導入されたので、そのクラスが完璧ではないというはちゃんと認識してないないといけない。
この辺はちゃんとコラムで触れたい。(+ ECMAScriptの策定プロセスの話は別途)

**Comment by yumetodo** [comment]
たしかにメンバ変数をconstにできない

**Comment by azu** [comment]
getter/setterは扱いが難しいから、構文的な紹介 + Array#lengthを再現してみる ぐらいにとどめておくのがいいかな。

[ArrayLike length implementation by getter/setter](https://gist.github.com/azu/eba89687a199e0cb8347ecc0b6436c93 "ArrayLike length implementation by getter/setter")

- [結局のところgetter／setterは要るのか？要らないのか？ - Qiita](https://qiita.com/katolisa/items/6cfd1a2a87058678d646)
- [getter/setterとはなんだったのか - プログラマーの脳みそ](http://d.hatena.ne.jp/Nagise/20141010/1412930502)
- [Why getters/setters is a bad idea in JavaScript - Notes of Maks Nemisj](https://nemisj.com/why-getterssetters-is-a-bad-idea-in-javascript/)
- [オブジェクト指向設計　getter, setterを使うなとはどういうことか - Qiita](https://qiita.com/Yahagi_pg/items/1bf59fc75d7f17c3b731)
- [結局のところgetter／setterは要るのか？要らないのか？ - Qiita](https://qiita.com/katolisa/items/6cfd1a2a87058678d646#_reference-8664ac8590df2cc99c22)

**Comment by azu** [comment]
- [JavaScriptのnew（インスタンス生成）は何をしているのか？について調べてみた - Qiita](https://qiita.com/rindarinda5/items/5501a01bd6001fafcbf7)
- [【連載記事】JavaScriptでプログラミングを学ぶ　その4：オブジェクト指向](https://sbfl.net/blog/2018/01/21/javascript-programming-4/)

newが何をやってるかは [JavaScript の new 演算子の意味: Days on the Moon](http://nanto.asablo.jp/blog/2005/10/24/118564 "JavaScript の new 演算子の意味: Days on the Moon") みたいな感じで解説した方がいいのかな

**Comment by azu** [comment]
継承 なんかちゃんと考えると普通のクラス定義と大体同じことを説明しないと行けない気がしてきた。

- クラスの定義
- コンストラクタ
- インスタンス化
- ...↓ここから先は継承のみの事↓
- super
- プロトタイプ継承
- ビルトインオブジェクトの継承

この辺はまあ飛ばしてしまうのは分からないでもないけど、クラス系の言語やったことない人には暗黙的に感じる気がする。
大体ルールは同じだけど、細かい所は別のルールがあるので一個づつやっていくのがいいのかなと思った。

- https://twitter.com/azu_re/status/962566152533639169

アウトライン更新したら、大体クラス定義と同じぐらいになった。

https://github.com/asciidwango/js-primer/blob/master/source/basic/class/OUTLINE.md

後は"継承のユースケース"はやるべきかが悩む。
漠然と継承使うと何か微妙だしユースケースに近いものはあってもいいかなー

**Comment by azu** [comment]
残り

- [ ] ビルトインオブジェクトの継承
- [ ] static メソッド

**Comment by azu** [comment]
[Demystifying ES6 Classes And Prototypal Inheritance ― Scotch](https://scotch.io/tutorials/demystifying-es6-classes-and-prototypal-inheritance "Demystifying ES6 Classes And Prototypal Inheritance ― Scotch")
クラスと継承の解説

**Comment by azu** [comment]
#380 Staticメソッドの継承について触れるべきか。
インスタンスはプロトタイプオブジェクトを継承し、
クラスはクラスを継承する

**Comment by azu** [comment]
#385 でstaticの継承についても書いたのでひとまず一通り完了。
リファクタリングは別途Issueを作りやる

**Comment by azu** [comment]
privateについては https://github.com/zenparsing/js-classes-1.1 とかもあるので、完全に削ったほうが安定かもしれない。
