### ISSUE TITLE
ランディングページを用意する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#42]
この本のURL として示しやすいページが欲しいので用意する。
合わせて #33 のフォームを配置する。

このリポジトリはtransferしたり、リポジトリ名を変更したりする可能性があるから、URLが一番問題になりそう。(少なくてもリポジトリ名は変更が必要…)

- gh-pagesはリポジトリをtransfer/renameしても追従されない
     - [About repository transfers - User Documentation](https://help.github.com/articles/about-repository-transfers/ "About repository transfers - User Documentation")
- リポジトリ自体( https://github.com/asciidwango/ES6book/ )は追従される

とりあえずな感じだとgh-pagesで用意しておいて、ちゃんとタイトルとかが決まったらそっちにリダイレクトする感じになる気がする。(transferしないでgit的に移すだけ)

JavaScript Plugin Architectureで試した感じでは、多くの人は一番ランディングページっぽいページをブクマとかする傾向があった。
GitHub.com はCSPが有効でFirefoxだとブックマークレットとかも使えないとかそういう要因もありそう。

- [JavaScript Plugin Architectureというプラグイン設計について学ぶ無料の電子書籍を書いた | Web Scratch](http://efcl.info/2016/06/06/JavaScript-Plugin-Architecture/)
- [azu/JavaScript-Plugin-Architecture: JavaScriptプラグインアーキテクチャの本](https://github.com/azu/JavaScript-Plugin-Architecture)
- [JavaScript Plugin Architecture - GitBook](https://www.gitbook.com/book/azu/javascript-plugin-architecture/details) <= ランディングページっぽい
- [この書籍について · JavaScript Plugin Architecture](https://azu.gitbooks.io/javascript-plugin-architecture/content/)

-----

📝 

|           | Organization                     | Repository only                    |
|-----------|----------------------------------|------------------------------------|
| Domain    | 一番柔軟で変更に強い                         | 複数のリポジトリが必要になるとダメ |
| No Domain | ドメインがない以外は特に問題なし | 単一のリポジトリなら問題なし       |

ドメインを使う場合はOrganizationを作って、Organizationにドメイン設定したほうが楽(リポジトリ単体だと扱いにくくなる)
複数リポジトリが必要になる可能性としては、ユースケースのサンプルを見られるURLを用意したい場合とかはリポジトリを複数作ってそこのgh-pagesに公開すると楽。

ドメインは[JS.ORG | DNS](https://dns.js.org/ "JS.ORG | DNS")のサブドメインという選択肢もあるけど、名前決めないと行けない問題は同じ

**Comment by azu** [comment]
https://asciidwango.github.io/ES6book/ で開けるようになった。
がやっぱりリポジトリ名は変えたい。
大文字があるのも区別されるため嫌な感じがする。

**Comment by kahei** [comment]
リポジトリ名、どんなふうに変えるのがいいですか？

**Comment by azu** [comment]
@kahei 仮名でもいいので、そのタイトルに合わせるのがいいですね。
小文字ハイフンで構成されるようにしたいのと、es6という単語は時間で古くなってしまうので、
リポジトリ名は時間で変更する必要がない名前にしたいというのが変えたい主な理由です。
(自分が付けると jsbook とかものすごい適当になります…)

**Comment by kahei** [comment]
@azu 企画時の仮タイトルは「ES2015によるJavaScript入門」なんですよね。ES2015もリポジトリ名には入れないほうがいいでしょうから、js-primerかなぁ。どうでしょう？

**Comment by azu** [comment]
> ES2015もリポジトリ名には入れないほうがいいでしょうから

既にES2016が出てるので、リポジトリ名としては何か微妙ですよね。
(リポジトリ名 = URLなので、URLにes2015と出てきてしまうとes2016に全く対応して内容に見えてしまいます)
本のタイトルとしてES2015というのが出てくるのは問題ないとは思っています。

> js-primerかなぁ

JavaScriptでprimerって単語を聞いて思い浮かぶメジャーなものは特にない感じがするので良さそうな気がします。

ググってみましたが知ってるものがなかった。

- https://www.amazon.co.jp/s/field-keywords=Javascript+Primer
- http://node-ardx.org/js-primer

@laco0416 どうでしょうか?

(js-primerにしても正式なタイトルが決まったら、後からリポジトリ名を変更するのは問題ないと思います。大文字のURLを無くしたいのが今のモチベーションなので)

**Comment by laco0416** [comment]
@azu js-primer、いいと思います！

**Comment by azu** [comment]
じゃあリネームします #50

**Comment by azu** [comment]
https://asciidwango.github.io/js-primer/ にリネームして、 #48 メールアドレスを登録できるようにしたので、このIssue閉じますー

**Comment by azu** [comment]
ちょうどタイトルがES6のままの本が出てた
https://www.amazon.co.jp/Js-next-Ecmascript-6-Aaron-Frost/dp/1449336361
http://shop.oreilly.com/product/0636920026396.do
記録によると一番最初は 2013年5月発売  予定だった…
