### ISSUE TITLE
2018-03-22 MTGアジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#420]
2018年3月22日のアジェンダ

**Comment by azu** [comment]
#359 idを付け直した

**Comment by azu** [comment]
- [x] #39 class

private https://github.com/zenparsing/js-classes-1.1 などもでてきて概念が揺れそうな気がするので完全に隠してもよさそう

**Comment by azu** [comment]
#4 todoアプリ の構成について

**Comment by azu** [comment]
[「スプレッド演算子」という表現を使わない - Qiita](https://qiita.com/hoo-chan/items/784f103e4d26747c89f0 "「スプレッド演算子」という表現を使わない - Qiita")


[meta] 用語集 Type: Meta
#231 spread element/syntaxに呼び方についてを再考する

**Comment by azu** [comment]
残りの章管理

- [基本文法](https://github.com/asciidwango/js-primer/projects/1)
- [ユースケース](https://github.com/asciidwango/js-primer/projects/3)

**Comment by azu** [comment]
[時間があったら]

- class: privateの取扱についてを決める #422
- introduction: JavaScriptとECMAScriptの区別について #123 
  -  #54 ECMAScript/JavaScript策定プロセス と関連付ける?
- 無効なエスケープシーケンスについてどこかに書けないか 基礎文法 #372

**Comment by lacolaco** [comment]
fs.promiseについていい説明されてるページあったら参考にしたい #311

**Comment by azu** [comment]
----
ここからMTG

**Comment by azu** [comment]
https://asciidwango.github.io/js-primer/basic/map-and-set/#add-and-take-out-for-map をみていて、deleteがタイトルにはないなーと思った

**Comment by lacolaco** [comment]
`map-read-and-write` でよさそう

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/381
todoのリファクタリングをした

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/source/use-case/todoapp/OUTLINE.md

**Comment by lacolaco** [comment]
http://todomvc.com/examples/vanilla-es6/

**Comment by azu** [comment]
- TODO足りないもの
- [ ] タイトルの変更
- [ ] フィルター

**Comment by azu** [comment]
Todoアプリはイベント駆動で回る状態をもったアプリ

**Comment by azu** [comment]
最初に全体像
CSS 入りのHTMLを置いて、動的な部分をJavaScriptで作るよという導入

**Comment by azu** [comment]
- event
- module
- class
- array
- template literal

ぐらいかな

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/92f9f6d0c163dd19b05b327317b9e238e604f24a/source/basic/map-and-set/README.md#weakmap-weakmap

**Comment by lacolaco** [comment]
WeakMapのところでEventListener管理みたいな話を書いてる

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/424
EventEmitterの一貫性がない

**Comment by lacolaco** [comment]
https://asciidwango.github.io/js-primer/basic/class/#extends-usecase ここのEventEmitterは配列でハンドラ管理してる

**Comment by azu** [comment]
https://asciidwango.github.io/js-primer/basic/class/#extends-usecase
をUseCaseのTODOに移動するとか

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/424

**Comment by azu** [comment]
UseCaseをバージョンごとにディレクトリを分ける書き方をするべきかどうか

**Comment by azu** [comment]
断片をディレクトリに突っ込んでいく感じ。

**Comment by lacolaco** [comment]
`...`

https://github.com/asciidwango/js-primer/blob/dbaa043e9c0b7a100c8f372de38090ce9fc4db1e/source/basic/math/README.md#L66

**Comment by lacolaco** [comment]
https://github.com/asciidwango/js-primer/blob/4b3c677d87e807a743f148f4df2828310c0df392/source/basic/string/README.md#L287

**Comment by azu** [comment]
- 引数: restパラメータ
- 配列: `...array` ???
- オブジェクト: `{ ...obj }` spread property

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/37767708-648bcf7e-2e0e-11e8-9a9f-80204e78d015.png)

https://github.com/tc39/proposal-object-rest-spread#object-restspread-properties-for-ecmascript

**Comment by azu** [comment]
spread operator -> spread syntax · Issue #425 · asciidwango/js-primer https://github.com/asciidwango/js-primer/issues/425

**Comment by lacolaco** [comment]
![image](https://user-images.githubusercontent.com/1529180/37767837-d4a03700-2e0e-11e8-8063-ac25176b2a6d.png)

**Comment by lacolaco** [comment]
https://github.com/asciidwango/js-primer/blob/master/source/use-case/nodecli/md-to-html/README.md#%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E8%A8%AD%E5%AE%9A%E3%82%92%E5%AE%9A%E7%BE%A9%E3%81%99%E3%82%8B-declare-default も`spread構文`でよい

**Comment by azu** [comment]
- [基本文法](https://github.com/asciidwango/js-primer/projects/1)
- [ユースケース](https://github.com/asciidwango/js-primer/projects/3)


残ってる章

**Comment by azu** [comment]
次は https://github.com/asciidwango/js-primer/issues/4 TODOをやる

**Comment by azu** [comment]
Node.js `.js` つけるに統一するとよさそうかも

**Comment by azu** [comment]
moduleは5の構文、 #329 をざっくり説明する

**Comment by azu** [comment]
todo #4 では.jsつけ忘れのエラーを紹介する

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/37768391-ceb99938-2e10-11e8-96bc-9e14f5bf9c2a.png)

- [ ] リンク切れ直す

**Comment by azu** [comment]
ビルトインオブジェクト とは何か?という説明

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/a2681b8bdf2aa0cfaf52df43b3bf0df52943da9b/source/basic/introduction/README.md#L31

**Comment by azu** [comment]
https://github.com/nodejs/Release 10は5月

**Comment by azu** [comment]
`fs.promise` は #94 なしで

**Comment by azu** [comment]
ターゲット Node.js LTS 8
http://node.green/

**Comment by azu** [comment]
privateについて
https://github.com/asciidwango/js-primer/issues/422#issuecomment-375278092

**Comment by azu** [comment]
\nと\tを具体的にして、エスケープシーケンスとは〜と簡単に書く。
 #372

**Comment by azu** [comment]
`\\` エスケープが必要になるものについてを文章として書く。
1行ぐらいのやつ。
 #372 はそれで解決できそう

**Comment by azu** [comment]
5月11日(金)
