### ISSUE TITLE
spread operator -> spread構文

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#425]
spread operatorとは呼ばないことにする #420 

- 引数: `fn(...args)` : restパラメータ
- 配列/文字列: `...array` : spread 構文
- オブジェクト: `{ ...obj }` : spreadプロパティ

に統一

**Comment by azu** [comment]
- [ ] Math
- [ ] String
- [ ] #349

**Comment by azu** [comment]
> オブジェクトのデフォルト値を明示的な値で上書きするときにはRest/Spreadプロパティを使うと便利です

https://github.com/asciidwango/js-primer/pull/351

safe

**Comment by lacolaco** [comment]
safeだけど一貫しておいたほうがよさそう

**Comment by azu** [comment]
- 引数: `fn(...args)` : restパラメータ
- 配列: `...array` : spread 構文
- オブジェクト: `{ ...obj }` : spreadプロパティ

に統一
