### ISSUE TITLE
Does not have a meta description 

### ISSUE THREAD

**Issue by nd-02110114** [asciidwango/js-primer#429]
Lighthouseをやってみたところ、以下のようにSEOのところで怒られていました
* Document does not have a meta description 

調べたところ、meta descriptionはSEOの結果には直接繋がないようなので、
そんなに重要なところでもない気がしますが、一応気になったのでIssueにしてみました。

<img width="1199" alt="2018-03-23 0 09 48" src="https://user-images.githubusercontent.com/17228098/37806241-475a3e44-2e82-11e8-8745-61076119a7f1.png">

**Comment by azu** [comment]
GitBookは [Front Matter](https://toolchain.gitbook.com/pages.html "Pages and Summary · GitBook Toolchain Documentation")にdescriptionを入れるとmetaを作って見れるみたいですね

```
---
description: This is a short description of my page
---
```

**Comment by azu** [comment]
descriptionはGoogleに表示されるという意識で書く感じになりそう。
[【2018年版】meta descriptionの最適な長さは「300文字」または「グーグル任せ」か | Moz - SEOとインバウンドマーケティングの実践情報 | Web担当者Forum](https://webtan.impress.co.jp/e/2018/02/19/28312)

結構長いのか。
章の最初に書いてるやつは前後の文脈が入ってしまってるから、章の目的を書いていくのがいいのかな。フォーマットさえきまればあとは作業的に埋めていく感じか。

**Comment by azu** [comment]
第一部については全部入れた
第二部についてはまだ全部は入ってない。

**Comment by azu** [comment]
#676 でユースケースもそれぞれ追加することになった。

**Comment by azu** [comment]
これはおそらく完了。後はテストを追加して終わり

**Comment by azu** [comment]
- [ ] テストを https://github.com/asciidwango/js-primer/blob/master/test/front-matter-test.js に追加する
