### ISSUE TITLE
基本文法では`var`を使う

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#46]
`let`や`const`はコンソール内だと、二重定義することができないためコピペして確認するのは不向きとなっている。

![es6book 2016-06-20 22-09-14](https://cloud.githubusercontent.com/assets/19714/16195243/a1bfafd8-3733-11e6-9fe7-adfa08b048c5.png)
## やること

そのため、 #17 基本文法は `var` を利用するということを明記する。
逆にユースケースでは積極的に `const` を使うということを明記する。
#15 の該当記述を修正する。

**Comment by azu** [comment]
#55 で基本文法はこの方向で同意を貰った

**Comment by azu** [comment]
これの問題点はやっぱり `var` を助長してるように見えてしまうという点かー。
ウェブ版は毎回クリーンなRealmを作れば解決できるけど、REPLがなー

**Comment by laco0416** [comment]
#263 でconstに統一したいという流れ

**Comment by azu** [comment]
統一した
