### ISSUE TITLE
Website: SWキャッシュが更新されているならリロードボタンを表示する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#466]
#431 
恐らく今アクセスした時に更新があっても前回のキャッシュがでている気がする。([Cache First](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#network_first_network_falling_back_to_cache))
このときにキャッシュが更新されるので、もう一度リロードすると最新版になる。

なので、更新がある場合はページ下部にリロードを促す通知を表示するとよさそう。

https://developers.google.com/web/tools/workbox/guides/advanced-recipes

**Comment by azu** [comment]
もしくは、 Network First にするとかでもよさそう?(できるのかな)

**Comment by nd-02110114** [comment]
@azu 
UX的にも、Network Firstにするのが僕も良さそうな気がします〜

こんなかんじで、今回の場合は`js,css,html`の場合は、
NetworkFirstにするといい感じかもしれません

```js
workbox.routing.registerRoute(/\.(jpg|png|svg|gif|woff|ttf|eot)/, workbox.strategies.cacheFirst({ cacheName: "assets", plugins: [new workbox.expiration.Plugin({"maxAgeSeconds":1209600})] }), 'GET');
```

**Comment by azu** [comment]
@nd-02110114 なるほど、Network Firstにできるならそれが良さそうですね。
