### ISSUE TITLE
Node.jsでHello World: Node.jsのバージョン

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#475]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/nodecli/helloworld/README.md

> 最新LTS版であるバージョン6.9系
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/use-case/nodecli/helloworld/README.md#L30 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/use-case/nodecli/helloworld/README.md#L30>

#454 でNode.js 8.x系のLTSじゃないと使えない `npx` を使うので、ここも合わせ更新する。
ここ変数的な感じだから、GitBookに変数を定義してそれを使ったほうがいいかもしれない。

- ブラウザ
- Node.js
- npx

など

**Comment by azu** [comment]
#496 で `{{esversion}}` という変数を導入した。
同じように Node.js の `{{nodeversion}}` とか定義するとよさそう。

**Comment by lacolaco** [comment]
setup-local-envの修正も終わりました
