### ISSUE TITLE
commanderのparse結果がbooleanでなくstringで格納されており意図した結果が得られない

### ISSUE THREAD

**Issue by yukihane** [asciidwango/js-primer#484]
(文中、分かりにくい表現があったとしたら、それは単に私がJavaScriptを理解していないだけだと思います。お手数おかけします。)

https://asciidwango.github.io/js-primer/use-case/nodecli/md-to-html/
において、

    $ node main.js --gfm false sample.md

というコマンド例が記載されています。
(特に補足が無かったので引っ掛け問題的なものではなく)`gfm`オプションをoffにする意図のコマンドだと理解しましたが、実際には`false`を指定しようが`true`を指定しようがGFMとして解釈されていました。

    $ node main.js --gfm "" sample.md

とすることで`gfm`オプションを`off`にした結果を得られました(が、指定方法として不自然なので、これはおそらく意図した設計では無いと考えました)。

**Comment by azu** [comment]
報告ありがとうございます。
たしかにfalseを渡すのは変ですね。

/cc @lacolaco

**Comment by lacolaco** [comment]
たしかに `--no-gfm` がただしそう

**Comment by lacolaco** [comment]
`--no`の説明するの本質的じゃないので、gfmもデフォルトでfalseにしておいて、値なしで `--gfm` だけ渡せばtrueになるという説明にします
