### ISSUE TITLE
Array/配列

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#49]
<span class="co-highlight" data-internal-link="/repo/asciidwango/js-primer/17">#17</span> 基礎文法/オブジェクト

配列についての章。

**アウトライン**:

- https://github.com/asciidwango/js-primer/blob/master/source/OUTLINE.md#%E9%85%8D%E5%88%97

**Comment by azu** [comment]
Arrayのメソッドについては事前に色々説明している #68 
**Arrayオブジェクト** というタイトルを見た時に何が期待されるかを考える必要がありそう。
#4 TODOアプリでも配列を使ってるので、なぜ配列なのか、逆になぜ◯◯ではないのかという事を書いていった方がユースケースが出てくるかも。

Arrayのメソッド紹介をどこまで自然にやるかが問題になりそう。
多分メソッドというよりもArrayとしての性質を使うためのメソッドを紹介するという流れにしたい。
(rangeとか微妙に足りないやつをどうしようかな)

`Array.prototype.reduceRight()` とか以外大体使うような気がしている。
後は `length` の特性を解説するべきかどうかという

**Comment by laco0416** [comment]
ここに限った話ではないけど、表記的には `Array.prototype.map` でいくんですかね？ `Array#map` みたいなJavaっぽい書き方もありますが
これってどこかにまとめられてましたっけ

**Comment by azu** [comment]
@laco0416 まとまってないので、決めて。

```
forEachメソッド
Array#forEach
array.forEach
Array.prototype.forEach

どれかの表記にまとめたい感じがする。
https://github.com/asciidwango/js-primer/pull/80#discussion_r70064981
```

**Comment by laco0416** [comment]
サンプルコードベースで説明するなら `array.forEach` が一番自然な気がする。追加の説明がいらないし
でもMDNとかで調べようとすると https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/map はArray.prototype.mapだから、Array.prototype.forEach がarrayのインスタンスメソッドを表してるってことを書いてないとどのみち困りそう。
`#`はない方向でよさそう

これはprhでしばれるのかな…

**Comment by twada** [comment]
インスタンスメソッドとクラスメソッドのある言語では

- `Array#forEach` はインスタンスメソッド
- `Array.forEach` はクラスメソッド

という書き分けをよく見ますね

**Comment by azu** [comment]
http://azu.github.io/promises-book/#_%E8%A1%A8%E8%A8%98%E6%B3%95

> インスタンスメソッドを instance#method という表記で示す。
> 
>     例えば、Promise#then という表記は、Promiseのインスタンスオブジェクトの then というメソッドを示しています。
> 
> オブジェクトメソッドを object.method という表記で示す。
> 
>     これはJavaScriptの意味そのままで、Promise.all なら静的メソッドの事を示しています。
> 
>

**Comment by azu** [comment]
`Object#instance` はいずれにしても触れたほうがよさそうな気がする。
普通に他の文章でも出てくることがあるし、JavaScriptだと結構見かけるので。

> Using a number sign (#) has emerged as a popular convention for describing prototype methods. For example, you will often see Car.prototype.shift written simply as Car#shift.
> -- Lerning JavaScript 3rd

ただ、[tc39/proposal-private-fields: A Private Fields Proposal for ECMAScript](https://github.com/tc39/proposal-private-fields "tc39/proposal-private-fields: A Private Fields Proposal for ECMAScript")が仮に入ったらこの記法どうなるんだろ的なのがよぎった。

**Comment by azu** [comment]
http://exploringjs.com/es6/ は

    C constructor
    Static C methods
    C.prototype methods

で、クラスメソッドとprototypeメソッドはそれぞれそのままの表記。

- Array.from
- Array.prototype.forEach

文中のインスタンスメソッドは `map()` とか何もつけずに書いてる。

**Comment by azu** [comment]
どちらにしてもprhでは判定するの無理だと思う。
自分は Array.from とかはコードと言う認識なので、 backtickで囲むと思うし。
それ専用のルール書かないと厳しい。

**Comment by azu** [comment]
http://yshibata.blog.so-net.ne.jp/2016-08-13
API設計の基礎

Array で何となく思い浮かぶ話

**Comment by azu** [comment]
全体的基礎文法の前半(forとかの構文)は読み込み系の処理が多い気がする。
Arrayオブジェクトとかの各オブジェクトの章で書き込む処理を扱う際になにに気をつけるべきがテーマにおいたほうが良いのかも。
Arrayなら基本的にmutableである点とか、どうやったら読みやすいコードを書けるのかみたいな。
例えばnullチェックを不要にするにはとか

**Comment by azu** [comment]
push/pop、indexOf/find or includeの話
mutableなのでimmuableにしてみるslice,...,concatの話
scopeなtraveseをしてみるネストした配列

**Comment by azu** [comment]
クリーンコード p159

- nullを返さない
- nullを渡さない

`return null` or `return []` の話

**Comment by azu** [comment]
[new Array(len)と[undefined, ...]の違い - Qiita](http://qiita.com/s-shin/items/88b2b6d4387312fe000a "new Array(len)と[undefined, ...]の違い - Qiita")
これ結構面白い挙動だなー。Rangeみたいなことをやろうとしてハマることがありそう。
Array#fillが有用なケース

**Comment by azu** [comment]
- [意外すぎる"未定義"の配列とその挙動 - Qiita](http://qiita.com/le_panda_noir/items/80fc46078e43c01cf928)
- [意外すぎる"未定義"の配列とその挙動 - Panda Noir](http://panda-noir.hatenablog.jp/entry/2016/04/06/190000)

疎な配列の文章表現が結構難しい。
プロパティのキーそのものがないということと値がない(undefined)と区別するうまい表現をしないといけない

**Comment by azu** [comment]
- [Gozala/antimutable-array: Immutable alternatives to built-in array operators](https://github.com/Gozala/antimutable-array)
- [Pure javascript immutable arrays](http://vincent.billey.me/pure-javascript-immutable-array)

**Comment by azu** [comment]
Array#copyWithIn　について調べてたけど、普通の人が使うユースケースが分からない。。
これTypedArrayからきてるのかな

- [Array.prototype.copyWithinが実装された - JS.next](http://js-next.hatenablog.com/entry/2015/04/26/192005)
- [Firefox 32(Nightly) で Array.prototype.copyWithin が実装された - hogehoge @teramako](http://d.hatena.ne.jp/teramako/20140607/p1)
- [18. New Array features](http://exploringjs.com/es6/ch_arrays.html)
- [ES6 Array Extensions in Depth](https://ponyfoo.com/articles/es6-array-extensions-in-depth)

**Comment by azu** [comment]
[JavaScript標準ライブラリの使い方超入門（3）：JavaScriptで配列を扱うArrayとスタック、LIFO、FIFOの基本 (1/6) - ＠IT](http://www.atmarkit.co.jp/ait/articles/1609/01/news013.html "JavaScript標準ライブラリの使い方超入門（3）：JavaScriptで配列を扱うArrayとスタック、LIFO、FIFOの基本 (1/6) - ＠IT")
メソッドの分類を見てた

**Comment by azu** [comment]
ひとまずざーと書いてみた
[JavaScriptの配列のパターン | Web Scratch](http://efcl.info/2016/10/11/array-patterns/ "JavaScriptの配列のパターン | Web Scratch")
ここから色々削ったり、順番を整理したり説明を書いたりしたらできるかな。
参照型のところがちゃんと理解できてないからか上手く説明できなかった感じがする。
https://github.com/asciidwango/js-primer/issues/145 で一度説明してから、Arrayではもう一度触れ直す感じかな

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/source/OUTLINE.md#%E9%85%8D%E5%88%97
Arrayのアウトラインをここに書いてるけど、結構広い感じ。
書きながらアウトラインへ反映を繰り返してると、だんだん統合されてくる。

**Comment by azu** [comment]
やりたいこととしては [十一章第一回　配列 — JavaScript初級者から中級者になろう — uhyohyo.net](http://uhyohyo.net/javascript/11_1.html "十一章第一回　配列 — JavaScript初級者から中級者になろう — uhyohyo.net") が近いのかもなー。

アウトラインベースで書き始めてみて、大体以下の3つが書きたいんだなと思ってきた。

- 基本的なメソッド(破壊的なやつばかり)
- コピー、破壊的じゃないメソッドとそれを推奨する理由
- 配列のパターン(メソッドチェーンとか高階関数、`return []`)

2番目のやつが異常に難しくて納得できるように書くのが厳しい感じ。
破壊的なメソッドをそのままつかちゃうと変数の名前から意味が抜けていくとか、読むときに動きをトレースする難しさとかがあるという感じの話になる。
配列はやっぱりMutableとImmutableがごちゃまぜ感が辛くて、それをどうにかするため LodashとかUnderscoreみたいなutilライブラリが異常な数あるんだなーという感覚。
(直に扱うのが難しい場合はライブラリを使いましょうという感じのありといえばありかな)

**Comment by azu** [comment]
ES5でArray subclass

[How ECMAScript 5 still does not allow to subclass array — Perfection Kills](http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array/ "How ECMAScript 5 still does not allow to subclass array — Perfection Kills")

**Comment by azu** [comment]
[javascript - Object.assign()の評価タイミング（？）について - スタック・オーバーフロー](https://ja.stackoverflow.com/questions/34004/object-assign%e3%81%ae%e8%a9%95%e4%be%a1%e3%82%bf%e3%82%a4%e3%83%9f%e3%83%b3%e3%82%b0-%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6 "javascript - Object.assign()の評価タイミング（？）について - スタック・オーバーフロー")

Array#fill({}) の動作 プリミティブ値以外を渡すことを考えたことなかったのでよくよく考えるとそうなのかー

**Comment by azu** [comment]
https://employment.en-japan.com/engineerhub/entry/2017/07/10/110000 
これを読んでいて、先にImmutable、mutableの話をするべきかを考えていたけど、
やっぱり先にそういう違いがあるという話をしないと分かりにくいなという感じがした。

先に違いあることについて説明 + 各メソッドではこれは破壊的ですとか書いていくスタイル

**Comment by azu** [comment]
Array-likeという用語 使わなくても普通にでてくるから、意味は理解できないと駄目かなー
![image](https://user-images.githubusercontent.com/19714/28322860-2d523930-6c12-11e7-9fb2-ce9e4af0a435.png)

**Comment by azu** [comment]
コラム的な枠でもいいかなーと思ってきた

**Comment by azu** [comment]
修正は別途Issueを
https://asciidwango.github.io/js-primer/basic/array/
