### ISSUE TITLE
次に何をするか: 参考リンク集

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#510]
From #492 

> 次に何を読めばいいかという。 リンク集的なものをウェブに作って、本からはリンクを貼るみたいな感じにする 

鮮度的に書籍に乗せるには難しいものを集めたページを作成して、書籍からこのページを参照する。

- ESLint from #142 
- クロスブラウザ対応/違い
- MDN
- Google

**Comment by azu** [comment]
ユースケースの延長線にあるものをベース。
lint、セキュリティ、パフォーマンス、CORS、ブラウザ、Node ドキュメント、Proposal

**Comment by azu** [comment]
ホスティングサービスの紹介

- gh-pages
- netlify
- firebase
- now.sh

**Comment by azu** [comment]
playground/online editor

- jsfiddle
- jsbin
- codesandbox
- repl.it

**Comment by azu** [comment]
新しい機能

    caniuse
    compatiblity
    node.green
    mdn
    chromestatus.com

**Comment by azu** [comment]
[Learn JavaScript](https://learnjavascript.online/)
練習問題を大量にときたい人はこのサイトすごく良さそう

**Comment by azu** [comment]
JavaScriptでやれることを大雑把に並べて興味を持ったものを調べてみようみたいな話がいいような気がする。
最近Rustを学んだけど、その後何をすればいいかって何ができるかを知らないと判断できなさそうだなと思った。
JavaScriptは大体なんでも出来るような感じではある(最適かは別として)ので、その辺を並べてみて興味があるものを選んで行くのがいい気がした。

実行プラットフォームみたいな感覚のまとめみたいのが欲しい
(基本的にその他の選択肢があるから"など"って付くけど)

- ブラウザをカスタム: 拡張機能
- ウェブサイト: JavaScript
- IoT: [Johnny-Five](http://johnny-five.io/)、Arduino、Tessel、obniz
- サーバ: Node.js
- Serverless: [Serverless Framework](https://github.com/serverless/serverless)、Lambda, Cloud Functions
- CLI: Node.js
- デスクトップアプリ: Electron, NW.js
- OSスクリプト:　WSH、JXA
- モバイル: React Native, Weex
- エディタ: VSCode, Atom
- ML: Tensorflow.js、Python
- 3D: WebGL, three.js
- VR: WebXR

**Comment by lacolaco** [comment]
source/appendixを作る

**Comment by lacolaco** [comment]
なんかもともとは eslintへの導線置きたいよねって話だった気がするけどプラットフォームの話となると書き方がぜんぜん浮かばないな… azuさんの中でなんとなく浮かんでるならヒアリングするより直接書いてもらったほうが早い気がした
