### ISSUE TITLE
文章が途中で切れている

### ISSUE THREAD

**Issue by maechabin** [asciidwango/js-primer#529]
## 該当ページ

- <https://asciidwango.github.io/js-primer/basic/object/#merge>

## 説明

```
第一引数には、空のオブジェクトではなく、既存のオブジェクトを指定することもできます。 しかし、次のコードを見ると第一引数に指定されたobjectA
```
「オブジェクトのマージ」のところの上記の説明文が途中で切れてしまっているように思われます。たまたま見つけたので、お知らせします。

**Comment by azu** [comment]
ご報告ありがとうございます。修正しました #550
