### ISSUE TITLE
2018-09-06 ミーティングアジャンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#531]
<del>2018年8月24日</del><ins>2018年9月6日</ins>のミーティングアジェンダ

**Comment by azu** [comment]
CI 

- Travis CIとかNetlifyとかが動いてない
- Integrationが切れている感じ
- @azu 権限持ってない

ドメイン

- ウェブサイトを独自ドメインに移行 #528

**Comment by azu** [comment]
まだIssue化してないような残りを整理する

- はじめに
  - 本書の目的 https://asciidwango.github.io/js-primer/intro/goal/
  - 読者対象 #461 
  - 動作環境
- ...

**Comment by azu** [comment]
2018-08-24: 延期なので日付をずらす

**Comment by lacolaco** [comment]
#534 
書き始めようとしたけど全然筆が進まず… 書かなきゃいけないことが広くふわっとしてて、セクションの目的みたいなところがまとまらなくて止まってます

**Comment by azu** [comment]
---

ここからログ

---

**Comment by azu** [comment]
- Googleドメインをとって共同管理する
- リポジトリ名をリネームすると github.io のリンクが切れる

**Comment by azu** [comment]
そろそろおわりに近いので、残ってる細かいものをIssue化する

**Comment by azu** [comment]
残りで書かないといけないやつ

- [read-eval-print: コンソールの開き方について #85 ](https://github.com/asciidwango/js-primer/issues/85)
- 読者対象
- 動作環境
- 目的
- JavaScriptとは

**Comment by azu** [comment]
付録的なもの

- [ 次に何をするか: 参考リンク集 #510 ](https://github.com/asciidwango/js-primer/issues/510)

**Comment by azu** [comment]
https://github.com/google/WebFundamentals/blob/master/src/data/glossary.yaml

Googleの用語まとめ

**Comment by azu** [comment]
- 検索の仕方とか

**Comment by azu** [comment]
末尾の付録 リンク集しかないな

- 次に何をするか: 参考リンク集 #510

**Comment by azu** [comment]
- caniuse
- compatiblity
- node.green
- mdn
- https://www.chromestatus.com

**Comment by azu** [comment]
- https://webcompat.com/

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/267 は

- Node.jsのインストール方法の紹介
- Node.jsのprocessとかのグローバルオブジェクトの紹介
- ブラウザのグローバルオブジェクトとは異なる = 実行環境の違い
- `node main.js` でのNode.jsのスクリプト実行
- nodeバージョン、npmバージョン
