### ISSUE TITLE
2018年10月25日 ミーティングアジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#537]
2018年10月25日のミーティングアジェンダです。

- 日時: 2018年10月25日 19:30~

**Comment by azu** [comment]
- Asyncの進捗 #536

**Comment by azu** [comment]
- ドメイン移行 #528

**Comment by azu** [comment]
`この文は実行されません` の表示

```
// この文は実行されません
```

と

```
console.log("この文は実行されません")
```

が混ざっているので統一したい

**Comment by azu** [comment]
残り

- [基本文法](https://github.com/asciidwango/js-primer/projects/1 "基本文法")
- [ユースケース](https://github.com/asciidwango/js-primer/projects/3 "ユースケース")

今週やっていた他のやつ

- [Until Review](https://github.com/asciidwango/js-primer/projects/4)

**Comment by lacolaco** [comment]
https://github.com/asciidwango/js-primer/pull/534
Node.js実行環境のセクション、ラフに書いたけどどこを掘り進めるべきかわからなくて止まってます

**Comment by azu** [comment]
----

ここからログ

----

**Comment by azu** [comment]
> `この文は実行されません` の表示

- コメントに変更する
- テスト時はthrow文に変えて実行されないことを明示する

**Comment by azu** [comment]
非推奨の機能からArgumentsを消す。
関数のところへ移行する。

https://github.com/asciidwango/js-primer/issues/274 
https://github.com/asciidwango/js-primer/issues/507

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/pull/534

**Comment by azu** [comment]
ツールとしてのNode.jsの使い方の説明?だけをする

**Comment by azu** [comment]
必要なのは

- ajaxでローカルサーバを建てるためにnpxを使えるようにする

**Comment by azu** [comment]
https://www.npmjs.com/settings/js-primer/packages
ここに @js-primer/hello-world を使える。

**Comment by lacolaco** [comment]
ソースコードとGitHub URL を添えて
`npx @js-primer/hello-world`  

ローカルサーバーを npxで立ち上げるよ、の説明

**Comment by azu** [comment]
- Node.jsインストール
  - npx
- Ajax
- Node CLI
  - Node.jsの環境オブジェクト
- Todo
  - module

**Comment by lacolaco** [comment]
Node.jsインストールの章というよりは、アプリケーション開発の準備　のセクション

**Comment by lacolaco** [comment]
Node.js hello worldはCLIの章でやる

**Comment by azu** [comment]
GitHub https://github.com/js-primer

**Comment by lacolaco** [comment]
各ユースケースの1ページ目で アプリケーション開発の準備 への参照

**Comment by azu** [comment]
[次に何をするか: 参考リンク集 · Issue #510 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/510)

**Comment by azu** [comment]
https://github.com/tc39/proposal-temporal

**Comment by azu** [comment]
全体のページ数はあんまり気にしないで、章ごとのバランスを見直す。

**Comment by azu** [comment]
https://jsprimer.net/basic/math/ はDateぐらいにあっていい。

**Comment by azu** [comment]
https://jsprimer.net/basic/string/ をもっと後ろに持っていく。

**Comment by azu** [comment]
https://jsprimer.net/basic/string/
アプリケーションよりの使い方になっているのでJSONとかそれぐらいの位置でもいいのでは

**Comment by lacolaco** [comment]
Date, Math, 文字列操作、JSONあたりはユースケース寄りのほうがなだらかに登っていけそう

**Comment by azu** [comment]
なだらかな難易度設定にしていきたい。

**Comment by azu** [comment]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/19714/47497662-c6b0c380-d895-11e8-881a-f04234864db3.png">

大体 900PV/day

**Comment by azu** [comment]
次回は11月29日(木) 19:30 ~
