### ISSUE TITLE
Google Apps Scriptについて言及するべきではないか

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#558]
## リクエスト/提案内容

Google Apps ScriptはMicrosoft Officeと競合関係にあるといえなくもないGoogle ドキュメントのマクロとしてや、単体でちょっとしたサーバーのようなものを作れるような環境です。

これまで事実上オンライン上のエディタで編集する一択、ES3すらやや怪しい標準対応状況だった開発環境も、2018年に入って[clasp](https://github.com/google/clasp/)が登場し、(コードサイズの制約が極めておおきいものの)、普通にバベったりwebpackしたりできるようになりました。
ref: [Google Apps Script をローカル環境で快適に開発するためのテンプレートを作りました - Qiita](https://qiita.com/howdy39/items/0e799a9bfc1d3bccf6e5)

そこで、どこかでGoogle Apps Scriptについて言及する価値があるのではないかという提案です。

**Comment by yumetodo** [comment]
# Google Apps Scriptの`global`に対する制約

Node.jsと同じく`global`オブジェクトを使うが、Spreadsheetsなどから関数を呼び出すには関数が

```js
function foo(){}
```

のようにfunctionキーワードを用いてglobalスコープで定義された関数しか呼び出せない。

このとき定義が空であとで`global`経由でoverwriteして実装を注入してもよい。

上記Qiita記事のテンプレートでは[gas-webpack-plugin](https://github.com/fossamagna/gas-webpack-plugin)を用いてこれを回避している。

**Comment by azu** [comment]
GASは何か作ることが目的ツールなので[本書がやらないこと](https://jsprimer.net/intro/goal/)でかつツールを使わないとES3環境なので[本書の目的](https://jsprimer.net/intro/goal/)からも逸れていそうです。
[GASの既存の本](https://www.amazon.co.jp/s/ref=nb_sb_noss?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&url=search-alias%3Ddigital-text&field-keywords=Google+Apps+Script)を見ても需要は実務よりなので、スコープ外な感じがしますね。
BabelやTypeScriptすらちゃんと紹介してない現状を考えるとGASやclaspについて触れる余裕がないことや、GASというオープンではないものを扱うのは予測が難しいこと、もっとユーザーが多い[ExcelがJavaScriptをサポートしている](https://developer.microsoft.com/en-us/office/blogs/azure-machine-learning-javascript-custom-functions-and-power-bi-custom-visuals-further-expand-developers-capabilities-with-excel/)ことと対比の必要がでてくることなどから難しそうです。
