### ISSUE TITLE
JavaScript Object Notations -> JavaScript Object Notation

### ISSUE THREAD

**Issue by ryo-a** [asciidwango/js-primer#565]
## 該当ページ

- [ ] https://jsprimer.net/basic/json/#what-is-json

## 説明

JavaScript Object Notation**s** ではなく JavaScript Object Notation です。( http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf 5ページ参照)
細かい指摘ですみません。

**Comment by azu** [comment]
ありがとうございます！
修正しました
