### ISSUE TITLE
let と const について >> ループと反復処理

### ISSUE THREAD

**Issue by mimosafa** [asciidwango/js-primer#567]
for … in ならびに、for … of の例示コードの中で、key, value が const のもとで宣言されている(ように見える)のが、どうしても理解できませんでした。
コラムでその辺りの合点が得られるのかと期待したのですが、そうはいかず…
どうかその辺りのご解説をいただければ幸いです。

URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/loop/README.md

**Comment by azu** [comment]
@mimosafa フィードバックありがとうございます。

このケースだと`let i`なのに
```js
let total = 0; // 初期値は0
for (let i = 0; i < 10; i++) {
    total += i + 1; // 1...10
}
console.log(total); // => 55

```

次のケースだと`const key` となぜできるかという話ですかね?


```js
const object = {
    "a": 1,
    "b": 2,
    "c": 3
};
for (const key in object) {
    const value = object[key];
    console.log(`key:${key}, value:${value}`);
}
```

書いてるときに確か解説を一度入れようとして、きれいな解説が思いつかなくて結局入ったない感じがしますね。
(どこかにログが残ってないか探しましたがなさそうでした)

- [loop: for/for in/for of/while/do while · Issue #68 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/68)

原理的にはforループにかかれている`const key`の部分はループのたびに別々のスコープとなるため、毎回同じ名前で定義できるという感じですね。

例えば次のコードは`const item`に`1`、`2`、`3`と値が入ってループします。

```js
const array = [1,2,3]
for (const item in array) {
    console.log(item);
}
```

このループを擬似的に展開すると次のようになります。

```js
const array = [1,2,3]
// 1回めのループ
{ 
   const item = 1;
   console.log(item);
}
// 2回目のループ
{
   const item = 2;
   console.log(item);
}
// 3回目のループ
{
   const item = 3;
   console.log(item);
}
```

ループ内で定義した`item`は外から参照できないのも同じ理由です。

```js
const array = [1,2,3]
for (const item in array) {
    console.log(item);
}
// ここでitemを参照しようとしても、ループ内はブロックスコープで囲まれているからアクセスできない。
console.log(item); => Error
```


のように、forループごとに別々のブロック`{}`で実行されるため、おなじ`item`という名前で定義できる感じ
になります。
(ブロック`{}`があれば同じ名前が使えるのは、`let`や`const`はブロックスコープ https://jsprimer.net/basic/function-scope/#block-scope だからという話です)

一方で、最初の`let i` が`let`担っているのは、この`i`が`++` インクリメントされているからですね。
`const i = 1; i++`がエラーになるから`let`になっているという理由です。

```js
let total = 0; // 初期値は0
for (let i = 0; i < 10; i++) {
    total += i + 1; // 1...10
}
console.log(total); // => 55
```

`const for loop why` とかで検索すると多分いろいろな解説がでてくると思います。

* [JavaScript - loop内でconstはOK?｜teratail](https://teratail.com/questions/89800 "JavaScript - loop内でconstはOK?｜teratail")
* [ES6 Variable Declaration & For Loops — Why ‘const’ works in a ‘for…in’ loop but not in a normal…](https://medium.com/@mautayro/es6-variable-declaration-for-loops-why-const-works-in-a-for-in-loop-but-not-in-a-normal-a200cc5467c2 "ES6 Variable Declaration & For Loops — Why ‘const’ works in a ‘for…in’ loop but not in a normal…")

ここで解説がなかったのは、コードの見た目と動きが違ったり、スコープの概念を知ってないと理解できない挙動だったりするからですね…
なんとかコラムで解説できないかを考えてみます。

**Comment by mimosafa** [comment]
ありがとうございます！理解できました。
「関数とスコープ」で解説されてましたね。コラムでなくてもその導線が提示されていれば（私的には）良いと思います。

**Comment by azu** [comment]
#852 で「関数とスコープ」への動線を追加しました
