### ISSUE TITLE
npm の --global flagについての説明

### ISSUE THREAD

**Issue by ryo-a** [asciidwango/js-primer#574]
## 該当ページ

- [アプリケーション開発の準備](https://jsprimer.net/use-case/setup-local-env/)

## リクエスト/提案内容

最近のパッケージマネージャを扱ったことがある人であれば、 global が何を言わんとしているか分かると思うのですが、本書の対象としている層は必ずしもそうでないように思えます。
（少なくともデフォルトではglobal / local を指定する文化のない言語の経験者等）
ざっくりとしたものでもよいので、解説があると理解の助けになるのではないでしょうか。

解説が記述されるとしたら実際に npm を積極的に操作させることになる[コマンドライン引数を処理する](https://jsprimer.net/use-case/nodecli/argument-parse/)のページでも良いかもしれません。

## 期待する結果

本書の趣旨からして、パッケージマネージャの概念などを詳説することは避けるにしても、この時点（あるいは「コマンドライン引数を処理する」のページ）で `--global` が何であるかを示す記述になること

**Comment by lacolaco** [comment]
#591 をマージしたので、Node CLIのユースケースの方で重複している説明を参照へ書き換える

**Comment by lacolaco** [comment]
Ajaxアプリケーションのlocalhostの部分も参照へ置き換え、 ローカルサーバーを立ち上げるコマンドを追記する

**Comment by lacolaco** [comment]
多分終わり？

**Comment by ryo-a** [comment]
@azu 
確認が大変遅れて申し訳ありません。

#591 確認させていただきました。
迅速なご対応ありがとうございます。
