### ISSUE TITLE
値の評価と表示: 構文エラーの説明

### ISSUE THREAD

**Issue by miy4** [asciidwango/js-primer#580]
## 該当ページ

https://jsprimer.net/basic/read-eval-print/

## 説明

> そのため、構文エラーの多くは書き方が間違っているため発生しています。

という記述が必要か、気になりました。

- 「そのため」「間違っているため」と一つの文に「～ため」が二度現れて、何が原因でエラーが発生しているかわかりづらくしている
- そもそも「構文エラーはプログラムの記述の誤りで発生する」という記述が同じ段落で二度現れている

と考えたからです。

**Comment by yumetodo** [comment]
「そのため」より「つまり」じゃなかろうか、文脈的に

**Comment by azu** [comment]
> そのため、構文エラーの多くは書き方が間違っているため発生しています。

この文自体がいらない気がしますね。
直します。
