### ISSUE TITLE
変数と宣言: 「定数」という語

### ISSUE THREAD

**Issue by c01o** [asciidwango/js-primer#586]
## 該当ページ

- [ ] https://jsprimer.net/basic/variables/

## 質問内容
`const`の解説では、

> `const`は**再代入できない変数**を定義するキーワードです。

とされています。

変数なのに変更できないというのは直感に反した悪いネーミングですし、[MDNのように](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/const)「定数」という語を使えばよいのではと思います。このリポジトリを「定数」で検索してもヒットしないところからすると、意図的に「定数」という語を避けているのでしょうか？

**Comment by azu** [comment]
ちょっとむずかしい問題ですね。
なんとなく"定数"とすると微妙な違和感がでるケースがある気がして、無意識的に避けている気がしますね。

- [定数](https://ja.wikipedia.org/wiki/%E5%AE%9A%E6%95%B0)というと`const TEN = 10`のように特定の値を定義するものととらわれる可能性がある
  - 歴史的に`const`がなかったときは、`var TEN = 10` のように大文字で書いた変数を**定数**ということも多かった(多分実際に今もそう言われている
- `const obj = {}` の`obj`は**定数**というと少し違和感を感じてしまう
  - おそらく数学的な定数とはことなるconstantsの意味合いになっている
  - プリミティブ型なら定数と言いやすいが、オブジェクト型が来ると定数というより再代入できない変数という意味合いが強く感じてしまう

なので、`const`の性質(再代入できない変数)という説明を使っているのだと思います。

定数というと、値そのものが変更できないイメージが個人的にはありますが、
`const`で定義したオブジェクトという値そのものは変更ができるので、
定数という言葉を避けているのかものかもしれないです。

```js
// objは定数
const obj = {};
obj.a = 1;
console.log(obj); // => { a: 1 }
```

**Comment by yumetodo** [comment]
>定数 ∋ 再代入できないで定数のほうが意味の範囲が広いのかなと思っています。

むしろ逆では・・？


C++でいうならJavascriptのconstは

```cpp
const void* obj;
```

であって、`constexpr`ではないといえばいいでしょうか。

**Comment by LightSpeedC** [comment]
以下の様なコードをよく書きますので、定数とは呼べませんね。
私も「再代入できない変数」「定数だけではない」と認識しています。

```js
const response = await getAsync('any async resource');
const { result, error } = response;
```

以下の様なコードなら `TIMEOUT` という変数を定数と呼んでもいいかも。
記述も大文字で記述することが多いです。

```js
const TIMEOUT = 30 * 1000; //  30 sec
```

最初のコードを大文字の `RESPONSE` などと書くと
違和感がありすぎます。とても定数とは言えないです。

```js
const RESPONSE = await getAsync('any async resource');
const { result, error } = RESPONSE;
```

それから以下の様なコードをよく書きます。
これも定数という雰囲気ではありません。

```js
const list = [];

list.push(data);
```

```js
const elements = [{name: 'John', age:20}, {name:'Jack', age:40}];

for (let elem of elements) {
    const { name, age } = elem;
    ...
}
```

`const` じゃなくて変数を修飾する `readonly` とか `final` とかの方が
合っているのかもしれませんが、言語の定義ですからね。

**Comment by yumetodo** [comment]
あぶない、私のコメントのC＋＋の例えが間違っていた。read-only pointer to objectの関係ですね。

```js
const arr = [1, 7, 3, 2, 1];
arr.push(0);
console.log(arr); // => [ 1, 7, 3, 2, 1, 0 ]
```

**Comment by azu** [comment]
📝 constの下にコラムを追加する

- JavaScriptでは`const`は再代入できない変数を定義するという違いが`let`に対してあるだけ
- 値には特に制限はない
- 変数名にも特に制限はない
  - Rustの[const](https://doc.rust-lang.org/std/keyword.const.html)みたいにコンパイル時に決まって変わることがない値ではなくて、JavaScriptにおいては実行時に値が決まるので`const`だけど変数みたいなもの
- 再代入できないので定数を定義するために利用もされるが、定数以外の任意の値でも普通に利用される
- const objectの問題については https://jsprimer.net/basic/object/#const-and-object でやっているのでここでは扱わない
