### ISSUE TITLE
関数と宣言: 引数の個数について

### ISSUE THREAD

**Issue by c01o** [asciidwango/js-primer#588]
## 該当ページ

- [ ] https://jsprimer.net/basic/function-declaration/

## リクエスト/提案内容

javascriptでは、引数によって関数が区別されません。例えば、ループと配列節のサンプルに見られるように
https://github.com/asciidwango/js-primer/blob/179ef67058a8df399a54b8b32c12c6309a709d89/source/basic/loop/src/break/some-even-example.js#L1-L5
とでき、余った引数は`arguments`に詰められるか、アロー関数の場合は単に捨てられます。

しかし、このことについて「関数と宣言」節を含むこれ以前のページで解説がありません。
特に上述した例では、`Array#some`は`(currentValue, index, array) => {}`の形のコールバック関数を取ると説明された直後なので、混乱を招きかねないように思います。

## 期待する結果

「関数と宣言」節、ないし他の適当な場所で解説する

**Comment by c01o** [comment]
@azu
関数の型に厳密だったりオーバーロードが存在したりする言語の経験者が混乱することを懸念しています。ですので、1.については
>単に値を受け取れないという話

よりもう少し踏み込んで、「仮引数の個数が型を定めるわけではない」みたいな話にしたほうが良い気もします。(個数が少ない場合`undefined`になる話は本書の範囲外か？)

2.については想定外の論点でした。関数が1st class objectであることは明記されているので、それで大丈夫ではないでしょうか

**Comment by yumetodo** [comment]
>(個数が少ない場合undefinedになる話は本書の範囲外か？)

それだとoptionalな引数はどう説明するのでしょうか？

**Comment by azu** [comment]
📝

- オーバーロードはJavaScriptになく、あくまで関数名でしか区別されない
  - TypeScriptにはあるから明示しておくとよさそう
  - [関数シグネチャ](https://developer.mozilla.org/ja/docs/Glossary/Signature/%E9%96%A2%E6%95%B0)という概念自体はあるが、シグネチャが異なるものが定義できるのではなく、あくまで関数名でしか区別されない
- 定義した関数のシグネチャと呼び出し方が異なる場合にどうなるかの説明をする
  - これが実行できるのがそもそも動的言語っぽさが強い気がするので、RubyとかPythonあたりを参考に考える
