### ISSUE TITLE
文字列: 章の再構成

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#598]
From #592 

前半はAPI、後半はUnicode, Code Point的に話を分ける。

- 簡単なAPI
  - String系
- 難しい文字コードの話
  - Code Point, Unicode

## 目的

APIとUnicodeの話が混ざっていると難易度が揺れすぎて読みにくくなっている可能性がある。
APIはAPIの話として書いて、話を分けることで難易度の上がり方をゆるやかにする。

## Task

- [ ] 章構成の変更
- [ ] [HTML文字列をエスケープする](https://jsprimer.net/use-case/ajaxapp/display/#escape-html)の簡略化

----

- azu: あと[タグ付きテンプレート関数](https://jsprimer.net/basic/string/#tagged-template-function) ちょっとストーリーが長くて、削りたい
- laco: これはユースケースでやってることと被っている?
- azu: ([HTML文字列をエスケープする ](https://jsprimer.net/use-case/ajaxapp/display/#escape-html)をみながら)あんまり説明はしてなかった
- azu: もっと簡単な話にしたい
- laco: `String.raw`を作るまでにするとか
- azu: それでもよさそう。そうしたら半分ぐらいになりそう
- laco: あとはrawの代わりになにかを出すぐらい
- azu: rawの代わりに○で伏せ字にするとか

---

**Comment by yumetodo** [comment]
#188 では

>Unicodeを解説したいわけでもないので

という話でしたが、改めて見るとそのせいでかえって話がわかりにくくなっているのではという印象です。まず[Unicodeの4つの文字の定義](https://unicode.org/faq/char_combmark.html#7)から用語を整理して、次にUTF-16を扱う上でサロゲートペアの話をして、Javascriptでのcode unitとcode pointの扱いを整理したほうがいいのではないでしょうか。

---

ところで改めて読み返して気になった点です。

>符号単位（Code Unit）は、文字を構成する最小の単位ですが

最小単位はbyteです、Javascriptで扱えるかは知りませんが

>そこで、16ビットを2つ並べることによって扱える文字数を増やすエンコード方式がUnicodeに追加されました。

サロゲートペアのことを言いたいのだと思いますが、これだと常に2つ並べている事になっているのでは

>JavaScriptにおいては、この16ビット1つのことを符号単位（Code Unit）とよび

Unicode側の用語だと思うんですが、ECMAScript側で再定義しているんでしょうか

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/50641730-48b31c00-0fac-11e9-80f3-a1ca3c2a0321.png)
> https://learnjavascript.online/app.html?id=13

やっぱりこういう図あったほうが説明が簡略化しやすそうな気がする
