### ISSUE TITLE
イベントとモデル: TodoListModel.js の onChange の返している関数の意味

### ISSUE THREAD

**Issue by tabass** [asciidwango/js-primer#607]
## 該当ページ

https://jsprimer.net/use-case/todoapp/event-model/#event-emitter-todolist-model

## 質問内容
`src/model/TodoListModel.js`の`onChange`は以下のようになっていますが、

```js
    onChange(listener) {
        this.addEventLister("change", listener);
        return () => {
            this.removeEventLister("change", listener);
        };
    }
```

単に以下のような実装でも正常に動作するように思いました。

```js
    onChange(listener) {
        this.addEventLister("change", listener);
    }
```

`return`で`removeEventLister`を呼ぶ関数を返しているのには、どのような意味があるのか教えていただけますでしょうか。

**Comment by azu** [comment]
```js
const unlisten = onChange(() => { /* onChangeのハンドラ */ });
// onChangeのハンドラを解除する
unlisten();
```
というパターン向けに`removeEventLister`(登録したイベントリスナーを解除する処理)を返していた感じですね。
登録したイベントは解除しないとメモリリークの原因となるので、ちゃんと解除できるように作るのがいいのですが、正直このサンプルだとリロードで十分なのでそこまでいけてないという感じですね。

ホントは `mount`で `addEventLister` して
https://github.com/asciidwango/js-primer/blob/7c8a4448b3dc833a2748ff95f454ea7252348d63/source/use-case/todoapp/final/final/src/App.js#L42

`unmount`で `removeEventLister` するという対比構造にする予定で書いていたのですが、
`unmount`の部分が省略されてしまった残骸みたいなものになっていますね。
`return () => this.removeEventLister("change", listener);` の部分は消そうかなと思います。

**Comment by tabass** [comment]
ご回答ありがとうございます。本書のレベルは私にちょうど良く、たいへん勉強になっています。おかげさまで上記のやり取りが理解できるほどになってきたかと思います。ありがとうございます。
