### ISSUE TITLE
[コラム] undefinedはリテラルではない - undefinedには代入できない様です (node.js以外のブラウザ)

### ISSUE THREAD

**Issue by LightSpeedC** [asciidwango/js-primer#610]
## 該当ページ

- [ ] ページのURL https://jsprimer.net/basic/data-type/#undefined-not-literal

## 説明

最近(2018.12)のブラウザ(Chrome, Firefox, Edge, IE11)では `undefined` に代入できない様です。
コード例の`実行`でも結果は `undefined` でした。
ブラウザのF12キーで出たコンソール画面で `var undefined = 10;` とか実行しても代入できませんでした。
何度代入しても `undefined` という変数は `undefined` を返すようです。
`window.undefined = 10;` としても `window.undefined` は `undefined` が返されました。

node.jsでは `var undefined = 10;` は js-primer の記事の通り実行できました。

試した例は以下の通りです。

```js
undefined = 10; // ブラウザでもnode.js でも代入不可
var undefined = 10; // node.jsで可能!!! ブラウザで不可
window.undefined = 10; // ブラウザで不可
global.undefined = 10; // node.jsで不可
```

**Comment by azu** [comment]
サンプルコードが少し間違っている感じですね。

```js
function fn() {
  var undefined = 42;
  return undefined;
}
console.log(fn());
```

だと、どのブラウザでも`42`を返すと思います。

これの原理を解説するのは結構面倒くさい話がありますね。

- `undefined` へ代入しているのではなくて、そのスコープに対して`undefined`という変数を定義している
- 変数は[スコープチェーン ](https://jsprimer.net/basic/function-scope/#scope-chain)によって最も近いスコープの名前で解決される
- strict modeではない場合は`undefined`という変数名をエラーなく定義できてしまう

この理由により、`fn`関数内で`undefined`という変数を定義し直すことができてしまい、そのスコープ以下だと`undefined`が別の値を参照することがあるという感じの話ですね。

原理的には次のコードと同じですね。

```js
var undef = "globalなundefined"
function fn() {
  var undef = "localなundefined";
  return undef;
}
console.log(fn()); // => "localなundefined"
```

Node.jsではなぜ元のコードでうごくかはちょっと調べないとアレですが、たしかNode.jsは自動的に一番外側に関数があって、その中で処理されているのかもしれないです(未確認。REPLはそんな感じだった気がしますが、普通のコード実行もなるのが少し謎ですね)

このコラムは、`var undefined`ができてしまうので`undefined`はリテラルではないということが言いたいだけなのに、少しバットノウハウ的/歴史的なな話であんまりよくない感じがしてきました。

**Comment by azu** [comment]
コラムのコード例はとりあえず #611 で修正してきます。

**Comment by LightSpeedC** [comment]
納得しました。サンプルコードも動く様になりました。
関数スコープ内で `var undefined` に代入すると実現できますね。了解です。

node.jsがうまくいくのは、実行しているソースが関数スコープだからですね。

```js
console.log(arguments.callee + '');
```

を見ると、関数スコープ内で実行されている事が目視できます。
以下っぽいコードが得られます。

```js
function (exports, require, module, __filename, __dirname) {
    console.log(arguments.callee + '');
}
```

ご確認ください。
