### ISSUE TITLE
WeakMap の例について

### ISSUE THREAD

**Issue by masakichi** [asciidwango/js-primer#627]
## 該当ページ

- [ ] https://jsprimer.net/basic/map-and-set/#weakmap

## 質問内容
WeakMap について１つ目の例はなかなかわかりにくいと思います（一応初心者の私にとっては）。

```
// eventTargetの参照が変われば自動的にイベントリスナーが解放される
eventTarget = null;
```
この二行のコードの說得力はちょっと弱いと思います。`eventTarget` を `null` にして後一体どんなことがあったのかもっと具体的に説明すればいいと思います。

ちょっとネットの上で調べると、この例 https://github.com/ruanyf/es6tutorial/issues/362#issuecomment-292451925 を見つけた(`heapUsed` の値が変わった)。よりわかりやすいではと思いますので、此処に貼ります。

**Comment by azu** [comment]
WeakMap 1番目の例から少し具体的すぎるのが、わかりにくさの原因なようにも見えますね
もっと基本的なMapとWeakMapでの動作の違い(自動的に開放されない例)を出せるとよさそうですね。
(eventTargetは2番目の例にする感じで)

```js
const obj = { key: {} };
const map = new WeakMap();
map.set(obj.key, 1);
console.log(map.get(obj.key));
delete obj.key; // ここで obj.key が消された = どこからも参照されなくなった(WeakMapはweakな参照なので例外的) = JavaScriptエンジンはGCで解放してよくなった => WeakMapで参照してた場合は参照できなくなって undefinedになる というのを説明する
console.log(map.get(obj.key));
```

JavaScriptに`gc`関数はないので、`gc`関数なしで観測しやすい例があるとわかりやすくなるような気がします。

関連: 

- https://jsprimer.net/basic/function-scope/#memory-management
- http://es6.ruanyifeng.com/#docs/set-map#WeakMap

**Comment by masakichi** [comment]
わかりますけど
```
delete obj.key;
console.log(map.get(obj.key));
```
この例も問題があると思います。 `obj.key` は既に `delete` されちゃったので、当然 `obj.key` を再びアクセスするときには `undefined` になちゃう。なので、 `console.log(map.get(obj.key))` => `console.log(map.get(undefined))` になる。 `WeakMap` にかかわらず、最初から `const map = new Map()` にするのも同じ結果を得るのではないかと思います。

gc関数なしで観測しやすい例を提出するのはなかなか難しいよね。

**Comment by lacolaco** [comment]
#654 で修正しました
