### ISSUE TITLE
関数とスコープ or 変数: ブロックスコープの活用

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#630]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/function-scope/README.md

Rustの[ベクタ型 - The Rust Programming Language](https://doc.rust-jp.rs/book/second-edition/ch08-01-vectors.html)をみていて

```js
{
  const a = 1;
}
{
  const a = 1;
}
```

みたいにブロックで囲めば、同じ名前の変数を一つのファイルでたくさん書けるので、書く練習するのに便利そうだなと思った。
ブロックスコープの紹介のところでこれを教えておくと、HTMLファイルに書いて練習したりしてる人にとってよさそう。
ブロックスコープの話は少し遅いので、 https://jsprimer.net/basic/read-eval-print/ あたりでこのテクニックについて原理はともかく教えておくと便利そうな気がする。

**Comment by azu** [comment]
https://jsprimer.net/basic/read-eval-print/#repl-on-browser

ここが入れる場所としては適切

**Comment by azu** [comment]
https://jsprimer.net/basic/statement-expression/#block-statement

ここでやるのがよさそう。一見ブロック文の使いみちって無いけど、こういうことができるよって話にする(この章が退屈だし)

**Comment by azu** [comment]
## [コラム] 単独のブロック文の活用 {#isolate-block-statement}

次のようにブロック文を単独で書く機会はあまりありません。
単純に実行するだけなら、ブロック文がなくても同じ結果になるためです。

{{book.console}}
```js
{
    const count = 1;
    console.log(count); // => 1
}
```

しかし、単独のブロック文が役に立つ機会もあります。

次のコードでは、ブロック文で`const`キーワードの変数宣言を囲むことで、同じ名前なのに変数が宣言できています。

```js
{
    const count = 1;
}
{
    const count = 2;
}
```

通常では、`let`や`const`は同じ名前の変数を再定義するとエラーが発生します(詳細は「[変数と宣言][]」の章の「[`var`の問題][]」を参照)。
これは、それぞれのブロック文でブロックスコープが作成され、異なるスコープに同じ名前の変数を宣言することで変数の名前が衝突せずエラーにならないためです。
詳しい仕組みは「[関数とスコープ][]」の章で解説するため、まだ理解しなくても問題ありません。

この仕組みはREPLでのJavaScript実行で同じコードを何度も実行する際に役立ちます。
REPLで実行するコードをブロック文で囲むと、同じコードを繰り返して実行しても変数の再定義エラーとはなりません。
そのため、同じコードの一部を変更して実行する試行錯誤する際に覚えておくとよいテクニックとなります。

```
// REPLでの動作
» {
    const count = 1;
    count * 2;
}
2
» {
    const count = 1;
    count * 3;
}
3
```


ざっくり書いてみたけど、ちょっと余計に混乱させそうだな。
もう少し短く、テクニック的な部分だけにするべきか

**Comment by yumetodo** [comment]
もっとシンプルに

---

例えばREPLで同じコードの一部を変更して実行したりと、試行錯誤してプログラムを書いている時、

```js
const count = 1;
//中略
const count = 2;
```

のように`let`や`const`を用いて一度作った変数名を再利用したくなることがあります。しかしこれはエラーが発生します(詳細は「[変数と宣言][]」の章の「[varの問題][]」を参照)。こういう場合は次のように書き換えるとうまくいきます。

```js
{
    //新しく`count`を作る
    const count = 1;
}
// `count`はもう使えない
{
    //新しく`count`を作る
    const count = 2;
}
```

`{}`で囲まれた中で、`let`や`const`を用いて変数を定義しても、その外には影響しません(詳細は[関数とスコープ][]を参照)。

---

くらいでどうでしょう？

**Comment by azu** [comment]
たしかにそれぐらいの感じがよさそうですね

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/567 も地味にこの話だったんだな。

**Comment by yumetodo** [comment]
#850 見ました、良いですね！ 自分が書いたのより明瞭です。
