### ISSUE TITLE
モジュール: デフォルトエクスポートと関数宣言

### ISSUE THREAD

**Issue by foomin10** [asciidwango/js-primer#635]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/module/README.md

はじめまして。  
[デフォルトエクスポート 節](https://jsprimer.net/use-case/module/#default-export) の 3つ目のコードのコメント「関数の宣言はデフォルトエクスポートできない」がちょっと意味がわかりません。コードの内容と合っていないような気がします。

**Comment by azu** [comment]
```js
// 変数宣言はデフォルトエクスポートできない
export default const foo = "foo", bar = "bar";
```

コメントが間違っていて、コードは正しそうですね。

**Comment by azu** [comment]
```
// 変数宣言と同時にデフォルトエクスポートはできない
export default const foo = "foo", bar = "bar";
```
のように修正しました　#636
