### ISSUE TITLE
整数リテラルの16進数についての記載内容について

### ISSUE THREAD

**Issue by azhrarn105** [asciidwango/js-primer#680]
## 該当ページ

- <https://asciidwango.github.io/js-primer/basic/data-type/>

## 説明

> 数値（Number）> 整数リテラル > 16進数
 
の記載内容について  
`0x の後ろには 0から15までの数値`

とありますが、実際には  
`0x の後ろには 0から9までの数値、もしくはAからFまでのアルファベット`

が正しいのではないでしょうか？

**Comment by azu** [comment]
ご報告ありがとうございます。

小文字もOKなので、

> 0xの後ろには、0から9までの数値と"A" から "F"（大文字）と"a" から "f"（小文字）のアルファベット(アルファベットは大文字、小文字は区別されません)

とかですかね。

**Comment by azhrarn105** [comment]
ご確認ありがとうございます。
すみません、小文字についてのケアが足りませんでしたね。
ご提示頂いた内容で異存ありません。

サーバサイドばかりやっていて10年ぶりくらいにjsを触ることになり、  
貴サイトで学習を始めたところなのですが、  
丁寧にまとめて頂いていて大変助かっています。  
ありがとうございます

**Comment by azu** [comment]
#681 で書き直してみました。
https://jsprimer.net/basic/data-type/#integer-literal

**Comment by azhrarn105** [comment]
確認しました。
迅速な対応ありがとうございました。
