### ISSUE TITLE
Node.jsのCLIアプリ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#7]
Node.jsのCLIアプリで何か一つユースケースがあるといいのではないという話が #5 ででた。
具体的に何かは出てなかったので、考える必要がありそう。

/cc @laco0416

**Comment by azu** [comment]
Node.js バージョン管理ツールとElectronベースのインストーラーの議論があるのか。
https://github.com/nodejs/version-management
https://github.com/nodejs/installer

**Comment by azu** [comment]
[The Node Beginner Book » A comprehensive Node.js tutorial](http://www.nodebeginner.org/ "The Node Beginner Book » A comprehensive Node.js tutorial")
これ一応今もアップデートされてるんだな

**Comment by azu** [comment]
[JSPatterns.com » Blog Archive » Node shell scripting](http://www.jspatterns.com/node-shell-scripting/ "JSPatterns.com » Blog Archive » Node shell scripting")
今時めずらしいNode.jsの本当に入門的な記事が書かれてた

**Comment by azu** [comment]
[今時のフロントエンド開発2017 (2. 構築編) - Qiita](http://qiita.com/Lyude/items/c4250b6be4eeece90348 "今時のフロントエンド開発2017 (2. 構築編) - Qiita")
npmのオプションテーブルわかりやすい

**Comment by laco0416** [comment]
とりあえず完了

**Comment by azu** [comment]
そういえば `console.assert` は https://asciidwango.github.io/js-primer/basic/implicit-coercion/#%E3%82%B3%E3%83%A9%E3%83%A0-nan%E3%81%AFnot-a-number%E3%81%A0%E3%81%91%E3%81%A9number%E5%9E%8B のコラムで軽く触れていることを思い出しました

**Comment by lacolaco** [comment]
Object.assignを `{...obj}` に書き直す

**Comment by lacolaco** [comment]
ひとまず書き終わってるのでcloseする
