### ISSUE TITLE
クラスページのリンクがいくつか切れている

### ISSUE THREAD

**Issue by waddlaw** [asciidwango/js-primer#704]
## 該当ページ

- [クラス](https://jsprimer.net/basic/class/)

## 説明

いくつかリンクが切れている

- 「関数とthis」
- 「Arrow Functionでコールバック関数を扱う」
- thisを含むメソッドを変数に代入した場合の問題
- 「ユースケース:Todoアプリ」

直し方がわからなかったので、ご報告のみです。

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/54569751-57dc2e80-4a1f-11e9-9b85-c9e3f31b6692.png)

Markdownの末尾に[参照リンク](https://hail2u.net/blog/coding/markdown-reference-style-links.html)として書いてるパスが、typoしてるっぽいですね(README.mdにするのはあってますが)

#285 も合わせてそろそろやらないとダメです。

**Comment by waddlaw** [comment]
参照リンク形式なんてあるんですね。
とりあえずリンク切れの部分のみ修正したPRを出しました。
