### ISSUE TITLE
「実行コンテキスト」について

### ISSUE THREAD

**Issue by yassh** [asciidwango/js-primer#709]
## 該当ページ

https://jsprimer.net/basic/function-this/#execution-context-this

## 質問内容

「実行コンテキスト」についてさらに詳しく調べようと思いましたが、「JavaScript 実行コンテキスト」で検索して見つかるのは"Script"と"Module"という区別の話ではなく、関数コンテキストとかグローバルコンテキストの話ばかりです。「JavaScript execution context」でも同様です。

「実行コンテキスト」について、参考になる情報源があれば教えていただきたいです。

**Comment by azu** [comment]
@yassh 実行コンテキストはECMAScriptの仕様で定義されているExecution Contextsから来てます。
この*Execution Contexts*の`ScriptOrModule`という要素が"Script"と"Module"の区別に使われていた気がします。

- https://tc39.github.io/ecma262/#sec-execution-contexts

*実行コンテキスト*という言葉自体はそこまで意味をないですが、実行される文脈が"Module"か"Script"の2種類があるよという話をするのに言葉が必要になって使った気がします。

**Comment by azu** [comment]
閉じちゃいますね。
