### ISSUE TITLE
Booleanオブジェクト

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#72]
#17 基本文法
- Booleanによるキャスト
- trueとなる値、falseとなる値
- new BooleanとBoolean(コラム)

これは完全にMDNと同じになる気がしている。
- [Boolean - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Boolean)

>  trueとなる値、falseとなる値

についてを重点的にわかりやすく解説するのを目的とする。
## 関連
#31 で 次のように書いてるので、ここでその問題を解決する

> どのような式が`true`として評価されるかは、[Booleanオブジェクト][]で紹介します。

**Comment by azu** [comment]
書いていて `Boolean` によるキャストは殆ど書いた記憶ない。( `!!` の方が見かけるぐらい)
キャストをしたい場合は明示的に真偽値が欲しい時になるはずだけど、
これはBooleanのキャスト = #53 型変換 を悪用してるような気がする。

空文字なら `文字列.length === 0` などの比較演算子を使えばいいし、キャストが必要になるケースは大抵がおかしな状態になってる気がする。
なので、それを使うケースが出てきたら危険信号 ⚠️ であるという話もできるといい気がする。

**Comment by teppeis** [comment]
思い出してみる。

- nullable string型に対して1文字以上あるかどうか
- nullable boolean型をnon-nullableにする
- ビット演算後にビットが立ってるかどうか

いずれも比較演算子で書けるので、危険信号と言えなくもない。
ただ、nullable系は2段階比較が必要だとつらいのでBoolean()か!!したい。
その場合Boolean()と!!がどっちがいいかと言うとどっちでもいい気がする。

**Comment by azu** [comment]
> ただ、nullable系は2段階比較が必要だとつらいのでBoolean()か!!したい。

https://twitter.com/mysticatea/status/749523213244207104
こういう感じのもの?

```js
if( a == null ) {
    return false;
}
if( a.length === 0 ){
    return false
}
// == ?
return Boolean(a);
```

**Comment by teppeis** [comment]
はい、そです。意味としては`a.length > 0`なんだけど、nullableだと先にnullチェックがいるっていう。
柔らかいJSだとnon-nullableという確証がないので常に`!!a`とか`Boolean(a)`の方が安全ということになりがち。

ClosureやFlowtypeだと、型をnon-nullableに寄せれば躊躇せず`a.length > 0`だけでOKなんだけど。

**Comment by azu** [comment]
このセクションはやっぱりいらない感じがするなー。
#53 で大体カバーできるので、 `Boolean` オブジェクトを知っていることで何か得する事があるかどうかぐらいかな。

**Comment by azu** [comment]
`[].filter(Boolean)` という使い方してるケース

https://github.com/babel/babel/pull/3673/files#diff-f0dba020c48e5f7861c241eb8ac5aa8eR7

**Comment by azu** [comment]
これは結局多分章としてはない気がする

**Comment by azu** [comment]
これは章としてはいらないのでclosed

https://github.com/asciidwango/js-primer/issues/328#issuecomment-349931202
