### ISSUE TITLE
nodcli: npm test の実行結果がちょっと違います

### ISSUE THREAD

**Issue by waddlaw** [asciidwango/js-primer#723]
## 該当ページ

- [ユニットテストを記述する](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/)

## 説明

書籍ではテストケースが無い場合、以下のように `0 passing` となると表記されています。

```shell
$ npm test
> mocha

 0 passing (2ms)
```

しかし、実際に試してみたところ、`Error: No test files found: "test"` が返ってきました。

```shell
λ npm test

> todo1@1.0.0 test /Users/gupi/Desktop/todo1
> mocha

Error: No test files found: "test"
```

`package.json` の内容は以下の通りです。

```json
{
  "name": "todo1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "commander": "^2.9.0",
    "marked": "^0.6.1"
  },
  "devDependencies": {
    "mocha": "^6.0.2"
  }
}
```

**Comment by azu** [comment]
Mochaの挙動が特定のメジャーバージョンから変更されたからっぽいですね(結構前だった気もします)
最新版(v6)に合わせて修正が必要そうですね。

@lacolaco `npm install mocha@6` とかバージョン固定が入ってないのもよくなさそう。

**Comment by lacolaco** [comment]
報告ありがとうございました！
