### ISSUE TITLE
データ型とリテラル　誤字の可能性

### ISSUE THREAD

**Issue by tomo-reb** [asciidwango/js-primer#731]
## 該当ページ

- https://jsprimer.net/basic/data-type/

## 説明
-------------------------------------
プリミティブ型とオブジェクト
これは、プロパティ型のデータのプロパティへアクセスする際に、対応するラッパーオブジェクトへ暗黙的に変換してからプロパティへアクセスするためです。
------------------------------------------------------------------
プロパティ型ではなくプリミティブ型ではないでしょうか？

**Comment by tomo-reb** [comment]
@azu 
(誤)プロパティ型　(正)プリミティブ型
誤字でしたら修正してプルリクを出してみてもいいでしょうか？

**Comment by azu** [comment]
@tomo-reb はい大丈夫ですよ

**Comment by tomo-reb** [comment]
@azu 
いつも学習の参考にさせて頂いているので本当に微力ですがお力になれて嬉しかったです！
これからもお世話になります、ありがとうございました。
