### ISSUE TITLE
ボキャブラリーシート

### ISSUE THREAD

**Issue by lacolaco** [asciidwango/js-primer#738]
#734

**Comment by lacolaco** [comment]
デストラクチャリングやアロー関数など、名前を知らないとググりにくいものをまとめたチートシート

**Comment by lacolaco** [comment]
まずは載せたいもののの洗い出し

**Comment by yumetodo** [comment]
これってこんな感じに表構造にする予定でしょうか？
![7432E101-7A62-45F9-8DAB-6F46F64D2277](https://user-images.githubusercontent.com/10869046/54941407-1ba15480-4f70-11e9-96ae-495c767fe5b7.jpeg)

**Comment by lacolaco** [comment]
@yumetodo 具体的なフォーマットは未定ですが、そんな感じのチートシートのようなものになると思います
