### ISSUE TITLE
while文の実行結果が違っているような気がします

### ISSUE THREAD

**Issue by masanarih0ri** [asciidwango/js-primer#763]
## 該当ページ

- https://jsprimer.net/basic/loop/

## 説明
いつもこちらのページでjavascriptの基礎を勉強させていただいております。（とてもわかり安い説明をありがとうございます！）
while文の説明のところで実行結果が間違っている箇所がありましたので共有をさせていただきます。

```
let x = 0;
while (x < 10) {
    console.log(x);
    x += 1;
}
```
という記載のある箇所で、実行ボタンを押すと

```
0
1
2
3
4
5
6
7
8
9
10
```
という結果が返ってきますが、実際には

```
0
1
2
3
4
5
6
7
8
9
```
ではないでしょうか？
適当に自分でjsファイルを作って実行してみても10まで表示されませんでした。

ご確認のほど、宜しくお願いいたします。

**Comment by azu** [comment]
ありがとうございます。

< 10なので10は出ないのが正しいですね。
あとで修正しておきます。
修正のPull Requestを出してもらっても大丈夫です。

**Comment by azu** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/19714/56731681-0c434000-6796-11e9-8c78-a0252f2dd776.png">

あー、これREPLの表示がちょっとややこしいですね。

`console.log(x)` ででているのは 0から9なのですが、
最後に`while`文後の `x` の評価結果が表示されていて、このときの `x` は 10 になります。
(よく見ると◀になっているのは、while文が終了後の`x`の出しているからですね)

つまり次のようなコードを実行しているのと同じです。

```js
let x = 0;
while (x < 10) {
    console.log(x);
    x += 1;
}
console.log(x);
```

これちょっとサンプルコードが良くない(REPLの仕組み的に誤解する)ので、変更します。

**Comment by azu** [comment]
サンプルコードを次のように変更しました。

```
let x = 0;
console.log(`ループ開始前のxの値: ${x}`);
while (x < 10) {
    console.log(x);
    x += 1;
}
console.log(`ループ終了後のxの値: ${x}`);
```

ループ終了後のxの値が`10`になっているのが確認できると思います。(`x`が`10`になったので`while`文のループが行われなかったということですね)

**Comment by azu** [comment]
他にも似たようなものをもし見つけたらぜひ報告して下さい。
見つけてもらって助かりました。

**Comment by masanarih0ri** [comment]
@azu 修正されているのを確認しました！
素敵な書籍なので、いつも時間が空いた時に読ませていただいてます^^
また少し気になった点があればご連絡をさせていただきます！
