### ISSUE TITLE
プロパティの存在確認: undefinedとの比較でコードの内容が論理的に間違っている

### ISSUE THREAD

**Issue by naoppy** [asciidwango/js-primer#768]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/object/README.md

[https://jsprimer.net/basic/object/#compare-to-undefined](url)の部分のコード
```javascript
const object = { key: "value" };
// `key`プロパティが`undefined`ではないなら、プロパティが存在する?
if (object.key !== undefined) {
    console.log("`key`プロパティの値は`undefined`");
}
```
if内はkeyプロパティに値が存在するときに実行されるのに、console.logでkeyは"undefined"と出力しているのがおかしいのではないかと思いました
```javascript
console.log(`"key"プロパティの値は"${object.key}"`);
```
こう出力するのが自然だと思います

**Comment by yumetodo** [comment]
どちらかというと

```js
const object = { key1: "value" };
// `key`プロパティが`undefined`ではないなら、プロパティが存在する?
if (object.key !== undefined) {
    console.log("`key`プロパティの値は`undefined`");
}
```

とかするべきな気もします。

**Comment by naoppy** [comment]
そうですね、私もそれが一番いいと思います

**Comment by azu** [comment]
ご報告ありがとうございます。
if文の中身が逆になってるみたいですね。
修正します

**Comment by azu** [comment]
#768 で周辺の説明と共に修正してみました。
