### ISSUE TITLE
関数とスコープ本文中のリンクが間違えている

### ISSUE THREAD

**Issue by naoppy** [asciidwango/js-primer#772]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/function-scope/README.md

[問題のあるページ](https://jsprimer.net/basic/function-scope/#global-scope)
```
ビルトインオブジェクトには、大きく分けて2種類のものがあります。 1つ目はECMAScript仕様が定義するundefinedのような変数（「undefinedはリテラルではない」を参照）
```
の`undefinedはリテラルではない`のリンクが
`##undefined-not-literal`になっていますが、
これは`#undefined-is-not-literal`に修正すべきだと思います。

**Comment by azu** [comment]
@naoppy ありがとうございます！ あとで修正します。

**Comment by naoppy** [comment]
https://github.com/asciidwango/js-primer/commit/6282d59d7ee88169a7db76095259567290b4b502#commitcomment-33443146

**Comment by azu** [comment]
@naoppy 度々ありがとうございます。

https://github.com/asciidwango/js-primer/commit/c9e52e37d0b4c1c548b76948b9d059df749e0d7e で修正しました。
