### ISSUE TITLE
Symbolのブラケット記法について

### ISSUE THREAD

**Issue by sin1rou** [asciidwango/js-primer#789]
## 該当ページ

- [https://jsprimer.net/basic/object/#add-property](https://jsprimer.net/basic/object/#add-property)

## 質問内容

2つ目のコードの中に`Symbolは例外的に文字列化されず扱える`とあるのですが、いまいち理解に自信が持てません。
「Symbolは常にブラケット記法を用いる必要がある」という意味で合っていますか？
よろしくお願いします。

**Comment by azu** [comment]
>  「Symbolは常にブラケット記法を用いる必要がある」という意味で合っていますか？

Symbolは文字列じゃないので、プロパティに入れる場合はブラケット記法でしか書けないですね。

```js
const object = [];
object[Symbol()] = 1
```

このコメントが言いたかったのは、文字列とSymbol以外はプロパティ名として使うと意図しない動作になる(toStringされた値がプロパティ名になる)ということですね。


なので、次のように `{}` をプロパティ名に指定すると、`"[object Object]"` という文字列に変換されてから、プロパティ名として扱われるのでおかしなことになってしまうという話ですね。

```js
const object = {};
const keyObject1 = {};
const keyObject2 = {};
object[keyObject1] = "1";
object[keyObject2] = "2";
console.log(object);
console.log(Object.keys(object)); // [ "[object Object]" ]
```


なので、プロパティ名には文字列 or Symbolしか原則は使ってはいけないという話を書きたかったのだと思います。

**Comment by sin1rou** [comment]
なるほど、そういうことでしたか。
ありがとうございます！ スッキリ理解できました。
