### ISSUE TITLE
ブラウザアプリユースケース用の開発サーバ

### ISSUE THREAD

**Issue by laco0416** [asciidwango/js-primer#79]
https://github.com/asciidwango/js-primer/pull/78#discussion_r69733626 より。

node-static が広く使われているようなので、全体を通して統一したほうがよさそう。
各ユースケースのpackage.jsonで依存するか、ルートでインストールしてpeerDepsにしておくかなど決めたい。

**Comment by azu** [comment]
各package.jsonでいい気がする。

```
git clone https://github.com/asciidwango/js-primer.git
cd path/to/example
npm start
```

みたいな手順で実行できたほうが分かりやすいと思うので。(ルートだとrootでnpm installしないと見れなくて謎い感じになる)
リポジトリとして切り離せるような依存にしておくのが良さそうな気もする。

**Comment by keik** [comment]
ダウンロード数では [http-server](https://github.com/indexzero/http-server) が最も使われていそうですがどうでしょう。
http://www.npmtrends.com/local-web-server-vs-static-server-vs-node-static-vs-http-server

CLI として使われることしか想定されていませんが、その分 README 的にもこっちのほうがシンプルな使い心地かなという感じがします。今回あまり関係ないですが SSL もできて微妙に便利ですね。

**Comment by azu** [comment]
https://github.com/indexzero/http-server/blob/1a8552c5e028bd5500027ee940111133927a4e94/package.json#L79 `preferGlobal`がついてる意外はよさそう。(`npm install`だけだと警告がでる系)

**Comment by azu** [comment]
### 機能要件

- [ ] http:// でアクセスできるURLを作る
- [ ] 起動した時にアクセスする URLが表示される
- [ ] メンテンスされている
- [ ] Node.js 6以降で動作する

### 非機能要件

- [ ] アクセスされてるリソースのログがでる
- [ ] インストールした時に余計な警告がでない
- `npm start` で叩くのでコマンドとしての使いやすさはやや置いておいてもいい

**Comment by azu** [comment]
[static-server](https://github.com/nbluis/static-server "static-server")のログは人間に分かりやすいので好きかも。

![1 presentation npm start zsh 2016-07-07 12-50-26](https://cloud.githubusercontent.com/assets/19714/16642018/73b1ae8c-4441-11e6-9003-1d5a3ef1d7b7.png)

どれもそんなに変わらないと思うので機能要件満たせるならどれでもいいです。

**Comment by laco0416** [comment]
ajaxappではnode-staticを使うことにしたけど特に理由はないのでのちのち必要があれば切り替える

**Comment by azu** [comment]
node-static ってことで閉じる
