### ISSUE TITLE
プライベートプロパティのコラムについて

### ISSUE THREAD

**Issue by sin1rou** [asciidwango/js-primer#799]
## 該当ページ

- [[コラム] プライベートプロパティ](https://jsprimer.net/basic/class/#private-property)

## リクエスト/提案内容

プライベートプロパティの構文が[Stage 3まで来て](https://github.com/tc39/proposal-class-fields)おり(+Chromeには実装済み)、将来的には`#`でアクセスすることになる可能性が高いという文言があっても良いかなと思います。

**Comment by azu** [comment]
Proposal自体は触れない方針にしてます。なので入れていません

https://github.com/asciidwango/js-primer/issues/422
