### ISSUE TITLE
Ajax: Fetch APIベースに書き換える

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#812]
#803 

https://jsprimer.net/use-case/ajaxapp/ をFetch APIをベースに書き換える。
もともとは、コールバックをPromiseにラップするという意味合いが強かった。
コールバック -> Promise という意図があった。

それ自体は非同期の章である程度カバーされている。
また、非同期の章でもコールバックベースのAPIを推奨する(非推奨ではない)形になっていないため、あえてユースケースでもコールバックベースの非同期をメインにする必要はないんじゃないかという話があった。
https://jsprimer.net/basic/async/

そのため、現在コラムになっているFetch APIをメインにして、コラムの方をXHRにするという形に書き換える。

## Tasks

- [x] Fetch APIがベースにかきかえる
- [x] XHRのコラムを入れる(Fetchの置き換え)
- [x] 最後に `async main()` で置き換える

## 考慮事項

- Node CLIのreadFileをPromiseベースに書き換える?

**Comment by azu** [comment]
https://jsprimer.net/use-case/todoapp/update-delete/#todo-item-update
ここも変更必要。addEventListenerが参照してた

**Comment by lacolaco** [comment]
完了した
