### ISSUE TITLE
スクリーンショットについて

### ISSUE THREAD

**Issue by lacolaco** [asciidwango/js-primer#82]
スクリーンショットの撮影方法と、サイズ・形式について

実行環境との一貫性を考えてFirefoxで撮影したい
サイズ固定はレスポンシブモードでよさそう？スクリーンショット機能もある。
形式はpngで問題ない？オンラインで見られるならjpgにしておくほうが親切か？

懸念点：
- ブラウザ以外のスクリーンショットはどうするか
  - ターミナル
  - 開発者コンソールを含めたブラウザ全体

**Comment by laco0416** [comment]
サイズは 横長のほうがよさそう 16:9？

**Comment by azu** [comment]
スクリーンショットにおいては以下の2つがあれば大抵は問題ない気がします

- 再現性(自動化 or 再現手順)
- 加工に耐えられる解像度

ChromeだとレスポンシブモードでDPRが設定できる。
Firefoxはなぜかないけど、開発ツールバーの`screenshot`コマンドにはある。

**Comment by azu** [comment]
縦横比はなんか状況で変わりそうな気がするけど、
HTMLコンテンツで16:9なら1280×720 とかぐらい?(1600x900だと余白多そうな気がするけどどうなんだろ)

**Comment by azu** [comment]
画像形式は jpg より png の方が良さそう(ファイルサイズも大した差ないと思うし、加工するならpngにしておいたほうがいい)

**Comment by laco0416** [comment]
> 開発者コンソールを含めたブラウザ全体

こっちをどうするか悩んでる Firefoxのウィンドウ自体のサイズを設定する方法あるのかしら(Mac用ツール探す話になりそう)

**Comment by laco0416** [comment]
AppleScriptで

```
set bounds of window 1 of application "Firefox" to {0, 0, 1280, 720}
```

と書いて実行すると調整はできた

**Comment by laco0416** [comment]
```
set bounds of window 1 of application "Firefox" to {0, 0, 1280, 720}
do shell script "screencapture -iW ~/Desktop/test.png"
```

で、Firefoxのウィンドウを調整した上でウィンドウを選択してスクリーンショットを撮影できた。とりあえずAppleScriptファイルを必要に応じてリポジトリに置いておけば特殊なスクリーンショットは再現可能になりそう

**Comment by azu** [comment]
手順書くならこんな感じ?(1は新規プロファイルでもいいけど)

1. Firefoxをセーフモードで起動(ヘルプ->アドオンを無効にして再起動)
2. 新規プライベートウィンドウ(Cmd+Shift+P)
3. ウィンドウサイズ指定
4. URLをひらく(`<title>`には意味があるものを指定)
5. キャプチャ

**Comment by laco0416** [comment]
```
tell application "Firefox"
	quit
end tell
delay 1
do shell script "open -a /Applications/Firefox.app --args -private"
```

これとさっきのスクリプトの2つあればFirefox自体のスクリーンショットには困らなさそう

**Comment by laco0416** [comment]
ajaxappの方で実際に使ってみる

**Comment by azu** [comment]
CONTRIBUTING.md あたりに方針を書いて、Issueを閉じるのがよさそう。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/tree/master/tools/applescript/src
でいくつかapplescriptをNode.jsから実行するスクリプトを書いた。
開発者ツールを開いて指定URLをキャプチャするみたいな感じのやつ
