### ISSUE TITLE
ソースコード内のコメント誤字

### ISSUE THREAD

**Issue by Yuki-Sakaguchi** [asciidwango/js-primer#820]
## 該当ページ

- [https://jsprimer.net/use-case/todoapp/final/]

## 説明
「TodoItemViewを作成する」項の「src/view/TodoItemView.js」にあるソース内に以下のコメントがあります。

```
* @param {function({id:string)}} onDeleteTodo 削除ボタンのクリックイベントリスナー
```

引数の型を記述している`{function({id:string)}}`の**閉じ丸括弧の位置がずれている**と思います。
以下が正しいと思いますがどうでしょうか？

```
* @param {function({id:string})} onDeleteTodo 削除ボタンのクリックイベントリスナー
```

## 該当箇所
以下の2箇所で見つけました

- src/view/TodoItemView.js内のcreateElement関数のコメント
- src/view/TodoListView.js内のcreateElement関数のコメント

**Comment by azu** [comment]
報告ありがとうございます！
確かにおかしいので間違いっぽいですね
