### ISSUE TITLE
非同期処理:コールバック/Promise/Async Function

### ISSUE THREAD

**Issue by iwinstar1980** [asciidwango/js-primer#838]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/async/README.md

Promiseチェーンの節には、以下のように書いてあります。

「asyncTask関数が成功（resolve）した場合はthenメソッドで登録した成功時の処理だけが呼び出され、catchメソッドで登録した失敗時の処理は呼び出されません。 」

その節の下の図とは合いません。

正しいのは以下ではないかと思います。

「asyncTask関数が成功（resolve）した場合はthenメソッドで登録した成功時の処理が呼び出され、該当処理が成功（resolve）した場合、catchメソッドで登録した失敗時の処理は呼び出されなく、失敗（reject）した場合、 catchメソッドで登録した失敗時の処理は呼び出されます。」

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/59889082-978f2980-9405-11e9-8983-b9e0ffcc5c4c.png)

この図はそれぞれの関数でPromiseがFullfilled or Rejectedになった状態の流れを表してますね。
`onFulfilled` で Rejectedとなった場合の流れが文章にないからおかしくみえるのかもしれないですね。

- `asyncTask`関数が成功（resolve） -> `onFulfilled`
- `asyncTask`関数が失敗（reject） -> `onRejected`
- `onFulfilled`が失敗(reject) -> `onRejected`

というパターンを書いています。
