### ISSUE TITLE
read-eval-print: コンソールの開き方について

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#85]
コンソールへの表示方法を扱っているが、開き方については書かれてない
ここで開き方について簡単に触れる。
(変数宣言より前に持って行ったほうが楽かも)

## やること

- [ ] index.htmlと`<script>`を使っての実行(ブラウザ(推奨はFirefox)を使ったコンソールの開き方と実行)
        - index.htmlにscriptタグを書いて、コンソール実行。リロード方式
        - script のtypeなしで書く 
- [ ] 実際に実行したときの表示の読み方
- [ ] VSCodeコラム
- [ ] 構文エラーがでた例 と エラーのふりがな
- [ ] 実行時エラーがでた例と エラーのふりがな
- [ ] その他のリンク
       - CodeSandboxとか設定方法へのリンクをまとめたもの

## 関連
-  #83: feat(ajaxapp): エントリポイントについての節を追加

**Comment by laco0416** [comment]
こちらでまとめられたら、ユースケース側からはread-eval-print節への参照で済ませられそう

**Comment by azu** [comment]
![250 2016-07-31 23-11-12](https://cloud.githubusercontent.com/assets/19714/17277033/3fc1cb5c-5774-11e6-9845-b92c9f7b6114.png)

[Mastering JavaScript](https://www.packtpub.com/web-development/mastering-javascript "Mastering JavaScript")はchapter 1のREPLの話のところで、エラー表示の話もしてた。
話的に自然なので、 https://github.com/asciidwango/js-primer/issues/102#issuecomment-234776494 の話をここに書くといいのかも。

後ウェブ版はコンソールがあるので、#56 これを使った解説と分岐が必要になるかなー
(GItBookで一応分けられる)

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/34467170-a2efbc10-ef2c-11e7-961f-3df250f98f12.png)

http://refactoringjs.com/
リファクタリングJavaScriptで見たこのテクニックはここに入れたいかも。
REPLでこういうの打ってみましょうって感じにして、もしエラーがでたら古いバージョンのものを使ってるかもしれないよっていう注記を入れる感じの
(ここか、最初にそういう機能が出てくるところ)

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/41806775-de044f1e-76fe-11e8-9f69-ea480e5db69e.png)

[かんたん Ruby](http://gihyo.jp/book/2018/978-4-7741-9861-3)を読んで、デバッグの概念についても触れられていて、エラーを次の２つに分けていた

- 構文エラーがでた例 と エラーの読み方
- 実行時エラーがでた例と エラーの読み方

これ最初にあると分かりやすいので、
[スラスラ読める JavaScriptふりがなプログラミング](https://www.amazon.co.jp/dp/B07DR76HSG/)も参考にしてエラーを見る部分も入れたい。

**Comment by azu** [comment]
スクラッチパッドを使う予定という話を https://github.com/asciidwango/js-primer/issues/2 をしていたけど、コンソールへの出力結果が見られないので、微妙に不便。

- コンソールを使う
- スクラッチパッドを使う
- Node.jsを使う
- [CodeSandbox](https://codesandbox.io/) のようなものを使う
- js-primerのサイト上にREPLを用意する

どの辺にするかを改めて考えたい感じがする。

コンソールとスクラッチパッドは見ているサイトの影響を受けるので、どちらにしても指定した場所への案内が必要になるのではという感じがしている。
Chromeの[Eager Evaluation](https://developers.google.com/web/updates/2018/05/devtools#eagerevaluation)もあるしゅ魅力的な選択肢でもあるので考慮したい

**Comment by azu** [comment]
> js-primerのサイト上にREPLを用意する

eloquentjavascriptはこのスタイルだった
https://eloquentjavascript.net/2nd_edition/code/
http://eloquentjavascript.net/code/

**Comment by azu** [comment]
#492  で以下みたいな感じにすることにした。

- [ ]  index.html + コンソール 
   - index.htmlにscriptタグを書いて、コンソール実行。リロード方式
- [ ]  エディタ
  - [ ] [Visual Studio Code](https://code.visualstudio.com/ "Visual Studio Code - Code Editing. Redefined")
- [ ] その他のリンク?
  - CodeSandboxとか設定方法へのリンクをまとめたもの?

**Comment by azu** [comment]
![image](https://user-images.githubusercontent.com/19714/46129127-a844b180-c270-11e8-9de7-1aa37ece0dab.png)

[Vue.js入門 基礎から実践アプリケーション開発まで：書籍案内｜技術評論社](https://gihyo.jp/book/2018/978-4-297-10091-9) ではHTMLとjsfiddleを使っていた。
