### ISSUE TITLE
loop: break文の代替記法のようなものでなにかいいものはあるか

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#853]
## 該当ページ

https://jsprimer.net/basic/loop/#break-statement

## 背景

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">JavaScriptのforEachは、breakができないのが不便ですね。<br>みなさん、どういう代替手段を使っているんでしょう？<br>・for<br>・some<br>・再帰<br>あたりでしょうか？</p>&mdash; はけた＠Excel最高の学び方発売中 (@excelspeedup) <a href="https://twitter.com/excelspeedup/status/1143387873263046656?ref_src=twsrc%5Etfw">2019年6月25日</a></blockquote>

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">あーまって、continueじゃなくてbreakか、そうなると普通にfor...ofでbreak書く</p>&mdash; yumetodo-鳥の氷河から逃げる (@yumetodo) <a href="https://twitter.com/yumetodo/status/1143395331838640130?ref_src=twsrc%5Etfw">2019年6月25日</a></blockquote>

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">ありがとうございます。<br>continueなら何もせずreturnでも良い気がしますね。<br>そして、breakのときは、やはりforEachを使うべきではないのでしょうね。</p>&mdash; はけた＠Excel最高の学び方発売中 (@excelspeedup) <a href="https://twitter.com/excelspeedup/status/1143461657223430145?ref_src=twsrc%5Etfw">2019年6月25日</a></blockquote>

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">forの方が良さげな雰囲気はしますね<br><br>.NET の LINQ だと All(JS の every)でやる例も見ますが、<br>JS だと返り値無しの undefined が false になるので、every より some の方がすっきりしそうですね。<br><br>ちょっと違いますが C# の LINQ での記事です(コメント欄に各種意見)。<a href="https://t.co/AzEdckMWa0">https://t.co/AzEdckMWa0</a></p>&mdash; いみひと (@nukie_53) <a href="https://twitter.com/nukie_53/status/1143472499012726784?ref_src=twsrc%5Etfw">2019年6月25日</a></blockquote>

## リクエスト/提案内容

`continue`については`Array#filter`を使う例が出ているが、`break`に対しては何か合っただろうか、`every`?`some`?

いずれにせよ、言及が合っても良いのではないか？

**Comment by azu** [comment]
breakは原理的にArrayのメソッドでは代替しにくいと思います。
Arrayのメソッドには条件式を書かずに済むため、forループより簡潔な場合が多いです。
逆を言えば条件式で止める = break みたいなものがないとも言えます。

Arary#someでbreakのようなことはできますが、someはそういう用途ではないですね。
(たまにsomeでbreakしてるコードは見ますが、ハック的なものだと思います)

filterで絞ってから反復処理を書くと、breakでやっていたことと似たような結果が実現できるケースが多い気もします。
```js
[1,2,3].filter().forEach()
```

基本的にArrayメソッドはループの反復数はforループより多くなりがちだと思います。
その辺のパフォーマンスの最適化を目指すならforループの方が原理的に早いです。
ループ回数をできるだけ減らすという最適化をArray系でやる場合はTransducerなどの関数合成的な話になってくるので、ここで扱うのはちょっとむずかしいです。

* [Understanding Transducers in JavaScript - Roman Liutikov - Medium](https://medium.com/@roman01la/understanding-transducers-in-javascript-3500d3bd9624)
* [tomi/fromfrom: A JS library written in TS to transform sequences of data from format to another](https://github.com/tomi/fromfrom)

**Comment by azu** [comment]
https://jsprimer.net/basic/loop/#conclusion
まとめでも書いてますが、(for...in文以外は)どっちの方がいいという答えはないと思います。
