### ISSUE TITLE
JavaScriptの概要

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#87]
#17 基本文法
プログラミング言語のとしてJavaScriptについてざっくり説明する節

## アウトライン

- 未使用
	- 似てる言語
		- C言語
		- Java
		- Scheme
		- Self
		- --- 言語仕様 ----
		- Python
	- JavaScriptは文や式から構成される
	- セミコロン
		- 文(ステートメント)は `;` で句切られる
		- 複雑なルールにより `;` を省略しても自動的に挿入されるASIがある
		- 基本的にASIに頼るのは言語を学ぶにおいても良くないことなので、基本的に付ける
		- `;`付けるほうがメジャー
		- [2015年のJavaScript開発者アンケートまとめ - Qiita](http://qiita.com/azu/items/eb6e8abf951a9af19dd9 "2015年のJavaScript開発者アンケートまとめ - Qiita")
	- case-sensitive
		- JavaScriptは大文字、小文字を区別する
		- 変数名で大文字小文字が異なれば別変数
	- Unicode
		- JavaScriptはUnicodeを利用している
		- メソッドによってはサロゲートペアもきちんと扱える(主にES2015〜)
	- ホワイトスペース
		- 空白文字 = スペース、2028/2029、タブ
                - 改行などはline-terminators http://www.ecma-international.org/ecma-262/7.0/#sec-line-terminators
		- インデントについての言語的な仕様はないため2タブ、4タブなど様々
	- キーワード
		- 予約語 ∋ キーワード
		- 特別な意味を持つ単語
		- 同じ名前で変数名として使えないなどの制限がある
		- 状況によってキーワードになったりならかなったり
		- Contextual キーワードという概念
		- 変数の宣言や値の表現としてキーワードやリテラルが定義されている
	- strict mode
		- `"use strict"` とかくことでstrict modeとして扱う仕様がある
		- 一部古い仕様がパース時にエラーとなるという機能
		- この書籍は基本的にstrict modeで実行できるようにしている
	- ScriptとModule
		- JavaScriptはスクリプトとモジュールがある
		- スクリプトはグローバル空間で全てのJavaScriptファイルが実行される
		- スコープが共有される
		- モジュールはモジュールごとにスコープが分かれている
		- 基本的にモジュール空間でソースコードを扱う想定にした方がコードが簡潔
		- 即時実行関数など回避するための手法が存在していたが今後は不要
	- 参考
		- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Basics
		- http://speakingjs.com/es5/ch01.html#_semicolons

**Comment by azu** [comment]
変数名は規約を満たしていれば、その変数名が大文字であるかどうかで挙動が異なることはない

**Comment by lv7777** [comment]
キーワードって予約語のことですか？

だとすると`予約語ともいう`みたいなことを書いておくといいかもしれません。

**Comment by azu** [comment]
@lv7777 そうですね。
予約語 ∋ キーワード みたいな関係です。
http://www.ecma-international.org/ecma-262/7.0/#sec-reserved-words

**Comment by azu** [comment]
インデント数についても2 or 4 spaceが多いって書きたい。。。
JavaScriptだと 2 or 4 spaceが主流というのはある程度正しいデータがあるけど、
ココ見ればそれが証明されているみたいなリンクがない…(常に最新があるような場所)

- [2015年のJavaScript開発者アンケートまとめ - Qiita](http://qiita.com/azu/items/eb6e8abf951a9af19dd9)
- [Detecting Code Indentation — Firefox Developer Tools — Medium](https://medium.com/firefox-developer-tools/detecting-code-indentation-eff3ed0fb56b#.aifwlb91j)

**Comment by azu** [comment]
closed by  #120
