### ISSUE TITLE
GitBookをやめる

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#877]
- 理由: [GitBook v1](https://github.com/GitbookIO/gitbook)はメンテされていない
  - GitBook v2はホスティングのみであるため
- 必要要件:
  - Markdownを拡張できる
    - https://github.com/azu/gitbook-plugin-include-codeblock
    - https://github.com/azu/codemirror-console/tree/master/packages/gitbook-plugin-js-console/
  - パーマネントリンクを維持できる
    - named linkも含めてマイグレーションできる

[VuePress](https://vuepress.vuejs.org/)や[Docusaurus](https://docusaurus.io/)(v2)あたりは候補。
ランディングページとコンテンツはできれば分けたくない。最初のページから目次(サイドバー)は一緒に表示したい。[docsify](https://docsify.js.org/#/)のような形もあり。

**Comment by yumetodo** [comment]
一応mdbookという手もありそうです。
https://rust-lang-nursery.github.io/mdBook/for_developers/preprocessors.html
https://crates.io/crates/pulldown-cmark

**Comment by azu** [comment]
mdbookも考えましたが、いまいちステータスがわからないですよね
https://github.com/rust-lang-nursery/mdBook/issues/858

GitBookよりビルドが遅いものの方が少ないと思うので、あんまりビルド速度は気にしなくていいと思います。
(自分はnetlifyのビルドしか見てない…)
拡張性とメンテナンス性ですかね。

**Comment by yumetodo** [comment]
確かにステータスわかりにくいですが、メンバー入れ替えたりして活動は続いているのでまぁ、という感じです。単にPRとIssueが投げつけられすぎているだけというような。
mdbook公式ドキュメントの執筆はだいぶ停滞している感がありますが(翻訳は特に手が回っていない)。

**Comment by yumetodo** [comment]
mdbookの場合、自分がざっと調べた感じだと
https://github.com/yumetodo/novel_two_people_who_transmigrated_make_magic_and_IT_fused/commit/f4138cb9df88a64cbecd6cff3f08d4d36ac3a53a#diff-f0855f4462826cc9e9c7a7c44540ad3b

```
---
author: yumetodo
---
```

みたいのは除去しないといけなさそうでした。

**Comment by azu** [comment]
https://blog.gmork.in/entry/mdmt

**Comment by azu** [comment]
別のアプローチとしてforkするというパターンがあるので、一度軽く実現できるのかは調べてみるといいのかも。メンテナンスコストがあるので避けたい気もするけど、移行コスト(他のプロジェクト)も考えるとなくはない方法という感じがする。

https://twitter.com/azu_re/status/1253588250997911552

**Comment by yumetodo** [comment]
前に上げたmdbookはメンテが続いていますし、pluginシステムもあるので時間が取れそうならforkしてやってみたい思いはあります。

詳しく調べていませんが、
https://github.com/vuejs/vuepress
というのもgitbookに近い有名なジェネレーターだと思います。

**Comment by azu** [comment]
[Nuxt Content](https://content.nuxtjs.org/)はVuePressとかなり近いけど、自由度はこっちのほうが高い気がする

**Comment by azu** [comment]
GitBookをforkした [GitHon](https://github.com/githon/githon) を作って、GitHonに移行したのでこのissueは解決済みにします。互換性は維持して、ビルドパフォーマンス周りは改善しました。

package-lock.jsonとかとの相性が悪い問題とかも解決されているはず。
