### ISSUE TITLE
非同期処理: Async Function 冗長な箇所？

### ISSUE THREAD

**Issue by HirotoTakezoe** [asciidwango/js-primer#884]
## 該当ページ
https://jsprimer.net/basic/async/
- [ ] 質問があるページのURLを入れてください

## 質問内容
一番最後の`class AsyncStorage`で実装されている`save()`と`load()`に`async`が使われているのはなにか意図があるんでしょうか。
別になくても問題ないように思ったのですが、理由があれば教えていただけると助かります &#x1f647;

**Comment by yumetodo** [comment]
（助長じゃなくて冗長・・・？)

**Comment by HirotoTakezoe** [comment]
タイピングミス、、、&#x1f62b;

**Comment by azu** [comment]
asyncと付くだけで特別な意味はない(同じ動作になる)ので省いても大丈夫そうですね
