### ISSUE TITLE
HTTP通信: ステータスコードは20Xを扱うように変更する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#896]
URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/ajaxapp/http/README.md

> ステータス4XXと5XXをサーバーエラーとする
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/use-case/ajaxapp/http/README.md#L130 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/use-case/ajaxapp/http/README.md#L130>

4xxはクライアントエラーなので、このコードは変更したほうがよさそう。
https://fetch.spec.whatwg.org/#ok-status と同じように 20x を扱うコードにしたほうが良い気がする。

**Comment by azu** [comment]
Fetchの方もサーバエラーじゃないことがあるので、なんかメッセージを変更したい

**Comment by yumetodo** [comment]
```js
status => status >= 200 && status < 300
```

みたいなのではだめですかね

**Comment by azu** [comment]
それが https://fetch.spec.whatwg.org/#ok-status と同じ20xを扱うという話です。

**Comment by azu** [comment]
#907
