### ISSUE TITLE
Ajax通信を行うブラウザアプリケーション

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#9]
ユースケースのひとつ 
Ajax通信を行ってデータを表示する簡単なアプリケーション

GitHubのAPIを使ってユーザーIDからプロフィールを出す

**Comment by azu** [comment]
@laco0416 これIssueのタイトルと説明を適当に埋めといてもらえると

**Comment by laco0416** [comment]
ひとまずの完了ということで、クローズする。
