### ISSUE TITLE
Promiseを活用する: Bug report

### ISSUE THREAD

**Issue by ken-mitamura** [asciidwango/js-primer#908]
## 該当ページ

URL : https://github.com/asciidwango/js-primer/blob/master/source/use-case/ajaxapp/promise/README.md

## 説明

関数名が変わってしまっているので、関数名を `fetchUserInfo` に変更する記述を入れるか、`getUserInfo` のままにしておくかどちらかが良いかと思いました。

```diff
-        const userInfo = await fetchUserInfo("js-primer-example");
+        const userInfo = await getUserInfo("js-primer-example");
```

**Comment by azu** [comment]
ありがとうございます。
`fetchUserInfo` に統一する形で修正してみました。
#909 #907 

#844 あたりのリファクタリングで混ざってしまったようです。
