### ISSUE TITLE
非同期処理 : 同期処理のコードの実行結果について

### ISSUE THREAD

**Issue by harashoo** [asciidwango/js-primer#913]
## 該当ページ

- 同期処理のコードです。
https://jsprimer.net/basic/async/#sync-processing

## 説明
- 以下の同期処理のコードの実行結果が、ブラウザ上では期待していない結果になります。
- "処理を開始"を表示後、1000ミリ秒後に、"この行が呼ばれるまで処理が1秒間ブロックされる"と表示されるはずが、ブラウザ上では、1000ミリ秒後に"処理を開始"と"この行が呼ばれるまで処理が1秒間ブロックされる"が同時に表示される。

### 対象のコード
```
console.log("処理を開始");
blockTime(1000); // 他の処理を1000ミリ秒（1秒間）ブロックする
console.log("この行が呼ばれるまで処理が1秒間ブロックされる");
```

念のため、実行環境は下記の通りです。
- OS : macOS High Sierra バージョン10.13.6
- ブラウザ : Google Chrome バージョン: 73.0.3683.86

**Comment by azu** [comment]
"実行"を押したときに処理が走って、このときにすでに1秒分UIがブロックされているので、結果が表示されるタイミングでは同時にでていると思います。

同時に表示されているように見えるのは、UIがブロックされているからですね。
UIを更新しようとする処理("処理を開始"というログを表示する処理)が重たい処理でブロックされてます。
なので、全ての処理が終わったときにまとめてUIが更新されるという動きをブラウザ側がやっています。

```
// 指定した`timeout`ミリ秒経過するまで同期的にブロックする関数
function blockTime(timeout) { 
    const startTime = Date.now();
    // `timeout`ミリ秒経過するまで無限ループをする
    while (true) {
        const diffTime = Date.now() - startTime;
        if (diffTime >= timeout) {
            return; // 指定時間経過したら関数の実行を終了
        }
    }
}
const start = Date.now();
console.log("処理を開始");
blockTime(1000); // 他の処理を1000ミリ秒（1秒間）ブロックする
console.log("この行が呼ばれるまで処理が1秒間ブロックされる", Date.now() - start);
```

としてみると実際に1秒間かかってるのがわかりやすいと思います。

**Comment by azu** [comment]
開発者ツールのコンソールログだと即時にでてくるので、こちらだとわかりやすいですね。

![Aug-01-2019 22-33-23](https://user-images.githubusercontent.com/19714/62297590-7f9ed100-b4ac-11e9-81ab-a6f59a40f9bd.gif)

ブラウザがUI(埋め込まれてるエディタのUI)の更新を間引くのは、毎回ちゃんと更新しようとすると重たいので、勝手に間引いているという感じですね。
これは表示が間引かれるかどうかはブラウザの実装依存なので、JavaScriptとしては意図したように実行されている感じがします。

もっと分かりやすい感じの説明の仕方があると良さそうですが、表示の問題なので説明が難しいですね…

**Comment by harashoo** [comment]
理解不足でした、すみません。
ご丁寧に解説いただきまして、ありがとうございます！
コンソールログで見ると、とても分かりやすいですね。
JavaScriptは意図した通りに動いていて、ブラウザ側でUIの更新をブロックしていることがよく分かりました。
