### ISSUE TITLE
nodecli: markedのsanitizeオプションはdeprecatedとなった

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#918]
https://github.com/markedjs/marked/releases/tag/v0.7.0

nodecliで利用してる `marked` の`sanitize`オプションは非推奨となったので、なんか別のライブラリとかにしたほうがいいような気がしてる。

**Comment by azu** [comment]
https://github.com/azu/safe-marked
https://www.npmtrends.com/marked-vs-markdown-it-vs-showdown-vs-remark-html

markdown-itが妥当な感じはするけど、オプション逆なんだよね(普通はそうな気がするけど、意外とそういうのが少ない)
https://github.com/markdown-it/markdown-it

**Comment by lacolaco** [comment]
https://github.com/markdown-it/markdown-it/blob/master/docs/security.md

markdown-itもHTMLを有効にするなら外部のサニタイザーを使ってって書いてる

**Comment by lacolaco** [comment]
サニタイザー内包してるほうが少なそう

**Comment by azu** [comment]
markdown-it はまあデフォルトがHTML無効だからまだいいけど、
https://github.com/azu/safe-marked
デフォルトが安全じゃないのが多いからわざわざこういうの書いた記憶もある。
(DOMPurify どう考えても使い方が難しい)

**Comment by lacolaco** [comment]
markdown-itにしてsanitizeの項目消しちゃう感じの想定です？

**Comment by azu** [comment]
> markdown-itにしてsanitizeの項目消しちゃう感じの想定です？

markdown-itにして、--enable-html みたいなオプションを追加するとか?

https://github.com/commonmark/commonmark.js
はmarkedと似た感じだけど、こっちはgfmオプションはないんだ(こっちも0.x系…)

**Comment by azu** [comment]
オプションがバージョンで変わるのはしょうがないんだけど、機能そのものがライブラリから消えちゃうパターンなのがちょっとネックなんだよなー

取れそうな選択肢

- marked の バージョンを固定しちゃう
- marked + サニタイズライブラリで実装する
- 他のなにかにする

**Comment by yumetodo** [comment]
ところでJS製のライブラリにこだわる必要ってあるんでしょうか・・・？

**Comment by azu** [comment]
@yumetodo 趣旨がよくわからないです。
環境依存とかを考えると、ネイティブライブラリを検討するのは難しいと思います。

**Comment by azu** [comment]
このIssueは #928 にマージされる。
基本的には扱わないように消すという方向。
