### ISSUE TITLE
Error/try...catch文

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#93]
#17 基本文法

このセクションでは、次のをメインにしたい。
- なぜエラーがおきるのか
- エラーのキャッチ方法
- エラーの扱い方

try...catch文は #68 の continute/breakと同じ制御文という分類?だけど、
基本的にエラーの話というまとまりでまとめていく。

なので、エラー  -> try...catch文 -> Promiseという話の流れが良さそう。

エラーについてのセクション
エラーは一番挫折に直結する部分なので、ものすごく丁寧な論調が必要になるかもしれない。

もしくは、Operational errors と Programmer errorsをセクションとして分離して行くのがいいのかもしれない。
サンプルコードがミスって動かないのはProgrammer errorsな気がするので、それを最初のコンソール値に持っていくとか。
- [Joyent | Error Handling](https://www.joyent.com/node-js/production/design/errors)
- [JavaScript error reference - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors)
- [JavaScriptの動かないコード　　(JavaScriptエラー集) - 主に言語とシステム開発に関して](http://language-and-engineering.hatenablog.jp/entry/20080912/1221297779)

ミスとエラーについての区別を付けるという趣旨?

**Comment by azu** [comment]
[Error Handling -- Eloquent JavaScript](http://eloquentjavascript.net/1st_edition/chapter5.html "Error Handling -- Eloquent JavaScript")

**Comment by azu** [comment]
エラーモデル [Joe Duffy - The Error Model](http://joeduffyblog.com/2016/02/07/the-error-model/ "Joe Duffy - The Error Model")

**Comment by azu** [comment]
try-catchとJSON.parseの組み合わせを関数として外に出すという話をしたい気もする。
try-catchを使わなければならない状況の典型なはずなので

**Comment by azu** [comment]
throwはErrorとセット

**Comment by azu** [comment]
[fun-task/exceptions.md at master · rpominov/fun-task](https://github.com/rpominov/fun-task/blob/master/docs/exceptions.md "fun-task/exceptions.md at master · rpominov/fun-task")

**Comment by azu** [comment]
プログラミングエラーについてもここにメモっていく

from https://github.com/asciidwango/js-primer/issues/102#issuecomment-234776494 

逆を言えば、エラーはでないけどエラーというパターンもあるので、
そういうパターンを見つけるにはどうすればいいかという話。
そういう発見という意味では #142 非推奨の章 にちかいのかもしれない。

例えば、次の例とかは構文エラーではないので、コンソールにエラーがでてることに気づかないと分からない。
またネイティブならエラーぐらいは出してくれそうだけど、ライブラリとかはこういうのは何も言わないことがある。
そういうのを発見する方法というのは結構重要そうな気もする。

```js
var obj1 = document.getElementByID("XXXXX");
obj1.addEventListener(function(){"propertychange",alert("イベント発生");},false);
```

- [javascript - INPUTの値の変更を感知するには？ - スタック・オーバーフロー](http://ja.stackoverflow.com/questions/30311/input%e3%81%ae%e5%80%a4%e3%81%ae%e5%a4%89%e6%9b%b4%e3%82%92%e6%84%9f%e7%9f%a5%e3%81%99%e3%82%8b%e3%81%ab%e3%81%af "javascript - INPUTの値の変更を感知するには？ - スタック・オーバーフロー")

**Comment by lacolaco** [comment]
https://github.com/asciidwango/js-primer/issues/299#issuecomment-332806223

**Comment by azu** [comment]
エラー文の解説: [JavaScript エラーリファレンス - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Errors "JavaScript エラーリファレンス - JavaScript | MDN")

**Comment by lacolaco** [comment]
- try-catch-finallyとthrowの構文の話
- ビルトインErrorの種類
- Errorオブジェクトの話
    - スタックトレースの読み方

みたいな展開で、なるべく薄めに薄めに書かないと沼に入りそう

**Comment by lacolaco** [comment]
エラーが出て困ったときに読むと足がかりになる章がいい

**Comment by lacolaco** [comment]
- try-catch-finallyとthrowの構文の話
- ビルトインErrorの話
    - スタックトレースの読み方
    - Firefoxのスクリーンショットで説明する
- Errorコンストラクタの話

**Comment by lacolaco** [comment]
「ここがエラーの種類(TypeErrorとか)で、ここがメッセージで、ここがスタックトレース、このファイルの何行目でエラーが投げられてる」

**Comment by lacolaco** [comment]
https://github.com/asciidwango/js-primer/issues/142 増えていきそうなので、こういうふうに並べていくテンプレートを書き始めておく

**Comment by azu** [comment]
[Proper Error Handling in JavaScript ― Scotch](https://scotch.io/tutorials/proper-error-handling-in-javascript "Proper Error Handling in JavaScript ― Scotch")
なんとなく話の内容は似たような雰囲気かも
