### ISSUE TITLE
const,letでもローカル変数undefinedが定義できる

### ISSUE THREAD

**Issue by yuta0801** [asciidwango/js-primer#944]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/data-type/README.md

> letやconstでは、同名の変数は再定義できないためundefinedの再定義はできません。

> const、letを利用した場合はそもそも定義できません。

と書かれていましたが、varと同様にスコープを作れば再定義できてしまいました。

```js
{
    const undefined = "独自の未定義値"; // undefinedと名前の変数をエラーなく定義できる
    console.log(undefined); // => "独自の未定義値"
}
```

**Comment by azu** [comment]
#611 の修正のときにコードだけ修正して、文章の方の修正が漏れてた感じみたいです。
