### ISSUE TITLE
App.jsの変数名について（todoapp）

### ISSUE THREAD

**Issue by harashoo** [asciidwango/js-primer#946]
## 該当ページ

- [https://jsprimer.net/use-case/todoapp/final/#app-event-listener](https://jsprimer.net/use-case/todoapp/final/#app-event-listener)

## 質問内容
**Appのイベントリスナーを整理する**の`src/App.js`で定義されている以下2つの変数名が、**Appのイベントリスナーを整理する**以前に書かれていた変数名と異なったので、少し気になりました。こちらの変更は意図したものでしょうか。

- `todoCountElement`は、それまでは`todoItemCountElement`
- `todoListContainerElement`は、それまでは`containerElement`

**Comment by azu** [comment]
多分誤記ですね

**Comment by harashoo** [comment]
修正してPRします！
