### ISSUE TITLE
2019年9月9日 ミーティングアジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#956]
2019年9月9日のミーティングアジェンダ

**Comment by azu** [comment]
https://twitter.com/MozWebCompat/status/1170889728171753473
Firefoxのコンソールチェック

**Comment by azu** [comment]
チートシート(ボキャブラリーシート?)  #738 をなんとなく作ってみた。

ArrayのSpread Syntaxの説明ちゃんとしてないということに気づいた。

https://github.com/asciidwango/js-primer/pull/955
https://deploy-preview-955--js-primer.netlify.com/cheetsheet/

**Comment by azu** [comment]
- [x] 一度、先頭からTODOまでリファクタリングした
- [ ] 細かいtypoとかは見てない
- [x] 参考リンク集にtranspilerとbundler足す
  - asciidwango/js-primer/issues/644
- ソースコードのタイトル 〜抜粋とかつける　asciidwango/js-primer/issues/927
  - [x] todoはとりあえずやった

**Comment by azu** [comment]
サブタイトル

asciidwango/js-primer/issues/865

**Comment by azu** [comment]
[テスト駆動開発](https://tatsu-zine.com/books/test-driven-development)の"付録C: 訳者解説:テスト駆動開発の現在" っぽくエッセイを書くとかありかも。

**Comment by azu** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19714/64523201-cba82580-d336-11e9-93a0-a26e0dd5e3fc.png">

Firefoxのコンソールパネルにエディタっぽいのが入ったのはまだNightlyっぽい。
DevEditionにはなかった

**Comment by azu** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19714/64524968-b3d2a080-d33a-11e9-8ad0-3a5cfddaa33d.png">

**Comment by lacolaco** [comment]
nodecliの全体リファクタは終わった https://github.com/asciidwango/js-primer/issues/928

**Comment by lacolaco** [comment]
---- ここからログ

**Comment by azu** [comment]
https://cheats.rs/

**Comment by azu** [comment]
チートシート

**Comment by azu** [comment]
> [テスト駆動開発](https://tatsu-zine.com/books/test-driven-development)の"付録C: 訳者解説:テスト駆動開発の現在" っぽくエッセイを書くとかありかも。

**Comment by lacolaco** [comment]
"エコシステム" ってなに？っていう話

**Comment by azu** [comment]
https://github.com/ljharb

**Comment by azu** [comment]
言語作者がいないというのは特徴

**Comment by azu** [comment]
サブタイトル

#865

**Comment by azu** [comment]
迷わず学べる

**Comment by azu** [comment]
迷わず学べる基本文法

**Comment by lacolaco** [comment]
> 基礎は認識や価値観を培う土台、基本は基礎の上に立つ応用。 獲得した基本は次の学習の基礎になる。 （2）建築物の重量を支え、安定させるために設ける建物の最下部の構造。 物事が成り立つためのよりどころとなるおおもと。

**Comment by azu** [comment]
本格的

**Comment by azu** [comment]
真剣にJavaScriptを学べる本

**Comment by lacolaco** [comment]
> C++の教科書
> > 基礎からしっかり学ぶ

**Comment by azu** [comment]
構文とサンプルコードから体系的にC＋＋を学べる入門書。

**Comment by azu** [comment]
- 基礎から
- 基礎を

基礎から

**Comment by lacolaco** [comment]
基礎から学ぶJavaScriptの入門書

**Comment by azu** [comment]
長く使えるように書いてる という意味合い

**Comment by azu** [comment]
ずっと役立つ基礎を学べるJavaScriptの入門

**Comment by azu** [comment]
JavaScriptをちゃんと学べる入門
[2019年前半の「JavaScriptをちゃんとやるための地図」](https://techracho.bpsinc.jp/hachi8833/2019_06_28/75994)

**Comment by azu** [comment]
> 本書では、Vue.jsの中核である、ページを構成するUI部品「コンポーネント」をしっかりと解説し、さらには本格的なアプリ開発で必要となる要素までを網羅的に取り扱います。丁寧な解説でよくわかる、入門書の決定版です!
> https://www.amazon.co.jp/dp/4815601828/

**Comment by azu** [comment]
(副詞 +) basic + JavaScript + 入門

**Comment by lacolaco** [comment]
迷わないJavaScript入門

**Comment by azu** [comment]
迷わず基礎から学べるJavaScript入門

**Comment by lacolaco** [comment]
基礎からはじめるJavaScript入門

**Comment by azu** [comment]
体系的

**Comment by kahei** [comment]
もう迷わないJavaScript入門
ずっと役立つ基礎を身につける！

**Comment by azu** [comment]
JavaScript Primer
基礎から学べるJavaScript入門

〜 迷わずにJavaScriptを学ぶ！ 〜

**Comment by lacolaco** [comment]
`...array` を説明していない話

**Comment by lacolaco** [comment]
> [..."あいうえお"]
> (5) ["あ", "い", "う", "え", "お"]

**Comment by azu** [comment]
Iterableの展開 みたいなのを配列を入れる

**Comment by azu** [comment]
結合 で spread
関数への引数展開 で spread

**Comment by azu** [comment]
結合: spread 
function spread: https://jsprimer.net/basic/function-declaration/#rest-parameters

**Comment by lacolaco** [comment]
Restのところでspreadを教えておかないと、配列を展開せずに引数に渡すと第1引数に配列として渡っちゃうよ、というのが解決できない
