### ISSUE TITLE
2016年7月29日 MTG アジェンダ/メモ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#96]
先に話しておきたい事を書いておく場所です。

マイルストーン

- [7th Meeting Milestone](https://github.com/asciidwango/js-primer/milestone/2 "7th Meeting Milestone")

**Comment by azu** [comment]
吉野家 問題 https://github.com/asciidwango/js-primer/pull/95#discussion_r71451112

**Comment by laco0416** [comment]
footnoteの運用方法みたいなところ。どのくらいからコラムに逃がすべきか、本文＋リンクにすべきかみたいな雰囲気の話

**Comment by azu** [comment]
ローカルサーバ https://github.com/asciidwango/js-primer/issues/79

**Comment by azu** [comment]
[はじめに/本書の目的 · Issue #103 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/103 "はじめに/本書の目的 · Issue #103 · asciidwango/js-primer")

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/82 
スクリーンショット サイズと枠線について

**Comment by azu** [comment]
-----

ここから開始

**Comment by azu** [comment]
"吉野家" で問題なさそうなので、"吉野家" にする。

**Comment by azu** [comment]
脚注や参照リンクを多用するのは微妙。
脚注は読まなくても良い物という感じを入れる。(必要な人は脚注を読むというもの)
コラムは本文とは異なってるけど、入れておきたいものを入れる。

**Comment by azu** [comment]
ローカルサーバはnode-static ってことになった

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/103#issuecomment-234762881
何かを作ろうとした時に、それをどうやって調べていけば、書けるのかを学ぶ本

**Comment by azu** [comment]
演算子のところが少しリファレンスに寄りすぎているのではという話

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/source/ajaxapp/firefox-launch.applescript 今は 1280 x 720 になってる

**Comment by azu** [comment]
図版の中の文字サイズが大きさが一定となるように調整するのが定番
本文の文字サイズと揃ってる最高そう

**Comment by azu** [comment]
全体を見せるときは、文字が読めなくてもいい

**Comment by azu** [comment]
画像自体には枠なしで、CSSや本側の処理で枠を付ける

**Comment by azu** [comment]
図形はやっぱり話として出てきてから考える

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/94 について。
UseCaseの方で話された内容を元に書くという方向で。

**Comment by azu** [comment]
https://github.com/yoshuawuyts/choo Tagged Templateについて

**Comment by laco0416** [comment]
Ajaxappのほうでやってるエスケープの使い方はよくある使い方として紹介でよさそう

**Comment by azu** [comment]
関数 #20 で（）ではない関数の呼び出し方というTagged Template

**Comment by laco0416** [comment]
https://www.ipa.go.jp/security/vuln/websecurity.html

**Comment by azu** [comment]
海外だと セキュリティならOWASPかなー

**Comment by azu** [comment]
#102 DOM-based XSSについて簡単に触れてるものでいい感じの参考資料が欲しい。

**Comment by azu** [comment]
https://www.amazon.co.jp/dp/479814343X/

**Comment by azu** [comment]
[クロスサイトスクリプティング - 用語集 | MDN](https://developer.mozilla.org/ja/docs/Glossary/Cross-site_scripting "クロスサイトスクリプティング - 用語集 | MDN")

**Comment by laco0416** [comment]
脚注 or リンクでIPAかMDNへのリンクを出すくらいにする

**Comment by azu** [comment]
http://gihyo.jp/dev/serial/01/javascript-security/0002 hasegawaさんのやつ

**Comment by laco0416** [comment]
即時関数の紹介(読み方)の話からイディオムの話へ https://github.com/asciidwango/js-primer/issues/108

**Comment by azu** [comment]
ESLintで学ぶプラクティス https://github.com/asciidwango/js-primer/issues/103#issuecomment-236161551

**Comment by azu** [comment]
使わない文法とか色々あるはずなので、
[既に使わなくてイディオム/文法 · Issue #108 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/108 "既に使わなくてイディオム/文法 · Issue #108 · asciidwango/js-primer") を作った

**Comment by azu** [comment]
Generatorはまだ日常的に使われてない感じなので、深くは触れないかも
