### ISSUE TITLE
マークダウンが適切にあたってないようです

### ISSUE THREAD

**Issue by koji-kimura** [asciidwango/js-primer#960]
## 該当ページ
- https://jsprimer.net/use-case/todoapp/form-event/ 

## 説明

たとえばこのあたりです。

> ```js formElement.addEventListener("submit", (event) => { // submitイベントの本来の動作を止める event.preventDefault(); console.log(`入力欄の値: ${inputElement.value}`); }); ``` 現在のURLに対してフォームを送信が行われると、結果的にページがリロードされてしまいます。 そのため、`event.preventDefault()`を呼び出し、デフォルトの動作をキャンセルしていました。 これは`event.preventDefault()`をコメントアウトすると、ページがリロードされてしまうことが確認できます。

**Comment by azu** [comment]
HTMLタグをそのまま書いた場所がおかしいみたいですね。
空改行を入れないと上手く行かないのかも…

**Comment by azu** [comment]
修正しました。ご報告ありがとうございます。
