### ISSUE TITLE
2019-10-07: ミーティングアジャンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#968]
2019年10月7日のアジェンダ。

**Comment by azu** [comment]
#957 https://github.com/asciidwango/js-primer/compare/essay?diff=unified&expand=1&short_path=608db52#diff-608db526782750877bf4caa38573b801
エッセイをちょっと書いてたけど、歴史そのものに焦点置いちゃうとただのおもしろ話になるので、そこから何が学べるのかをベースにしたいな

**Comment by azu** [comment]
#963 ES2015みたいなラベル 書籍だとどういう表現にするかとか。ちょっと考えたい

**Comment by azu** [comment]
------

ここからログ

**Comment by azu** [comment]
エッセイの着地点が難しい

**Comment by azu** [comment]
今のJavaScriptこういう状態で、それはこういう背景となっている方が読みやすい

**Comment by azu** [comment]
エコシステムとは?

**Comment by azu** [comment]
エコシステムは雰囲気だと思う

**Comment by azu** [comment]
https://www.swyx.io/writing/js-tooling/
ここにあったやつ

**Comment by azu** [comment]
https://web.archive.org/web/20191001081621/https://www.swyx.io/writing/js-tooling/

**Comment by lacolaco** [comment]
https://github.com/asciidwango/js-primer/issues/956#issuecomment-529420974

> 言語作者がいないというのは特徴

**Comment by azu** [comment]
ライブラリが一級市民

**Comment by lacolaco** [comment]
JavaScriptが変化してきた理由と、これからも変化する理由

**Comment by lacolaco** [comment]
Webを停滞させず、かつ独占させないための仕組み

**Comment by azu** [comment]
大きなテーマを最初に書いて、それを掘っていく感じで書くとか

- エコシステム(初見だと雰囲気がわかりにくいやつ)
	- Node.js的な話
- プロセス? 
	- ES2015がゴール

ユースケースが無限に変化しがち。

**Comment by azu** [comment]
この本読んだ後に、babelとかwebpack触る必要が出てきたときになんでオフィシャルツールが無いんだっけ?ということを感覚的に分かるような内容。

**Comment by lacolaco** [comment]
混沌であることを認めた上で、混沌であることの意味（意義？）を理解すると、現在未来の混沌がただの理不尽や欠陥ではないと思えるのかな

**Comment by azu** [comment]
ウェブの基本が積み重ねていく文化
これは後方互換性、相互運用性が大きい?

**Comment by azu** [comment]
過去、現在、未来

- 一度、標準化すると消せない
- 試してない機能を仕様化しても使われない

**Comment by azu** [comment]
「変化を続けていくJavaScript」
必要があれば新しい機能が追加される。

**Comment by lacolaco** [comment]
世界がWebに求めるものがどんどん変わっていく上にJavaScriptの変化がある

**Comment by azu** [comment]
変化を望まない人もいるけど、変化を望む人の方がまだ多いので変化してる。

**Comment by azu** [comment]
変化をしつづけるの と 後方互換性を守る を両方やろうとしてる のが JavaScriptの複雑さを表現してる。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/970

**Comment by azu** [comment]
まずMarkdownレベルで修正。

まえがき
https://github.com/asciidwango/js-primer/projects/5

**Comment by azu** [comment]
まえがきの著者紹介とか謝辞は後でいい。

**Comment by azu** [comment]
11月5日の本文のフリーズ日

**Comment by azu** [comment]
#971 著者紹介は本文に入れても良い

**Comment by lacolaco** [comment]
著者紹介 issue https://github.com/asciidwango/js-primer/issues/971

**Comment by azu** [comment]
https://asciidwango.jp/
表紙

**Comment by lacolaco** [comment]
表紙のイラスト（写真）は宿題　年内

**Comment by lacolaco** [comment]
- 自由の女神

**Comment by lacolaco** [comment]
- サグラダ・ファミリア (完成しない感じ）

**Comment by lacolaco** [comment]
- コーヒー

**Comment by azu** [comment]
- 隼

**Comment by azu** [comment]
- mocha
