### ISSUE TITLE
関数とthis

### ISSUE THREAD

**Issue by motchy869** [asciidwango/js-primer#969]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/function-this/README.md

> 属性を指定してない場合
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/basic/function-this/README.md#L42 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/basic/function-this/README.md#L42>

「していない」のタイプミスと思われましたので報告致します。

URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/class/README.md

> 適応
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/basic/class/README.md#L20 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/basic/class/README.md#L20>

「適用」の間違いかと思われましたので、報告致します。

宜しくお願い致します。

**Comment by azu** [comment]
修正しました。ありがとうございます
