### ISSUE TITLE
Node.js 12.x に変更する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#976]
<del>10.x</del><ins>12.x</ins> がLTS https://github.com/nodejs/Release なので12を使うように変更する。

12.xのLTSリリースは2019/10/21の予定。

- README
- usecaseの nodecli、`-v` のところ とか
- https://github.com/asciidwango/js-primer/blob/master/book.json

**Comment by azu** [comment]
Node.js 12のLTSが21日にでる

**Comment by azu** [comment]
そっちを待ったほうがいいかもしれない

**Comment by numb86** [comment]
やりたいです。
`8.x`系になっている箇所を21日以降に`12.x`系にすればよいでしょうか？

**Comment by azu** [comment]
@numb86 ありがとうございます。

そうですね。
book.json にバージョンが定義されてるので、それを12のLTSバージョンに書き換えるのと、
もし文章中にNode 8.x と思われる記述があったら修正する感じですね。

https://github.com/asciidwango/js-primer/blob/4d8ea36f7cb25f8d6409f3c935ec995a7b8e5c06/book.json#L23

今気づきましたが、同梱されるnpmもアップデートされてると思うので、それも同じようにアップデートする感じですね。文章的に見る部分はnodecliの章だけになると思います。

後、トップのREADMEもNode 8となってるのを12としておきたいですね。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/.travis.yml

CIの方はすでにNode 12でも回してたので特に変更は必要なさそうでした。

**Comment by azu** [comment]
LTSのリリースは次のIssueかブログあたりで告知されると思います。

- [Node.js](https://nodejs.org/en/blog/)
- [v12.13.0 'Erbium' release proposal by targos · Pull Request #29981 · nodejs/node](https://github.com/nodejs/node/pull/29981)

**Comment by numb86** [comment]
ありがとうございます。
確認して作業を進めます。

**Comment by azu** [comment]
fixed by #982
