### ISSUE TITLE
非同期処理:コールバック/Promise/Async Function

### ISSUE THREAD

**Issue by motchy869** [asciidwango/js-primer#978]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/async/README.md

> timeout`関数は指定ミリ秒経過すると`reject`する
> [:memo:](https://github.com/asciidwango/js-primer/edit/master/source/basic/async/README.md#L1157 "Edit") <https://github.com/asciidwango/js-primer/blob/master/source/basic/async/README.md#L1157>

この文は正しいですが、その下のサンプルコードのコメントの1行目における resolve が reject の書き間違いかと思われましたので報告致します。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/source/basic/async/README.md#L1164

ホントですね。ご報告ありがとうございます
