### ISSUE TITLE
アプリの構成要素/5. Todoアイテム数の表示 カタカナから漢字の適用

### ISSUE THREAD

**Issue by mendelssohnbach** [asciidwango/js-primer#979]
## 該当ページ

[アプリの構成要素](https://jsprimer.net/use-case/todoapp/app-structure/)

[5. Todoアイテム数の表示](https://jsprimer.net/use-case/todoapp/app-structure/#comment-todo-count)

## 説明

`0コ` は `0個` 

```text
 初期表示時はTodoリストが空であるため0コとなりますが、
```

```text
 初期表示時はTodoリストが空であるため0個となりますが、
```

間違いではありません。現在の記述でも問題はありません。

**Comment by azu** [comment]
`コ` は `個` のカタカナ表記で意味的な違いはないと思いますが、
文中だと`個`だと少し硬い感じがして`コ`を選んでしまうことが多いですね。

`個`の方が多分正式?(`コ`の元となる表記?)なので、`コ`に違和感がある人がいるなら`個`に変えてしまうのもいいと思います。

**Comment by azu** [comment]
@mendelssohnbach #980 で変更してみました。

https://deploy-preview-980--js-primer.netlify.com/use-case/todoapp/app-structure/#comment-todo-count
から確認できますが、違和感ないでしょうか?

**Comment by mendelssohnbach** [comment]
Proposal 確認しました。

個人的には違和感はありません。
