### ISSUE TITLE
入力内容をコンソールに表示する：　助詞の使われ方

### ISSUE THREAD

**Issue by mendelssohnbach** [asciidwango/js-primer#983]
## 該当ページ

[Todoアイテムの追加を実装する](https://jsprimer.net/use-case/todoapp/form-event/)

[入力内容をコンソールに表示する](https://jsprimer.net/use-case/todoapp/form-event/#input-to-console)

## 説明

`を` より `の` を使ったほうが適切ではないでしょうか？

`src/App.jsより抜粋` コードの直下

```text
現在のURLに対してフォームを送信が行われると、
```

```text
現在のURLに対してフォームの送信が行われると、
```

現在のままでも意味の把握は可能です。

**Comment by azu** [comment]
> `現在のURLに対してフォームの送信が行われると、`

のほうが良さそうでうね。
ありがとうございます。

**Comment by mendelssohnbach** [comment]
> そのままPull Request送ってもらっても大丈夫です。

Pull Requestの使い方すら知らない初心者です。

**Comment by azu** [comment]
ブラウザから直接編集できるので、次のような手順でPull Reqeustが出せると思います。

1. https://github.com/asciidwango/js-primer/edit/master/source/use-case/todoapp/form-event/README.md#L102 を開くと編集画面になる
　　- https://github.com/asciidwango/js-primer/blob/master/source/use-case/todoapp/form-event/README.md の 📝 Editアイコンからでも同じです
2. 修正箇所を書き換える(エディタ内でCmd+FとかCtrl+Fを入力すると検索ボックスが開く)

![image](https://user-images.githubusercontent.com/19714/67360370-ae56b000-f5a0-11e9-9d1a-beb515de1e73.png)

3. Commit Messageのタイトル部分に修正概要を入力して "Propose file change"ボタンを押す
  - new branchは適当な名前で大丈夫です

![image](https://user-images.githubusercontent.com/19714/67360472-01c8fe00-f5a1-11e9-8465-7f425b53504b.png)

4. Pull Reqeust作成画面に行くので、そのまま"Create Pull Request"ボタンを押す
5. これでPull Reqeustが出せると思います。。

[プルリクエストの作成方法 - GitHub ヘルプ](https://help.github.com/ja/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

**Comment by mendelssohnbach** [comment]
> new branchは適当な名前で大丈夫です

https://github.com/asciidwango/js-primer/blob/master/source/use-case/todoapp/form-event/README.md

上記、URLより行いました。
branchを選択する画面が表示されませんでした。

Open pull request までいくことができたので、操作してみました。

手違いがあるかもしれません。申し訳ありません。

**Comment by azu** [comment]
@mendelssohnbach リポジトリの管理者とそうでない場合で若干UIが違うからっぽいですね。
Pull Requestありがとうございます！
