### ISSUE TITLE
ajax: fetchUserInfoでのエラーがすべてネットワークエラーになってしまう

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#990]
```js
function fetchUserInfo(userId) {
    return fetch(`https://api.github.com/users/${userId}`)
        .then(response => {
            if (!response.ok) {
                throw new Error(`${response.status}: ${response.statusText}`);
            } else {
                return response.json();
            }
        }).catch(error => {
            throw new Error("ネットワークエラー");
        });
}

```
このコードだとサーバエラーが発生して、`catch`されてネットワークエラーになってしまう。

**Comment by azu** [comment]
```js
function fetchUserInfo(userId) {
    return fetch(`https://api.github.com/users/${userId}`)
        .then(response => {
            if (!response.ok) {
                throw new Error(`${response.status}: ${response.statusText}`);
            } else {
                return response.json();
            }
        }, (error) => {
            throw new Error("ネットワークエラー");
        });
}
```

こうだと意図した感じになるんだろうけど。文章が全部catchの流れで書かれるので調整が必要そう。
あと`throw`使ってるのもブレークポイント的に良くないので`Promise.reject`にしたい。

**Comment by azu** [comment]
@lacolaco これどうするのがいいですかね。

fetchUserInfoがpromiseを返すようになった時点で、fetchUserInfo関数内でエラーハンドリングするのではなく、これを使う側でエラーハンドリングするため、catchメソッドは消します みたいな感じにして、
`catch`自体を消すのがいい気はします。

**Comment by azu** [comment]
https://jsprimer.net/use-case/ajaxapp/http/
https://jsprimer.net/use-case/ajaxapp/display/#escape-html
うーん、でもこの時点でもthenメソッドでエラーが発生したら”ネットワークエラー"になってしまって良くない気がする。

**Comment by azu** [comment]
> fetchUserInfoがpromiseを返すようになった時点で、fetchUserInfo関数内でエラーハンドリングするのではなく、これを使う側でエラーハンドリングするため、catchメソッドは消します みたいな感じにして、
> `catch`自体を消すのがいい気はします。

+ 最初から単純な`console.error(error)`にするとかが良い気はする

**Comment by lacolaco** [comment]
その方針にしましょう

**Comment by lacolaco** [comment]
しかしrejectとthrowでスタックトレース変わるの知りませんでした
