### ISSUE TITLE
Dateについての説明の改善案: mutableについて

### ISSUE THREAD

**Issue by munierujp** [asciidwango/js-primer#998]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/date/README.md

配列についての説明で破壊的なメソッドについて触れているように、Dateクラスがミュータブルであることについて触れるべきかと思います。
また、その場合ライブラリの例としてmomentではなくluxonを載せるとよいでしょう。

**Comment by azu** [comment]
提案ありがとうございます。

luxonを出すならImmutableではなくIntlベースという点になる気がします。
ここではDateの機能の不足を章のメインにしているので、Immutableだともっと先のAPIデザインよりの話になってしまう気がします。
Date#setHoursとか基本的なAPIの紹介すらも意図的に省いてるので、ちょっとImmutableについて書くには説明不足な感じになっちゃう気がしますね。
配列はAPIについてじっくりやっているので、その特徴であるmutableとimmutableの話がでてきますが、Dateはそうでもないので。

単純に追加するだけでは意図が不明瞭になると思うので、Immutableについて足すならDate全体にもっと厚みをもたせる必要性が出てくる気がします。
たとえば、momentについて触れてmomentがmutableである話とi18n apiが整備されてきたことで新しいライブラリが増えてきたことについて書くなど、ただこの書籍としてライブラリを紹介するのは目的ではないので、ちょっとむずかしい気がします。

- https://jsprimer.net/intro/#do-not

Refs: [Date/i18n · Issue #125 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/125)

多分今追加することはない気がするので一旦closeします。
